### ISSUE TITLE
Tutorial Projects and Demos

### ISSUE THREAD

**Issue by afolson** [meltano/meltano#5953]
- [K8](https://github.com/meltano/meltano/issues/6266)
- Docker
- Lightdash
- DBT
- Deploying github actions
- Helm

**Comment by emilylucie** [comment]
@afolson I would like to break these out into separate issues to start chipping away at them and planning timelines. With that in mind are you able to give me a rough overview of what you might expect to see in these tutorials and demos. Looking for a breakdown in a couple bullet points in what each tutorial or demo might ential. Is there a formula we can use?

**Comment by afolson** [comment]
@emilylucie Yeah I'll open separate issues for these. I think this was one of the issues that came out of an engineering meeting so it was never fleshed out.

I don't think there's going to be a formula for these. Maybe deployment ones will be relatively consistent in getting you from project to deployment but for the most part I think these are all different enough that the outlines won't be the same.
