### ISSUE TITLE
Method to 'lock' plugins in a project and update existing lock files

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#5961]
So that we can fully move off of `discovery.yml`, we should add a method to lock all plugins.

> @aaronsteers from your last comment on the GitLab issue, will you create a relevant "lock all" issue? I'm not seeing one in https://github.com/meltano/meltano/issues?q=is%3Aissue+is%3Aopen+lock

Proposed spec details:

- https://github.com/meltano/meltano/issues/5961#issuecomment-1145378980

_Originally posted by @tayloramurphy in https://github.com/meltano/meltano/issues/5925#issuecomment-1141520551_

**Comment by aaronsteers** [comment]
@edgarrmondragon - Yes, I think basically this would be it.

We would likely want an `all` or `--all` option.

We probably also need to consider at the same time what our `update`/`upgrade` command should be.

1. We could extend [`meltano upgrade`](https://docs.meltano.com/reference/command-line-interface.html#upgrade)
2. We could add a new `meltano update`.
3. We could add a `--update` to `meltano add` and just have users essentially just re-run `meltano add`.
4. We could add `--update` to the proposed `meltano lock` where running _with_ `--update` would pull the latest and running _without_ `--update` would be a noop when a lockfile already exists.

I think my preference is to use `--update` on `meltano lock`, but would be important for us to decide before we build `meltano lock`.

Also, if we can take the name of the plugin without the plugin type, that would be nice. So, preferring the `meltano config` syntax, where plugin type only needs to be provided if there's a name collision.

**Comment by aaronsteers** [comment]
@edgarrmondragon - Great, thanks.

Then I think our syntax would be something like

```
# Lock the plugin def - if not already locked
meltano lock tap-salesforce

# Lock the plugin def - updating from source if a new definition is available
meltano lock --update tap-salesforce

# Lock the plugin def - with explicit plugin type in case there is a name collision
meltano lock --plugin-type=extractor tap-salesforce
```

Does this look right to you @edgarrmondragon and @tayloramurphy ?

**Comment by edgarrmondragon** [comment]
@aaronsteers Yup, that looks good

**Comment by tayloramurphy** [comment]
@aaronsteers @edgarrmondragon  the only nit I have is that it's not clear to me that simply running `meltano lock` will lock everything. 

Looking at our own prior art we have a few ways of selecting "all":

* `meltano config <plugin> list` # lists all settings for a given plugin
* `meltano discover all` # discover all plugins
* `meltano job list` # list all jobs
* `meltano schedule list` # list all schedules
* `meltano select <plugin> --list --all` # list all available entities and attributes
* `meltano test --all` # run all tests for all plugins
* `meltano test <plugin>` # run all tests for one plugin

Given that, my push would be for `meltano lock --all` .

And am I correct in assuming we don't need to worry about variant here given that if 2 variants of the same tap were installed they'd have a different namespace?

**Comment by edgarrmondragon** [comment]
@tayloramurphy I don't feel strongly about either `meltano lock` vs `meltano lock --all` for locking all plugins, but we should establish a consistent guideline because `meltano install` does install all plugins 😅

**Comment by tayloramurphy** [comment]
@edgarrmondragon good point - I made a discussion about this 😄 https://github.com/meltano/meltano/discussions/6018

**Comment by aaronsteers** [comment]
Yeah - I don't feel very strongly either - but we should try to have consistent practices.

I think my preference would be `--all` but in certain contexts `--all` is option and/or the default behavior if nothing else is requested.

Also related: 'interactive' #3153 .
