### ISSUE TITLE
Switch to Winget from Chocolatey 

### ISSUE THREAD

**Issue by visch** [meltano/meltano#5968]
See comments here 

https://github.com/meltano/meltano/pull/5967/files#diff-7622618641d3839332b1af8f4f83486662c86a56ea59e441f758aa2969a32b48R10

For Windows we are currently using Chocolatey for Package Management. Windows now has Winget. With the switch to gitlab this may be easier to switch to? Unclear as we haven't looked into it

**Comment by tayloramurphy** [comment]
Still relevant

**Comment by WillDaSilva** [comment]
We no longer use Chocolatey.
