### ISSUE TITLE
Better document the "env:" key at all levels

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#5969]
The env key isn't discussed holisticially in the "Manage Configuration" section of the docs. 

We mention it in Environments https://docs.meltano.com/concepts/environments and Projects https://docs.meltano.com/concepts/projects but it's not clear that `env` is now a good option for setting environment variables at all levels.

**Comment by aaronsteers** [comment]
@tayloramurphy and @kgpayne - Is it okay to close this and introduce the docs as part of https://github.com/meltano/meltano/issues/6207?

**Comment by tayloramurphy** [comment]
@aaronsteers if we include the definition of done for https://github.com/meltano/meltano/issues/6207 to be updating the docs, then yes.

**Comment by tayloramurphy** [comment]
Duplicate of https://github.com/meltano/meltano/issues/6207
