### ISSUE TITLE
Meltano remove lock file bug

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#5979]
From #5977 I was removing an installed plugin and got this on the command line:

```
❯ meltano remove orchestrator airflow
2022-06-02T15:20:50.385299Z [info     ] Environment 'dev' is active

Removing orchestrator 'airflow'...

Reset orchestrator 'airflow' plugin settings in the system database
Removed orchestrator 'airflow' from meltano.yml
Removed orchestrator 'airflow' from .meltano/orchestrators
Could not find orchestrator 'airflow' in /Users/taylormurphy/Documents/Projects/dev/meltano/addfromhub/plugins/orchestrators/airflow--original.lock to remove
```

In my `plugins/` folder I still have:

```
plugins
  files/
     airflow--meltano.lock
  orchestrators/
     airflow--apache.lock
```

@edgarrmondragon cc @aaronsteers

**Comment by edgarrmondragon** [comment]
@tayloramurphy Ah, the quirks of putting the variant in the filename. `meltano remove` doesn't take the variant name into account and thus tries to remove a plugin with the fallback `original` variant. This wasn't scoped in the original lockfile issue so I didn't dive too deep, but I think I have a fix.
