### ISSUE TITLE
Update terminal environment variable precedence to be in line with currently xfail-ing tests

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/meltano#5982]
We want environment variable resolution to behave as described in [this miro board](https://miro.com/app/board/uXjVO3j_ADw=/).

This behavior is described in test cases written in `tests/meltano/core/test_environment_variables.py`which which currently have `xfail=True`. Behavior should be updated so that these tests pass. The relevant test cases will have a comment referencing this issue.

Related:

- Exploratory issue:
  - https://github.com/meltano/meltano/issues/3100
  - https://github.com/meltano/meltano/pull/5938
- Also found:
  - https://github.com/meltano/meltano/issues/5983
- Xfail (expected-to-fail) tests to fix:  https://github.com/meltano/meltano/commit/17ce6c65d2ea3f4b5851528ec15de45e22843be8

**Comment by aaronsteers** [comment]
@cjohnhanson - Thanks for logging this.

Can you say a bit more of the currently observed behavior you seeing re: terminal environment variable precedence?

For instance, does it appear that terminal context is having highest-level resolution priority instead of the (proposed) lowest?

**Comment by tayloramurphy** [comment]
@aaronsteers what's the weight on this and is this something that can be done for 2.0?

**Comment by cjohnhanson** [comment]
@aaronsteers 
> For instance, does it appear that terminal context is having highest-level resolution priority instead of the (proposed) lowest?
^That's exactly right. Terminal context takes precedence over everything else. If its priority is correct, I believe that all 6 of these tests would start passing.

@tayloramurphy I would weight this at an 8, it definitely requires some exploration but I believe the current behavior is the result of several different parts of the code, there's no single "precedence order" set that we could just change.

**Comment by cjohnhanson** [comment]
@aaronsteers (CC @kgpayne--you might have also come to this conclusion or otherwise have some insight here)

After banging my head against this for a long time, I think I've come to the embarrassing conclusion that current behavior is in line with the spec and I misinterpreted the precedence order when writing these tests.

 Basically, the currently failing tests fail because they have environment variables that are set at the terminal or active environment level _and_ in the plugin- and/or environment-plugin level. I interpreted the precedence order in the spec to indicate that the plugin- or environment-plugin level value should "win", but these tests fail because the values from the terminal or active environment context are "winning" and taking precedence over the plugin- and environment-plugin level values. My mistake in these tests is that the environment variables being tested **are also valid settings for the mock plugin**. This means that the values set for them are resolved into the plugin settings/config and then those resolved settings are mapped to environment variables, which take precedence over the plugin- and environment-plugin level envs. 
 
 The key takeaway here is that **environment variables in terminal or active environment contexts will always take precedence over plugin or environment-plugin values for those same variables _if_ those env variables in question are valid keys for a plugin setting.** My reading of the spec was that plugin or environment-plugin should "win" over terminal or active environment context, but I think this was incorrect and the existing behavior is actually correct.
 
  I think I particularly owe @kgpayne a mea culpa for potentially sending him down an unnecessary rabbit hole in trying to resolve this issue.
  
  I'm going to update the tests to reflect my new reading of the spec and then we can finally close out this issue. FYI @tayloramurphy if you have any additional thoughts on this.

**Comment by tayloramurphy** [comment]
> The key takeaway here is that environment variables in terminal or active environment contexts will always take precedence over plugin or environment-plugin values for those same variables if those env variables in question are valid keys for a plugin setting. My reading of the spec was that plugin or environment-plugin should "win" over terminal or active environment context, but I think this was incorrect and the existing behavior is actually correct.

@cjohnhanson I might need some example meltano.ymls + terminal contexts to understand what you're saying here. Or maybe even having one of the new integration tests would be really helpful in understanding. I'm trying to match what I said in https://github.com/meltano/meltano/issues/6386#issuecomment-1195887590 with what you're saying in your comment and I'm confusing myself.

**Comment by cjohnhanson** [comment]
@tayloramurphy  here's an example that I think demonstrates this pretty well:

If we have this meltano.yml:
```yaml
version: 1
default_environment: dev
project_id: example
plugins:
  utilities:
  - name: ls
    namespace: ls
    executable: ls
    settings:
    - name: from
      kind: string
      value: "root-level plugin-level setting"
environments:
- name: dev
  config:
    plugins:
      utilities:
      - name: ls
      config:
        from: "active environments plugin-level config"
 ```
  and we run:
  ```
  meltano invoke --print-var LS_FROM ls
  ```
  then we'll get:
  ```
  LS_FROM=active environment plugin-level config
  ```
  Which is correct behavior.
  
  _BUT_ if we run:
  ```LS_FROM="terminal context" meltano invoke --print-var LS_FROM ls```
  then we'll get:
  ```
  LS_FROM="terminal context"
  ```
  My initial reading of the spec was that this behavior is incorrect because active-environment plugin-level config should take higher precedence over terminal context. But I think that reading is incorrect and this behavior is actually what we want. Because during plugin settings value resolution, environment variables in the terminal context take precedence over plugin-level config, meaning that the `from` setting for the `ls` plugin gets its value from the terminal environment and then maps that setting onto the `LS_FROM` environment variable in the plugin invocation context. So the `LS_FROM` environment variable in the invocation context in this case isn't coming directly from the terminal context, it's coming from the plugin's settings value resolution, which has the highest priority. 
  
  Does that make sense? Basically, environment variables get mapped to settings values, and then settings values get mapped back to environment variables.

**Comment by tayloramurphy** [comment]
@cjohnhanson I think I realize the gap. This whole time I thought you were talking about environment variable precedence with regard to the `env` at all levels. 

In your example I think yes, what you've described is right. Where I was getting stuck is if a user were to specify `env` containing `LS_FROM: something` anywhere in their meltano.yml then I would expect that to take precedence over what's in the terminal context according to the inheritnance order we discussed in https://github.com/meltano/meltano/issues/6386#issuecomment-1195887590 

@aaronsteers if you could check both our logic here and as a third party to make sure we've reconciled the confusion I'd appreciate it!

**Comment by cjohnhanson** [comment]
@tayloramurphy yes exactly, I failed to disambiguate "environment variables" from "plugin settings" since I think in practice it should be rare to pass to plugins environment variables which are not _also_ configuration settings (or maybe it's not rare and I'm further displaying my ignorance here 😅). The existing unit tests _do_ test for "environment variable precedence with regard to the `env` at all levels" and that precedence behavior works as expected.
