### ISSUE TITLE
Update environment variable inheritance to be in line with currently xfail-ing tests

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/meltano#5983]
Environment variable inheritance should behave as illustrated by the `STACKED` variables in [this issue description](https://gitlab.com/meltano/meltano/-/issues/3173). There is a test written for this behavior in `tests/meltano/core/test_environment_variables.py` which is currently marked to `xfail`. Inheritance behavior should be updated so that this test passes.

## Related: 

- Exploratory issue:
  - https://github.com/meltano/meltano/issues/3100
  - https://github.com/meltano/meltano/pull/5938
- Also found:
  - https://github.com/meltano/meltano/issues/5982
- Xfail (expected-to-fail) tests to fix:  https://github.com/meltano/meltano/commit/17ce6c65d2ea3f4b5851528ec15de45e22843be8

**Comment by aaronsteers** [comment]
@cjohnhanson - Thanks for logging this.

Can you say a bit more of the currently observed behavior you seeing on inheritance/stacking?

For instance, is it something of a name-conflict issue, or are higher-level values simply unavailable during evaluation at lower levels of the tree?

**Comment by cjohnhanson** [comment]
@aaronsteers here's the current behavior, basically environment-level `env` takes precedence and doesn't inherit from variable definition in other "layers". See the `STACKED=3` output line here:
```bash
~/Projects/project-meltano/env-vars/env-vars-3 via 🐍 v3.9.12 (env-vars) on ☁️  cody@codyjhanson.com 
❯ export STACKED=1

~/Projects/project-meltano/env-vars/env-vars-3 via 🐍 v3.9.12 (env-vars) on ☁️  cody@codyjhanson.com 
❯ cat meltano.yml
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: meltano.yml
       │ Size: 667 B
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ version: 1
   2   │ default_environment: dev
   3   │ project_id: 044adc22-cf5b-4c51-9bef-46b512b848fe
   4   │ send_anonymous_usage_stats: false
   5   │ env: "${STACKED}2"
   6   │ plugins:
   7   │   utilities:
   8   │   - name: codys-test-plugin
   9   │     namespace: codys_test_plugin
  10   │     executable: pwd
  11   │     env:
  12   │       STACKED: "${STACKED}4"
  13   │     settings:
  14   │     - name: cody_from
  15   │       env: CODY_FROM
  16   │       kind: string
  17   │       aliases: [cody_from_alias]
  18   │       value: default_value
  19   │ 
  20   │ environments:
  21   │ - name: dev
  22   │   env:
  23   │     STACKED: "${STACKED}3"
  24   │   config:
  25   │     plugins:
  26   │       utilities:
  27   │         - name: codys-test-plugin
  28   │           env:
  29   │             STACKED: "${STACKED}5"
  30   │           config:
  31   │             cody_from_alias: "coming_from_alias"
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

~/Projects/project-meltano/env-vars/env-vars-3 via 🐍 v3.9.12 (env-vars) on ☁️  cody@codyjhanson.com 
❯ meltano invoke --print-var STACKED codys-test-plugin
2022-06-03T21:12:48.422490Z [info     ] Environment 'dev' is active
STACKED=3
/Users/codyhanson/Projects/project-meltano/env-vars/env-vars-3

```

**Comment by cjohnhanson** [comment]
@tayloramurphy @aaronsteers this might be overly pessimistic, but my best guess on weight for this would be an 4, I think it would just involve correcting the behavior in `PluginContext`. I think I could knock this out this weekend, particularly if @edgarrmondragon is taking over https://github.com/meltano/meltano/issues/3375
