### ISSUE TITLE
Collect process exit events with Snowplow

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#5986]
It would be useful to emit an event to Snowplow when the Python process running Meltano exits. It could let us know how long a process ran for (by comparing the exit timestamp to the `process_creation_timestamp` from the environment context), as well as the exit code.

We'll want to wrap the whole execution of the CLI in a try-finally block. Within the finally block the exit code can be obtained like so in `src/meltano/cli/__init__.py`:

```python
exit_code = None

def main():
    try:
        # <current definition of `main` goes here>
    finally:
        global exit_code
        ex = sys.exc_info()[1]
        if ex is None:
            exit_code = 0
        elif isinstance(ex, SystemExit):
            exit_code = 0 if ex.code is None else ex.code
```

Now that the exit code has been retrieved, we can use an [`atexit`](https://docs.python.org/3/library/atexit.html) handler to emit the Snowplow event. `Tracker.__init__` can register an `atexit` handler with itself as an argument, and that handler can check for an exit code in `meltano.cli`:

```python
def __init__(self, project: Project, ...):
    # <current definition of `Tracker.__init__` goes here>
    atexit.register(self.track_exit_event)

def track_exit_event(self):
    from meltano.cli import exit_code
    self.track_unstruct_event(
        SelfDescribingJson(
            "iglu:com.meltano/exit_event/jsonschema/1-0-0",
            {"code": exit_code, "timestamp": datetime.datetime.utcnow().isoformat() + "Z"}
        )
    )
```

Exit event schema (`src/meltano/core/tracking/schemas/exit_event.json`):

```json
{
    "$schema": "http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#",
    "description": "Schema for a Snowplow event of a process exiting",
    "self": {
        "vendor": "com.meltano",
        "name": "exit_event",
        "format": "jsonschema",
        "version": "1-0-0"
    },
    "type": "object",
    "properties": {
        "code": {
            "description": "The exit code of the process",
            "type": [
                "integer",
                "null"
            ],
            "minimum": 0,
            "maximum": 255
        },
        "timestamp": {
            "description": "The time ",
            "type": "string",
            "pattern": "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d{1,9})?(?:Z|[+-][01]\\d:[0-5]\\d)$",
            "maxLength": 64
        }
    },
    "required": [
        "code",
        "timestamp"
    ],
    "additionalProperties": false
}
```

We probably won't need the timestamp as part of the event itself if Snowplow adds a timestamp to all events automatically.

One downside to how this is currently designed is that it loses the contexts that were active when the exit was triggered. It'll only have the contexts that are active when the `atexit` handler is called.

**Comment by pandemicsyn** [comment]
probably related https://github.com/meltano/meltano/issues/6041

**Comment by WillDaSilva** [comment]
@pnadolny13 if you want to capture exit events in all circumstances, we can do so by running a sidecar or monitor process.

As proposed here, we will capture all exits except for when the process is killed or exits from a segfault/abort on Linux/macOS. Not sure about Windows, which doesn't distinguish between termination and killing.
