### ISSUE TITLE
Was this guide useful? 👍 / 👎 telemetry

### ISSUE THREAD

**Issue by afolson** [meltano/meltano#5988]
It would be good to collect information on how useful our docs are to end users. I'm thinking this can go at the bottom of the side bar with the "Edit this page" stuff.

cc @tayloramurphy In case you have suggestions for tools or have requirements for such a thing.

**Comment by emilylucie** [comment]
@afolson can we push for this next?

**Comment by emilylucie** [comment]
@tayloramurphy we have added this to the product board for triage. I consider it a high priority as it is tied back to OKRS. please let us know what additional you need for scoping.

**Comment by afolson** [comment]
@emilylucie I can implement this, we just need to agree on a solution. I'm currently looking at https://uservoice.com/solutions/feedback-manager but I want to do some more research since that seems like more than we really want right now.

**Comment by emilylucie** [comment]
@tayloramurphy yes we can remove it sorry for the confusion, thanks.

**Comment by emilylucie** [comment]
@afolson closing since you seem to have made an MR for this

**Comment by sbalnojan** [comment]
@afolson any thoughts on this one? I use https://sprig.com/ in my personal newsletter which works "just fine" and almost out of the box. Don't know though if we are able to use the free pricing version.

**Comment by tayloramurphy** [comment]
Not a priority at the moment.
