### ISSUE TITLE
Add from hub: file bundle requires reference not found should warn or error

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#5997]
When using whats currently on `main` to test the add from hub feature with `requires` file bundles, it looks like it just doesnt install the file bundle when the reference isnt found. I would expect it to do something something else, maybe error, or maybe just log a warning that it wasnt found. I'm not sure whats best.

I ran into this by pointing meltano to my local running instance of the hub and adding a non-existant name in requires setting.

cc @edgarrmondragon

**Comment by pnadolny13** [comment]
@tayloramurphy I just synced with Edgar on a zoom and showed him this, it sounds like he knows whats causing it already.

**Comment by aaronsteers** [comment]
@pnadolny13 and @edgarrmondragon - Since it sounds like we can control for this by just having valid refs on the hub, I'm labeling as `urgency::low` - we can loop back on this post-launch.

**Comment by pnadolny13** [comment]
@edgarrmondragon and I have been slacking about this a bit but I'm not able to get add working when I make the change for https://github.com/meltano/hub/issues/246 (draft PR https://github.com/meltano/hub/pull/538) and I think its related to this issue but still trying to figure it out.

Using my local hub instance by toggling https://github.com/meltano/meltano/blob/eee011d2f7e1048d1326cea5cf348969cc591332/src/meltano/core/hub/client.py#L88 to test the following flows.

Passing:
- `airflow` installs properly with its file bundle as expected

Failing:
- I add a new `airflow_test` orchestrator to my local hub with the same orchestrator definition as `airflow` only with name/namespace changed to `airflow_test`. The `requires` still references `airflow` file bundle `meltano` variant.
- I add `airflow_test` and I only get the orchestrator installed but not the file bundle

This makes me think that the `requires` attribute isnt working properly.

**Comment by edgarrmondragon** [comment]
@aaronsteers I second @pnadolny13, this is a bit higher priority since behavior is broken in Meltano

**Comment by aaronsteers** [comment]
Okay, I haven't dug into this as of yet but I'm bumping up to `Iteration 2`, per your input.
