### ISSUE TITLE
Newly launched Snowplow schema versions should be rewound back to 1-0-0

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#5998]
As discussed in the (internal) slack thread: https://meltano.slack.com/archives/C03GKHWS0HM/p1654289111449709?thread_ts=1654287872.611379&cid=C03GKHWS0HM

This became a problem because we wanted to remove/change fields that had already been published during early dev cycles. Snowcatcloud sees updates now (especially those that would remove/change already declared fields) as impossible with the version number we are trying to post to.

The temporary solution is just do local testing with the `igluctl` tool and then just keep bumping the version as needed for each iteration.

On Monday we'll:

1. [ ] Ask Snowcatcloud to purge/nuke the published schemas.
1. [ ] Rewind version numbers back to `1-0-0`.

Long-term solution is that perhaps we need to iterate using a throw-away schema name - or a separate publish endpoint that we don't care about.

**Comment by aaronsteers** [comment]
> [Will Da Silva](https://app.slack.com/team/U03APER4XNY):palm_tree:  [19 minutes ago](https://meltano.slack.com/archives/C03GKHWS0HM/p1654295342102859?thread_ts=1654287872.611379&cid=C03GKHWS0HM)
> [@Florian Hines](https://meltano.slack.com/team/U0238A68LJ3) [@AJ Steers](https://meltano.slack.com/team/UPAD8KBKL) you can overwrite existing versions on SnowcatCloud so long as it hasn't been set to production mode. That's what I've been doing. No validation is performed on fields being added or removed when you do this.

**Comment by aaronsteers** [comment]
@WillDaSilva - Are you able to pick this up, if it is indeed needed?

cc @pandemicsyn in case you have thoughts and/or are already started.

**Comment by pandemicsyn** [comment]
This became a non-issue, gonna go ahead close out.
