### ISSUE TITLE
Settings/capabilities can't be overridden locally for plugin added from the hub with incomplete metadata

### ISSUE THREAD

**Issue by DouweM** [meltano/meltano#6029]
See https://github.com/meltano/meltano/issues/2717#issuecomment-1146363583 and @edgarrmondragon's response.

It means that adding a plugin from the Hub with missing/incorrect metadata leads to user to a bit of a dead end, as they won't be able tweak the `capabilities` and `settings` in their own project to find out what works 😬 They could directly edit the lockfile, but I don't think we want users to actually do that. 

There needs to be a way to for a user to try out metadata changes locally to get the plugin working, before they can contribute them to the Hub, and it doesn't look like there currently is.

We didn't have this issue with `meltano add --custom`, because that would always add a full plugin definition (with a `namespace`) to `meltano.yml` that didn't inherit anything from the Hub or discovery.yml and would allow `capabilities` and `settings` to be set.

**Comment by DouweM** [comment]
@tayloramurphy @aaronsteers I don't think we can launch the "add from Hub" feature as is, since we know that most metadata is incomplete, and there is no way for the user to fix that locally.

**Comment by DouweM** [comment]
@aaronsteers [wrote](https://github.com/meltano/meltano/issues/2717#issuecomment-1146860355):

> Sounds like a bug:
>
> > those properties [capabilities and settings] were only respected on fully custom plugin definitions with a namespace, not on those that inherited from discovery.yml ... and ... the lockfile.
>
> Presumably would be resolved by https://github.com/meltano/meltano/issues/3296

**Comment by aaronsteers** [comment]
> there would still need to be a way to say "don't inherit a plugin definition at all, I'll provide all metadata inline"

It's not clear to me that a missing or present `namespace` value would drive the behavior of 'ignore the lock file'. Is this is the control users need, can we provide another means of doing so? Perhaps a missing `variant` name is a stronger signal, since presently that is expected and used to find a lock file and/or `discovery.yml` entry?

**Comment by DouweM** [comment]
@aaronsteers That meaning of `namespace` is definitely not clear. And I think we can discuss whether the user will need a new way to do so in https://github.com/meltano/meltano/issues/3296. Missing `variant` wouldn't be sufficient, because that already means "use the default variant", and we need to support existing `meltano.yml` projects created before variants were introduced that wouldn't have that key.

Either way, since that won't go into 2.0, I don't think it's directly related to this issue? Or are you saying we don't need to fix this right now because it'd likely be addressed in the process there? I don't think that'll be sufficient as we'll have tons of users installing plugins with missing metadata between 2.0 and then.

**Comment by aaronsteers** [comment]
> Missing variant wouldn't be sufficient, because that already means "use the default variant"

There's no need for the concept of 'default variant' post-installation. We probably should not be doing anything like that in 2.0.

**Comment by aaronsteers** [comment]
> Either way, since that won't go into 2.0, I don't think it's directly related to this issue? Or are you saying we don't need to fix this right now because it'd likely be addressed in the process there? I don't think that'll be sufficient as we'll have tons of users installing plugins with missing metadata between 2.0 and then, who'd currently get stuck.

I do think we need a fix by 2.0, as you mention above.

I'm just calling out we have a few ways to fix this. All of them are going to take time and a bit of scramble.

**Comment by aaronsteers** [comment]
One proposed fix is 'use the presence of variant instead of namespace when deciding whether to inherit from lock files and/or discovery.yml'.

**Comment by DouweM** [comment]
> One proposed fix is 'use the presence of variant instead of namespace when deciding whether to inherit from lock files and/or discovery.yml'.

@aaronsteers I don't understand how that would solve the issue of `capabilities` and `settings` not being overrideable on plugins inheriting from lockfile/discovery? Are you suggesting the user turns off inheritance so that they can define capabilities/settings from scratch? They'd also need to copy over all other properties from the inherited definition then, since inheritenace will be gone. But if we're asking the user to turn off inheritance, I'm not sure what difference it makes if we do that based on the presence of `namespace` or `variant`.

The fix I'm thinking of doesn't change the meaning of `namespace` or `variant` (which is a much bigger topic that I don't want to rush in a few days: https://github.com/meltano/meltano/issues/3296), but would allow `capabilities` and `settings` to be set on inheriting plugins, with `capabilities` overriding the inherited capabilities entirely (as it's a list), and `settings` being merged with the inherited `settings`. The user would still get the benefits of inheritance, with the ability to override locally.

**Comment by DouweM** [comment]
@aaronsteers Let me know if you'd like me to look into this myself! I think I still know this part of the codebase pretty well.

**Comment by aaronsteers** [comment]
@DouweM - Yes, if I understand this correctly, I think this makes sense as a global change.

> The fix I'm thinking of ... would allow capabilities and settings to be set on inheriting plugins, with capabilities overriding the inherited capabilities entirely (as it's a list), and settings being merged with the inherited settings.

Would these then be correct descriptions of the post-solve behavior:

1. In `meltano.yml`, a `capabilities` entry will always replace an available `capabilities` list from the lockfile or discovery definition, regardless of `namespace` value and regardless of whether the plugin was added with `--custom`.
1. In `meltano.yml`, a `settings` entry will always be merged with an available `settings` list from the lockfile or discovery definition, regardless of `namespace` value and regardless of whether the plugin was added with `--custom`.
1. In regards to the `settings` merge behavior, the merge occurs one layer deep (at the per-setting level, not recursive) so `parent.settings[mysettingname]` will be replaced and not merged with `self.settings[mysettingname]`.

Is all that correct?

This seems like a good+safe behavioral change overall, so yes definitely would appreciate the cycles if you have time to implement.

**Comment by DouweM** [comment]
@aaronsteers Yep that's right!

**Comment by DouweM** [comment]
Fixed in https://github.com/meltano/meltano/pull/6033!
