### ISSUE TITLE
Refactor command tracking event/context to be initialized earlier

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6041]
To get things out the door in hurry, the current (although not actually merged yet as of this writing) command tracking events and context are initialized within the cli implementations of those commands. e.g.:

https://github.com/meltano/meltano/blob/762a2592c5da95fa6b1e91aa3c20d79725949a66/src/meltano/cli/invoke.py#L75-L80

But we could (should?) initialize it further up the stack when click is setting up, maybe https://github.com/meltano/meltano/blob/762a2592c5da95fa6b1e91aa3c20d79725949a66/src/meltano/cli/cli.py#L32 ? Then we could also add the global opts like `--log-level` to the tracking context. 

The initialized tracker with appropriate tracking context could then be embedded in the click context (`context` is suddenly a super loaded term for us), and down stream we could pull the tracker from the *click* context:

```python
@click.option("--some-option")
@click.pass_context
def some_cli_command(ctx, some_option):
    tracker = ctx.obj["tracker"] 
```

------

## Related work items

Noted this related issue may be solved at the same time (or not):

- https://github.com/meltano/meltano/issues/6095

If resolved, we can close the other at the same time. If not, we'll re-raise/re-prioritize that after this closes.

/cc @pnadolny13 @aaronsteers @WillDaSilva

**Comment by pandemicsyn** [comment]
Cross post from https://github.com/meltano/meltano/issues/6057 , but that issue talks about tieing together both our new telemetry events and legacy tracking events under a single trace id. IMHO these two issues should be addressed at the same time, and a trace id generated and included in the click context along side already initialized tracker. 

That means that trace id could also be forwarded and configured to be used in things like structured logging and allow it to be used as an **actual** trace id.

**Comment by WillDaSilva** [comment]
I think we can either hook into Click or something like the `pass_project` decorator that is currently used by many CLI commands to automatically instrument them.

With the project instance we could initialize a `Tracker`. The info needed to construct the CLI context could be obtained from Click. Once those are both available, the CLI started event can be fired. Then, once the decorated function returns, we can fire a CLI completed event if no exception was raised, and otherwise we can fire an aborted or failed event depending on what exception was returned. I'm not sure what to do with CLI skipped events - we don't currently seem to use them.

@pandemicsyn @pnadolny13 Is there value in distinguishing between aborted and failed? In either case we get the exception context which provides details such as the exception class name, and the line number it was raised on. We might be better off subclassing/replacing `CliError` with `CliAborted` and `CliFailed`.

**Comment by pandemicsyn** [comment]
>Then, once the decorated function returns, we can fire a CLI completed event if no exception was raised, and otherwise we can fire an aborted or failed event depending on what exception was returned. 

I think thats going to be a challenge, because we don't fire or raise consistent exception types and different exceptions imply different things at different points because of that. Hence me having littered try/excepts all over the cli code now 😢. The main thing i was trying to solve with Aborted vs Failed is to have an easy signal for whether an issue was user induced or meltano induced. Which in hindsight/practice might not be all that reliable. 

@pnadolny13 if you don't find it all that useful, being able to ditch Aborted vs Failed and just having a single state, would definitely let us simplify things **a lot.**

**Comment by WillDaSilva** [comment]
I'll note that the simplification isn't just for the benefit of us Meltano core dev who want "cleaner" code. Any external contributor should be able to add to or edit the Meltano CLI without thinking about telemetry. Making it automatic via a decorator would enable that.

**Comment by pandemicsyn** [comment]
> I think thats going to be a challenge, 

Should clarify, i think its a challenge but we could define some broad buckets that would still help indicate whether something was user induced vs meltano induced. Like if we record a `ScheduleAlreadyExists` exception, thats always going to be user induced.

**Comment by pnadolny13** [comment]
>@pnadolny13 if you don't find it all that useful, being able to ditch Aborted vs Failed and just having a single state, would definitely let us simplify things a lot.

@pandemicsyn I dont really have a strong opinion. I can see value in having them separate but if its not consistent then I can also see us just lumping them together in the warehouse. It sounded like AJ liked the distinction during office hours. I'd leave it to you all to decide whats best. Is there a way to call it failed but later infer the difference using other attributes? Or would we want to add a new attribute to help us differentiate in the warehouse?

**Comment by aaronsteers** [comment]
@pandemicsyn - When you wrote this distinction and the initial feature we didn't have any exception context, or really any plan of exactly what we'd be getting (if anything from the exception context).

If (or _as_) we feel confident that Exception context is going to have the Exception class name, I think we can be less rigorous with the aborted vs failed distinction, or drop it entirely in favor of raising exceptions that have the distinction built in (such as `JobAlreadyExistsError` as a good example).

What do you think?

**Comment by pandemicsyn** [comment]
#6260 didn't cover all the commands, will send up another to cover the (few) remaining
