### ISSUE TITLE
Pre-2.0 versions should still work with `env_aliases`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6049]
We received a report this morning [in slack](https://meltano.slack.com/archives/C01TCRBBJD7/p1654603659407119?thread_ts=1654597663.385549&cid=C01TCRBBJD7) that the `env_aliases` were broken in pre-2.0 versions.

This was not intended to be broken in pre-2.0  versions.

**Comment by aaronsteers** [comment]
@tayloramurphy, @kgpayne, @pandemicsyn - I'm not sure what the best resolve here is.

**Comment by aaronsteers** [comment]
I've merged a version bump on `discovery.yml` so that existing versions of Meltano (pre-2.0) should in theory fall back to the version of `meltano.yml` that was bundled with their installation rather.

**Comment by tayloramurphy** [comment]
Looks like this is good to close, right?
