### ISSUE TITLE
Telemetry - Shared UUID to tie unstructured and structured events

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6057]
As a follow on from https://github.com/meltano/meltano/pull/6028:

We're sending duplicate structured events along side our new unstructured events as a failsafe in case our new events have bugs. If we do end up having bugs and need to take all unstructured events and blend in structured events that are missing we need a way to tie them together. The SQL could say "give me all the unstructured events, and all the structured events where context_uuid isnt in that set of unstructured events".

The unstructured environment context has a `context_uuid` thats shared across all unstructured events in an execution session, could we append this custom context to the structured events also? Is there another way to add the `context_uuid`? 

cc @pandemicsyn @tayloramurphy @aaronsteers

**Comment by pandemicsyn** [comment]
I think we should probably do this as part of https://github.com/meltano/meltano/issues/6041 and generate a general trace id accessible to anyone with the click cli context AND at the same time use that when initializing the cli tracker (or we can snag the id when tracker is initialized, whatever makes the most sense).

**Comment by pandemicsyn** [comment]
@pnadolny13 Ah because you can't reliably pull in legacy events to fill in the gaps in the new telemetry by project id ?

**Comment by pandemicsyn** [comment]
Quick update. @pnadolny13 and I just paired and think we came up with a simple/quick way to resolve this that we're going to test out. 

Basically we're going to use *the same* ProjectContext for both trackers.

**Comment by pnadolny13** [comment]
> @pnadolny13 Ah because you can't reliably pull in legacy events to fill in the gaps in the new telemetry by project id ?

Yeah like this pseudo code scenario where I have a structured and unstructured event that were fired for the same CLI action by the same user. Theres no shared attribute to tie those CLI invokes together across struct vs unstruct so I'm able to understand that its the same project at about the same time but I cant say for sure these are the same CLI action to be able to dedup, if I had a shared ID I could chose which event I want to drop:

Structured `meltano invoke tap-csv`:
- `meltano invoke tap-csv`
- 2022-06-08 20:00:31.000 (note slightly different TS)
- project_id=123
- event_id =456
- < MISSING Shared UUID >

Unstructured `meltano invoke tap-csv` (1 of 2 total unstruct events):

- `invoke`
- started
- 2022-06-08 20:00:34.000 (note slightly different TS)
- project_id=123
- event_id =91011
- plugin_context.plugin_name = tap-csv
- < MISSING Shared UUID >
