### ISSUE TITLE
PyPi Publish and GitHub Release Tag in CI/CD

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6070]
Rebuilding the tag-based deploy cycle from Gitlab, likely with some adaptations.

**Comment by aaronsteers** [comment]
@edgarrmondragon has picked this up as part of `2.2.0` release.

**Comment by edgarrmondragon** [comment]
Closed by:

- https://github.com/meltano/meltano/pull/6338
- https://github.com/meltano/meltano/pull/6145
- https://github.com/meltano/meltano/pull/6346
- https://github.com/meltano/meltano/pull/6348
