### ISSUE TITLE
Telemetry - Invoke services dont have plugin context or structured event

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6093]
When running a service plugin like superset that blocks for a long time and is then exited using CTRL+C I'm not able to track the plugin context. I think whats happening is:

- `meltano invoke superset:ui` (blocking)
- CLI started event fired when started up. Plugin context isnt available yet
- build dashboards
- CTRL+C
- <MISSING CLI completed/aborted/etc. with plugin context>
- <MISSING structured legacy event>

I think the fact that I need to CTRL+C to close the blocking service plugin means the structured event isnt fire because its not a successful exit and with the new unstructured events we dont get a plugin context. I dont get enough info for these events to be useful, all I know its that `invoke` ran but nothing about what plugin/command (i.e. `ui`)/etc. This is likely undercounting usage of Airflow also because we never get to the successful firing of structured events either. 

Would it be possible to include the plugin context on the first event?

cc @pandemicsyn @tayloramurphy @WillDaSilva

**Comment by WillDaSilva** [comment]
@pandemicsyn @tayloramurphy @pnadolny13 Is there ever a situation where we want to remove context? Currently we use `Tracker.add_context` and `Tracker.with_context` to permanently and temporarily add context respectively.

I ask because if we never want to remove context (i.e. only ever permanently add it) then these sorts of things can be handled with #5986. The first time any context (e.g. the plugin context) is created it would be added permanently to the list of contexts that will be sent on any future event. Then if the process exits for almost any reason we'll get those contexts.

**Comment by pandemicsyn** [comment]
> @pandemicsyn @tayloramurphy @pnadolny13 Is there ever a situation where we want to remove context? Currently we use Tracker.add_context and Tracker.with_context to permanently and temporarily add context respectively.

I can't think of any cases off the top of my head where we'd need to unbind a context. As long as we stick our pattern of binding PluginContexts to the events/things actually using them. i.e. in `meltano run` plugin context is related to the block events, in `etl` its related to the cli event.

**Comment by pandemicsyn** [comment]
@pnadolny13 ok hotfix in bound.

**Comment by pnadolny13** [comment]
@pandemicsyn https://github.com/meltano/meltano/pull/6098 looks like it resolves the plugin context part but I still dont get any exit events. Is that expected? Is there any chance we can attempt to fire one if I CTRL+C my blocking service plugin? Idk how that works

**Comment by pandemicsyn** [comment]
@pnadolny13 yea, thats expected. https://github.com/meltano/meltano/issues/5986 will help with catching exit events in some scenarios. However, keep in mind that depending on **how** the process is killed, we wont be *allowed* to do anything and we just get unceremoniously killed.
