### ISSUE TITLE
Telemetry - `option_keys` to include meltano options also

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6095]
We currently collect most optional arguments like described in https://github.com/meltano/meltano/discussions/6036#discussioncomment-2892418:

```
$ meltano run --dry-run tap-gitalb target-jsonl
command = run
sub_command = None
option_keys = ["dry_run"]

$ meltano schedule set --job
command = schedule
sub_command = set
option_keys = ["job"]

$ meltano invoke something
command = invoke
sub_command = None
options_keys = []
```

We dont collect things like `--log-level=debug` or `--environment=dev`. It would be nice to know what CLI arguments are being used and not used.

cc @pandemicsyn @tayloramurphy this is low priority but we talked about it yesterday and wanted to log it.

**Comment by pandemicsyn** [comment]
👍 we can snag these as part of https://github.com/meltano/meltano/issues/6041 (referenced there too but definitely worth this explicit issue)

**Comment by pandemicsyn** [comment]
I do wonder if we'll want/need a `hashed_options_values` entry at some point that we use selectively/carefully. At least its an easy schema evolution if we do need it since its just an addition.

**Comment by aaronsteers** [comment]
@pandemicsyn and @tayloramurphy - Per these comments, I'm removing this from our Engineering Assignments board, but with a mention in the description of #6041 that we can opportunistically solve this issue there if feasible.

**Comment by pandemicsyn** [comment]
@aaronsteers this actually was one of the bigger pieces that was fixed yesterday as part of https://github.com/meltano/meltano/issues/6041 , so gonna go ahead close.

**Comment by tayloramurphy** [comment]
@pandemicsyn can you cross-link the PR? Catching up from vacation and the context isn't clear here.
