### ISSUE TITLE
Improve documentation around (scheduled) jobs

### ISSUE THREAD

**Issue by DouweM** [meltano/meltano#6102]
Does https://docs.meltano.com/reference/command-line-interface#job put jobs in `meltano.yml`? What does that look like? It’s not documented under https://docs.meltano.com/concepts/project#meltanoyml-project-file.

https://docs.meltano.com/guide/orchestration#create-a-schedule also doesn’t mention scheduling a job, and should.

It’s also not clear to me what “Add a new job with multiple tasks by passing arrays in yaml format, where each item representing a run command.” means in https://docs.meltano.com/reference/command-line-interface#job. In a job with multiple tasks, do the tasks run in parallel when you call `meltano run <that-job>`?

**Comment by DouweM** [comment]
@tayloramurphy Assigning to you to prioritize

**Comment by DouweM** [comment]
@pandemicsyn Do you have the most context on this feature to improve the docs?

**Comment by aaronsteers** [comment]
@DouweM - I think we need @pandemicsyn to stay focused on Telemtry a bit longer. 

I've added this to `Iteration 3` as unassigned. 

@cjohnhanson, @WillDaSilva - Do either of you have capacity to pick this up?

**Comment by cjohnhanson** [comment]
@aaronsteers Yeah I can pick this up this afternoon. I'll definitely need a PR review from @pandemicsyn to double check my understanding though.

**Comment by aaronsteers** [comment]
Thanks, @cjohnhanson !

Greatly appreciated.

**Comment by aaronsteers** [comment]
Let us know if you need any more info from me (or more likely @DouweM as the requestor) on what is/isn't clear.

**Comment by DouweM** [comment]
@cjohnhanson Reopened because there are some more points to address: https://github.com/meltano/meltano/pull/6112#pullrequestreview-1000511531
