### ISSUE TITLE
Improve Hub plugin definition contribution docs

### ISSUE THREAD

**Issue by DouweM** [meltano/meltano#6107]
## Background

https://docs.meltano.com/contribute/plugins should explain exactly how to build a plugin definition for the Hub, including new values like `requires` (https://github.com/meltano/meltano/issues/6106), and the new `usage`/`prereq`/`settings_preamble` properties that build the detail pages.

## Spec

To add to plugin definition reference (the yaml stuff):

- `requires`
- `settings` - and how this relates to `config`
- `capabilities` - and how tap developers can determine the correct capabilities
- `container_spec` - per https://github.com/meltano/meltano/issues/6408#issuecomment-1190924489

Hub-only YAML fields:
- `prereqs` markdown field
- `settings_preamble` markdown field
- `usage` markdown field

To add to contributing docs:

- Link to plugin reference page.
- Instructions for submitting.
- Details on how the markdown will be rendered in our readmes docs.
- A small blurb on how we capture metrics for the hub.
- Details on how this shows up on the REST API.
- Info on how users will install the plugin after it is published.

**Comment by aaronsteers** [comment]
@DouweM, @tayloramurphy, @afolson - I'd like to resolve this by spliting this page into two.

We currently have it as `Contributing` > `Plugins` but so much of that content actually belongs under something like `Reference` > `Plugin Definitions`.

This is important because both "Contribute a plugin" and "Add a Custom Plugin" should be working from the same reference doc (with a call out inline if certain settings only apply to one or the other).

**Comment by DouweM** [comment]
Closed https://gitlab.com/meltano/meltano/-/issues/2384 as a dupe. Don't forget to check out the comments in https://gitlab.com/meltano/meltano/-/issues/2384 as well.

**Comment by DouweM** [comment]
@aaronsteers Splitting makes sense.

**Comment by aaronsteers** [comment]
@DouweM - I've scraped all the context I could from those other issues into the issue description. 

If there's anything else you want to add, please feel free. As clear as we can be upfront, the more likely I think we'll get everything covered.

**Comment by aaronsteers** [comment]
Should the Meltano `contributing plugins` instructions live here or on the hub?

**Comment by DouweM** [comment]
@aaronsteers I think it's part of the Meltano contributor guide. Hub doesn't have its own (non-Singer) docs section.

**Comment by aaronsteers** [comment]
That makes sense. I do think the hub should have a page pointing to the Meltano one then.

**Comment by afolson** [comment]
@aaronsteers Yeah I think splitting this into two makes sense. Most of the stuff above the "Plugin Development" section seems like reference material and not really a how to (although there are a few steps there that can probably be referenced in the how to)

**Comment by aaronsteers** [comment]
@afolson, @tayloramurphy, @pandemicsyn, @edgarrmondragon, @cjohnhanson 

I'm imagining a yaml reference for plugins modeled after this [GitHub Yaml Workflow Reference](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses).

1. The "top level" for this "Plugin Definition Yaml Reference" would be the level of the plugin entry, but we could (and should) later do a similar reference for `meltano.yml` config all-up (pointing to this file where plugin definitions are concerned).
2. The Hub contributor docs would point to this plugin definition yaml reference.
3. This plugin definition reference doc would include _all_ valid entries within a plugin definition, including hub-specific metadata. The Hub-specific metadata would be listed as optional, with a note that it is primarily meant for indexing and documentation purposes, not needed for internal/custom plugin definitions as would be listed in `meltano.yml`.

**Comment by edgarrmondragon** [comment]
> I'm imagining a yaml reference for plugins modeled after this [GitHub Yaml Workflow Reference](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses).

@aaronsteers what's they say about great minds? That's what I went for in https://github.com/meltano/meltano/pull/6460 😅 

> For what it's worth, I did _also_ investigated automated approached to document the yaml reference based on our JSON Schema, but none of these investigations came up with fruitful/usable libraries.

I did think about that but came similarly with no out-of-the-box solutions.
