### ISSUE TITLE
`default_environment` can only be set in `meltano.yml`, not using `meltano config meltano set`

### ISSUE THREAD

**Issue by DouweM** [meltano/meltano#6115]
@tayloramurphy pointed out that `meltano config meltano set default_environment prod` or `meltano config meltano unset default_environment` doesn't do anything.

This is because `default_environment` is not actually a setting, but a core property of `meltano.yml`: https://github.com/meltano/meltano/blob/dfd9650170ff97fd69fdff7ac8dc7dc0841bf663/src/meltano/core/meltano_file.py#L21

https://docs.meltano.com/concepts/environments#default-environments doesn’t suggest that `meltano config meltano` would work here, only setting it directly in `meltano.yml`. But https://docs.meltano.com/getting-started#view-and-activate-your-environments does call it a setting, and someone seeing it in `meltano.yml` could reasonably expect it to work just like the other keys in there like `send_anonymous_usage_stats` and `project_id`.

If we want to make it a proper setting, we should be able to define it in `settings.yml` and replace https://github.com/meltano/meltano/blob/main/src/meltano/cli/cli.py#L70 with `ProjectSettingsService(project).get("default_environment")`.

**Comment by aaronsteers** [comment]
@DouweM - Thanks for this writeup. Super helpful.

I don't see any downsides of making it a formal setting. Anything you can anticipate that would keep us from making this change?

cc @tayloramurphy, @edgarrmondragon

**Comment by edgarrmondragon** [comment]
@aaronsteers I don't see any reason why this wouldn't work (or not be improved!) by making it a project setting. It'd even make it possible to toggle it with environment variables.

What I'd worry about is related to https://github.com/meltano/meltano/issues/3419, i.e. what is the effect of

```console
$ meltano config meltano set default_environment
```

**Comment by DouweM** [comment]
@edgarrmondragon Yeah, if `default_environment` is currently `dev`, `meltano config meltano set default_environment prod` would store that under `environments: - dev`. In this case, it really doesn't make any sense to store this anywhere other than the top-level of `meltano.yml`.

**Comment by aaronsteers** [comment]
@DouweM and @tayloramurphy - This should be blocked by 

- #6247 

If we have that in place, and if we categorized this as a Meltano config, this becomes doable as a top-level only setting that can be modified via `.env`, terminal env vars, and a top-level entry in `meltano.yml`.
