### ISSUE TITLE
Prettier CLI outputs with `rich`

### ISSUE THREAD

**Issue by kgpayne** [meltano/meltano#6122]
Meltano currently uses the Click python library for our CLI definition and formatting. Whilst Click is excellent at defining CLI experiences, it is much less effective at formatting. Cross-platform libraries exist, such as rich, for better formatting of Click outputs and structlog logs. As Meltano is CLI-first, improvements in output formatting would positively impact most users.

Example improvements:

From #2971
---

![image](https://user-images.githubusercontent.com/5585874/172839334-b9e4b140-07a9-4821-ae51-7fad8f68067b.png)

With [rich-click](https://github.com/ewels/rich-click):
---

![](https://raw.githubusercontent.com/ewels/rich-click/main/docs/images/command_groups.png)

From #6103
---

Before

<img width="1440" alt="Screenshot 2022-06-08 at 17 44 58" src="https://user-images.githubusercontent.com/5585874/172839610-432424d6-e084-4a1d-bf45-c3214df27fa5.png">

After

<img width="1439" alt="Screenshot 2022-06-09 at 12 49 09" src="https://user-images.githubusercontent.com/5585874/172839746-48c60425-2c2f-464d-a5d8-36498e07737c.png">

**Comment by pandemicsyn** [comment]
Considering the amount of users that have been frustrated with the addition of colored log output and even structured output, I'm not convinced this is actually a path we should make. At least not whole-sale across the entire experience. I could definitely see this being great for specific modes of operations like a settings configuration wizard though!

If we go down this path we should also keep in mind that what makes awesome UI's outstanding is that most don't try to recreate a GUI in the CLI, but highlight and convey important info and statuses in creative ways that _complement_ a terminal experience.

App's that try to use table/cell based CLI layouts or attempt to reproduce GUI behavior patterns, are almost always frustrating. For them to work well you often need a larger terminal size, or they handle resizing poorly, or they have awkward line wrap issues, or non-intuitive nav, etc etc.  I think your own example illustrates how easily they can degrade in text heavy applications.

**Comment by tayloramurphy** [comment]
Pretty sure we did this!

**Comment by WillDaSilva** [comment]
@tayloramurphy This was partially completed by:
- https://github.com/meltano/meltano/issues/2971

But as the issue description explains there is more to be done. The issue description & title would benefit from some refinement.

**Comment by kgpayne** [comment]
@WillDaSilva I'd be in favour of closing this and creating specific issues for the views we'd like to improve.

The history above relating to 'if' we should use rich is outdated and might lead readers to believe rich adoption is still in active discussion 😅
