### ISSUE TITLE
docs: Update 2.0 migration guide to include confusing/scary warning about discovery.yml not being parsed

### ISSUE THREAD

**Issue by DouweM** [meltano/meltano#6128]
As reported in https://meltano.slack.com/archives/C01TCRBBJD7/p1654785151254499:

> I wanted to hold off the upgrade to Meltano 2.0 a bit in case there were some small issues, but now I'm getting `The `discovery.yml` manifest received from https://discovery.meltano.com/discovery.yml could not be parsed.` errors so I guess I have no choice.

It's just a warning, and Meltano will fall back on the cached or bundled copy, but it still makes people seem like something's wrong. We can't go back and make the warning message sound less concerning, of course.

One option would be to roll https://discovery.meltano.com/discovery.yml back to the latest version supported by <2.0 (version 20, iirc), since 2.0 will use the Hub anyway. 2.0 will find an outdated copy at the location, and fall back on its own bundled version, which is OK. It will also show a warning about the remote `discovery.yml`, but there are fewer users on 2.0 than on pre-2.0 affected by that, and we can suppress that in 2.0.x and only use the bundled copy, since the remote discovery.yml won't be updated anymore anyway and the Hub API is the preferred way to look up plugin definitions going forward.

**Comment by kgpayne** [comment]
> We can't go back and make the warning message sound less concerning, of course.

Is it really not possible to cut a new minor release of v1 from a branch right after the last one? I expect it would have to be manual (not sure bump version et al would cope) and we'd need to make the changelog updates back to the tip of `main`(as we would never merge it) but I did think it was a possibility 🤔

**Comment by aaronsteers** [comment]
Ideas I've considered:

1. Introducing a patch version: user still needs to upgrade, and depending on how far back they are, this might _also_ require them to retest things. 
2. Revert discovery.yml as we've published it to the remote endpoint (but perhaps not in the main repo).

I think we could `2` do this safely, but versions of 2.0.0 might then throw their own weird messages, which we could resolve in `2.0.1`. Anyway, functionality shouldn't impact 2.0 users.

**Comment by DouweM** [comment]
@aaronsteers I support 2. We can freeze `discovery.meltano.com/discovery.yml` to the latest version used by <2.0 and never update it again.

**Comment by aaronsteers** [comment]
@DouweM - I agree, but this may still break `2.0` versions, since I don't think we disconnected the inheritance tree. We can do so in a subsequent 2.0.x release, and then ask users if they have problems to update to a newer 2.0 or 2.x version.

We'd need to (1) release a patch on 2.x to ignore the `discovery.yml` published version (if we aren't already doing so), wait a few days, and then (2) revert the published version to match our prior `discovery.yml` file.

**Comment by aaronsteers** [comment]
@DouweM and @tayloramurphy - In terms of priority level here, I am not sure I agree this is something we would prioritize highly. Long-time users of Meltano were/are probably already getting this error message and have been accustomed to ignoring it until they get around to upgrading.

This seems like it's been in the product for so long, I'm not sure why we'd take special action in this case to mitigate the warning/error message when we didn't do so in prior versions. What do you think?

**Comment by DouweM** [comment]
@aaronsteers Good point that this has already been affecting people for a while, but then updating to the latest version would've been less disruptive than it is now. But I guess it's good to motivate people to go through the effort of getting on 2.0!

@tayloramurphy A new FAQ section makes sense to me

**Comment by tayloramurphy** [comment]
@edgarrmondragon did you intend to close this issue with #6543 ?

**Comment by edgarrmondragon** [comment]
@tayloramurphy yes, the warning caused by Ruamel dumping and the trying to parse back `discovery.yml` should be gone now.
