### ISSUE TITLE
Getting Started - Different Systems

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6153]
https://github.com/meltano/meltano/pull/5967#discussion_r886904600

Getting Started has different steps for each OS. They are pretty small differences. Here's some ideas for other options.

1.  Seperate pages for each System
> Old comments
> Instead of doing this all on one page would making 3 pages make more sense?:
> 
> "Install on Unix-Like systems"
> "Install on MacOS" (Links to the Unix-Like systems page or seperate all together)
> "Install on Windows"
> "Install on Docker"
> Another option could be making a UI dialog that allows you to pick your system and we'd only display that Systems installation instructions on the page (Similar to https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/ picking between Intel and Apple Silicon)

2. UI Element (@WillDaSilva 's comment below)

> The UI element you're referring to is provided by the [Tabbed](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/) PyMdown extension, among other implementations. I think they're great for cases like this where most of the instructions will be identical, but certain parts will change based on some consistent setting/environment.

> 
> @afolson I don't believe we're currently using PyMdown, but if we switch from Jekyll to Mkdocs then we probably ought to use it. It has a variety of wonderful features, and the fact that it's all in Python would make it easier for the Meltano community (and devs) to contribute.The UI element you're referring to is provided by the [Tabbed](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/) PyMdown extension, among other implementations. I think they're great for cases like this where most of the instructions will be identical, but certain parts will change based on some consistent setting/environment.
[@afolson](https://github.com/afolson) I don't believe we're currently using PyMdown, but if we switch from Jekyll to Mkdocs then we probably ought to use it. It has a variety of wonderful features, and the fact that it's all in Python would make it easier for the Meltano community (and devs) to contribute.

3. Crazier idea, something like https://labs.play-with-k8s.com/ for Meltano, could use gitpod or some other tool to give folks a fresh environment to play with that's not on their machine allowing us to control the experience. I'm not sure I love this idea but it's an idea. On the backend this uses https://github.com/play-with-docker/play-with-docker

**Comment by tayloramurphy** [comment]
This is in a pretty good state now along with the codespaces demo.  https://docs.meltano.com/guide/installation-guide#local-installation
