### ISSUE TITLE
Ability to configure plugins in Meltano UI in an environment-aware manner.

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6180]
We don't currently have the ability to configure plugins in Meltano UI in an environment-aware manner.

Would be very helpful to add this capability.

## Workaround

As of now, the user would need to configure plugins using the CLI or in yaml.

Related to: https://github.com/meltano/meltano/issues/6179

**Comment by WillDaSilva** [comment]
Closing as no longer relevant on account of the removal of the UI for Meltano 3.0
