### ISSUE TITLE
Consider auto-generating YAML reference docs for `meltano.yml` from JSON Schema

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6182]
Can we create an autogenerated reference documentation for yaml files, populated by the JSON Schema file here?: https://github.com/meltano/meltano/blob/main/schema/meltano.schema.json

This would by a DRY approach to keep IDE validation, IDE auto-completion, and docs all in sync at all times.

**Comment by WillDaSilva** [comment]
Closing in favour of:
- https://github.com/meltano/meltano/issues/7327
