### ISSUE TITLE
Remove/replace Windows 'raise' workaround in after Python 3.7 EOL

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6223]
While making Signals work properly on Windows in https://github.com/meltano/meltano/pull/6208 We hit https://github.com/meltano/meltano/pull/6208/checks?check_run_id=6903745902 

```
        with pytest.raises(SystemExit):
            async with subject.run(session):
>               signal.raise_signal(signal.SIGTERM)
E               AttributeError: module 'signal' has no attribute 'raise_signal'
```

Python 3.7 does not have the `raise_signal` function implemented. When Python 3.7 is deprecated we should update the code to use `raise_signal` instead of the `send_signal()`  function in `tests/meltano/core/job/test_job.py`

Note there's a full walkthrough of this issue and why it happens here https://stackoverflow.com/questions/35772001/how-to-handle-a-signal-sigint-on-a-windows-os-machine , tldr; It's Windows Related

**Comment by tayloramurphy** [comment]
@WillDaSilva added to v3 milestone
