### ISSUE TITLE
End-to-end data platform/pipeline testing in CI/CD

### ISSUE THREAD

**Issue by DouweM** [meltano/meltano#6230]
At a high level, a user with Singer, dbt, and Superset in their project should with minimal effort be able to set up a CI job that will help them detect when an EL config/schema change would break dbt, or when a dbt model change would break a report/query, so that these fixes across tools can be made in the same PR that introduced the breakage before anything makes it into production.

Ideally this wouldn't require actually running the pipeline, and we can accomplish this by generating and comparing the output and input schemas at each stage (e.g. Singer target output database -> dbt input layer -> dbt output layer -> Superset query target). Meltano can have abstractions to define how to generate and compare this for arbitrary plugins.

See also https://github.com/meltano/meltano/issues/3343, which is related but I haven't dug into yet.

See also the proposed `build` command which was written exactly for this purpose:

- https://github.com/meltano/meltano/issues/2975

Edit: if this is easier to implement with a different BI tool than Superset, we should do that. See https://github.com/meltano/meltano/issues/3455#issuecomment-1159037441. I want to show off the promise of end-to-end testing with at least one tool, but realistically a lot of tools aren't there yet.

**Comment by aaronsteers** [comment]
@DouweM - Thanks for logging. I've linked above this issue:

- https://github.com/meltano/meltano/issues/2975

**Comment by tayloramurphy** [comment]
We'll be supporting a more focused version of this around EL workloads via Cloud.
