### ISSUE TITLE
Display glossary words in a tool tip or link to words on the glossary page.

### ISSUE THREAD

**Issue by afolson** [meltano/meltano#6246]
Now that we have a glossary it would be nice to show these definitions in-line so folks don't have to leave the page and come back. Opening a link to the word in a new window is also more disruptive than I'd like but would be a reasonable first iteration.

Ex: Hover over any link on Wikipedia and it will show you a small blurb in a tool tip about whatever that page is https://en.wikipedia.org/wiki/Main_Page. You can also click to get more information. Our glossary has a field for "more info" links but links aren't required for terms.

This may be easiest to do with a Jekyll generator. This would allow us to create a custom tag of sorts that would prevent folks from having to put in-line HTML in our markdown files. Ex `{% term dataops %}` which would create a tooltip and add a link to more info if a link exists.

**Comment by aaronsteers** [comment]
Great idea, @afolson !

**Comment by tayloramurphy** [comment]
Not a priority at the moment.
