### ISSUE TITLE
Update dependencies that libraries.io considers "out of date"

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6264]
[According to Libraries.io we have 15 dependencies that are "out of date"](https://libraries.io/pypi/meltano)

These are:
- [x] `authlib`
- [x] `click`
- [x] `fasteners`
- [x] `flask`
- [x] `flask-executor`
- [x] `gunicorn`
- [x] `ipython`
- [x] `jsonschema`
- [x] `MarkupSafe`
- [x] `pypika`
- [x] `python-dotenv`
- [x] `python-gitlab`
- [x] `sqlparse`
- [x] `watchdog`
- [x] `werkzeug`

Where possible, we should update these dependencies. This may impact 
- https://github.com/meltano/meltano/issues/2830

**Comment by dingobar** [comment]
Watch out, the dependency `click-default-group` requires `click<8`. It also seems like it has been abandoned https://github.com/click-contrib/click-default-group . I suggest we remove this dependency and rather absorb the very small amount of code into Meltano if it's still needed.

**Comment by WillDaSilva** [comment]
> Watch out, the dependency click-default-group requires click<8. It also seems like it has been abandoned

Thank you @dingobar for calling attention to this, and for opening an issue for it. I've assigned the issue to myself, and will address it soon.

In the meantime I've made this PR into a draft.
