### ISSUE TITLE
Meltano elt process does not fail when target_redshift process dies with error

### ISSUE THREAD

**Issue by halilduygulu** [meltano/meltano#6272]
Like in the title, meltano process did not die even though target_redshift python process died with following error. This leaves meltano elt command running forever even there is no reading from tap-postres or any other action happenening according to logs and cpu,memory,network usage. 

I would expect meltano main process to fail with error when target process is no longer working due to a crash. 

error in target-redshift
```
time=2022-06-23 10:45:55 name=target_redshift level=INFO message=Uploading 300000 rows to S3 cmd_type=loader name=target-redshift run_id=840e0304-ba6a-4464-9151-19080f5a114a state_id=prod-to-redshift stdio=stderr                                                                       
time=2022-06-23 10:45:55 name=target_redshift level=INFO message=Target S3 bucket: xxxxx, local file: /tmp/xxxxxxxcustomer_4j231yjz.csv.2, S3 key: xxxxxxxxcustomer_20220623-104456-392678.csv.2 cmd_type=loader name=target-redshift ru 
time=2022-06-23 10:46:11 name=target_redshift level=ERROR message=Failed to load stream xxxxxxcustomer to Redshift cmd_type=loader name=target-redshift run_id=840e0304-ba6a-4464-9151-19080f5a114a state_id=prod-to-redshift stdio=stderr                                        │
Traceback (most recent call last): cmd_type=loader name=target-redshift run_id=840e0304-ba6a-4464-9151-19080f5a114a state_id=prod-to-redshift stdio=stderr
```

elt command I used to start app; 
```
meltano elt tap-postgres target-redshift --state-id prod-to-redshift
```

process list on container via top command, there is no more `target-redshift` running but `meltano` and `tap-postgres` still there as idle
```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0  455592 253728  18336 S   0.0   1.5  31:55.08 meltano
   97 root      20   0  160196 136376  14496 S   0.0   0.8  39:33.90 tap-postgres
  102 root      20   0    5988   3788   3348 S   0.0   0.0   0:00.00 bash
  108 root      20   0    8880   3764   3292 R   0.0   0.0   0:05.21 top
```

my meltano --version is `meltano, version 2.0.1`

**Comment by pandemicsyn** [comment]
@tayloramurphy definitely a bug - probably going to be a bit tricky to track this one down. Unfortunately, not a bug I have a quick "oh I know the fix for this" answer for.  `meltano elt` hasn't had changes in a long time and afaik, we haven't gotten other reports of this, so I'm guessing this bug is transient and comes down to a deadlock/blocking wait that someone will need to run down.

**Comment by edgarrmondragon** [comment]
@tayloramurphy I agree with Florian. Also, I'd try the same EL with `run` since its error handling is likely better.

**Comment by tayloramurphy** [comment]
@halilduygulu thanks for the report! As Edgar mentioned, I do recommend running this with `meltano run` and seeing if the behavior is better. We likely won't get to this bug fix for a bit as `meltano run` is prioritized over `meltano elt`. If you see any more hints at what may be causing the problem, please do share here!

**Comment by halilduygulu** [comment]
thanks for replies, I do not see a `--catalog` parameter for run command. It would be nice if documentation explains main difference between two commands more in details. As a beginner to meltano, elt command looks better to me on docs than run if I want to sync a source to target and do not care about rest of the chaining.

**Comment by tayloramurphy** [comment]
@halilduygulu that's fair! Meltano should handle generation of the catalog though during the `run` command if everything is defined appropriately in the `meltano.yml`. I'll make an issue to better document `elt` vs `run` in a clearer way.

**Comment by tayloramurphy** [comment]
Likely still relevant
