### ISSUE TITLE
How to catch dev dependencies that actually need to be included in the distributed presentations of Meltano?

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6277]
Just got bit by this with `packaging` in https://github.com/meltano/meltano/pull/6276:

It's a transitive dependency required by `tox`, but `tox` is only a dev dependency. So, in CI tests, things look good because dev dependencies are installed by `poetry install`. But, when meltano is installed from an upstream source or by another tool like `pipx`, which is the case in end-to-end tests [here](https://gitlab.com/meltano/legacy-ci/meltano/-/jobs/2632994538#L63) (`pipx install ..`), then the transitive dev dependency `packaging` is not installed and errors are encountered: https://gitlab.com/meltano/legacy-ci/meltano/-/jobs/2632994539#L1237.

```console
$ meltano add orchestrator airflow
2022-06-23T19:10:30.061252Z [info     ] Environment 'dev' is active
No module named 'packaging'
```

I guess one easy way to ensure we don't fall in that scenario is to have tests that don't rely on Poetry to install Meltano.

**Comment by z3z1ma** [comment]
Export the lockfile from from poetry to pin deps in a requirements.txt as part of the release process? 🤔

**Comment by aaronsteers** [comment]
@pandemicsyn and @edgarrmondragon - What do you think of this being a part of 

- #6218?

At least when running in CI, we could use a pipx-installed version of Meltano instead of the Poetry-installed one.

**Comment by pandemicsyn** [comment]
> At least when running in CI, we could use a pipx-installed version of Meltano instead of the Poetry-installed one.

Probably a better discussion for #6218, but sounds fine  - at some point we'd probably want a test mirroring the contributor guide which might end up using poetry.

**Comment by edgarrmondragon** [comment]
The SDK had this exact issue in the `v0.6.0` release so I went ahead and started a PR with `nox-poetry`, which runs tasks against the _installed_ form of the package using the wheel.

https://github.com/meltano/sdk/pull/780
