### ISSUE TITLE
Document how to override plugin settings/capabilities locally

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6283]
https://github.com/meltano/hub/issues/580 is the relevant Hub issue to add some text on the specific plugin pages. 

This capability was added in https://github.com/meltano/meltano/pull/6033/files

Likely on this page we should talk about how capabilities can be defined and overriden. https://docs.meltano.com/guide/configuration

A changelog entry for this feature should be added as it was never documented due to the 2.0 rush.

This can be coupled a bit with https://github.com/meltano/meltano/issues/6107 as well.

**Comment by tayloramurphy** [comment]
@aaronsteers this is the sibling issue for https://github.com/meltano/hub/issues/580 which has already been prioritized. I've added to Iteration 5.

**Comment by edgarrmondragon** [comment]
@tayloramurphy I think now that https://github.com/meltano/meltano/pull/6404 is ready for review, I have some some capacity to document this feature.
