### ISSUE TITLE
Document clearly that `discovery.yml` should not be updated further

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6290]
_Originally posted by @aaronsteers in https://github.com/meltano/hub/issues/621#issuecomment-1164801287_:

> As @edgarrmondragon points out, `discovery.yml` actually deprecated/frozen at this time. The directory @edgarrmondragon  points you at is where this would live in the post-2.0 world. 

We should probably put this guidance in the `discovery.yml` file as a top-of-file comment. ~~And/or remove the file if we don't need it here in the `hub` repo.~~ (Looks like it is only in the `meltano/meltano` repo, which makes sense.

re: https://github.com/meltano/meltano/blob/4deafc883a9b0ffbf2fc87e4a4be28cb20034ce4/src/meltano/core/bundle/discovery.yml

**Comment by tayloramurphy** [comment]
Moved this to the meltano project. This is a nice to have now - we generally don't point people towards discovery.yml and we talk about the Hub as the SSOT. I'm cool with a small update though if someone wants to make that!

**Comment by tayloramurphy** [comment]
Closing as this is scheduled for removal in 3.0.
