### ISSUE TITLE
Uvicorn - Configurations do not update

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6299]
When updating in Uvicorn (on Windows) if I update a configuration for a tap it doesn't update in the meltano.yml file

**Comment by BuzzCutNorman** [comment]
I was wondering if you could supply a little more info about the context in which this occurring.  Was the tap installed via the cli or ui?  Did the tap have an existing configuration you were trying to update or was this the the initial configuration.  If the the tap had a configuration you were trying to edit was the configuration in an environment like dev or prod ?  Could you see the tap configuration values in the ui before you edited them?

**Comment by WillDaSilva** [comment]
Closing as no longer relevant on account of the removal of the UI for Meltano 3.0
