### ISSUE TITLE
Forked Repos don't allow actions to run

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6315]
Check out https://github.com/meltano/meltano/pull/6314

From chatting with @WillDaSilva we found https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks , and https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

It looks like we need to implement the `pull_request_target` event in our github actions. 

What's a bit confusing to me is that I would think I could run the actions on the AutoIDM fork without much issue to Meltano (as I wouldn't have access to any of the secrets from Meltano's repo)

**Comment by visch** [comment]
Maybe caused by https://www.githubstatus.com/  ?

**Comment by WillDaSilva** [comment]
Was caused by the GitHub Actions outage.
