### ISSUE TITLE
`meltano --help` fails on Windows in some environments

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6319]
Running any Meltano command in my fresh Windows VM results in the following error:

![image](https://user-images.githubusercontent.com/11428666/176504379-a9489721-09b5-4a2d-ad83-c2f5a37adfb0.png)

Sorry for the image of text - I forgot to enable the shared clipboard for the VM.

The failure is happening here:

```python
        freedesktop_data = (
            platform.freedesktop_os_release()
            if safe_hasattr(platform, "freedesktop_os_release")
            else defaultdict(type(None))
        )
```

This might be because I'm running under git bash instead of Powershell.

We had assumed that if `freedesktop_os_release` is present, it will work. This is apparently only sometimes true. To prevent problems for Windows users we should put the call to `platform.freedesktop_os_release` in a try-except block. Doing so will also mean we no longer need to call `hasattr`.

**Comment by aaronsteers** [comment]
Thanks for identifying and logging, @WillDaSilva . Would be worth picking up as soon as we have capacity. Thanks!

**Comment by WillDaSilva** [comment]
Okay @aaronsteers, I've moved it into the current iteration, and moved https://github.com/meltano/meltano/issues/6234 into the next one to compensate (not that they'll take nearly the same amount of time, but we'll see what I have time for in the end).
