### ISSUE TITLE
Considering removing product as codeowners for some core files

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6322]
Currently, the @meltano/product group is listed as a CODEOWNER of:

```
# Release Ops (see `/.bumpversion.cfg` for list of bumped files)
/.bumpversion.cfg @meltano/engineering @meltano/product
/CHANGELOG.md @meltano/engineering @meltano/product
/cookiecutter/**/pyproject.toml @meltano/engineering @meltano/product
/docs/package.json @meltano/engineering @meltano/product
/package.json  @meltano/engineering @meltano/product
/pyproject.toml  @meltano/engineering @meltano/product
/src/meltano/__init__.py  @meltano/engineering @meltano/product
/src/webapp/package.json  @meltano/engineering @meltano/product
```

Some of these like package.json, pyproject.toml, etc, could update somewhat frequently due to day to day maintenance tasks - so might be worth reconsidering if Product should really be required to approve changes to these.

**Comment by tayloramurphy** [comment]
Yeah, I'm a fan of not having me be an owner of that! We could add me as an owner on the integration tests though.
