### ISSUE TITLE
Plugin and Environment `env:` keys are not accessible/configurable via the CLI

### ISSUE THREAD

**Issue by kgpayne** [meltano/meltano#6326]
In preparing the docs changes for #6207 I noticed that the `env:` key of an environment is inaccessible via the CLI.

For the top-level `env:` we can use:

```shell
meltano --no-environment config meltano set env '{"MY_NEW_GLOBAL_ENV":"value"}'
```

For the plugin level, we can use the 'plugin extra' syntax `_env` to set values (either at root or in an environment):

```shell
meltano config tap-gitlab set _env '{"MY_NEW_PLUGIN_ENV":"value"}'
```

However there is currently no way to target an environments' `env:` key via the CLI.

**Comment by tayloramurphy** [comment]
Still relevant
