### ISSUE TITLE
Add integration tests to environment variable resolution features

### ISSUE THREAD

**Issue by kgpayne** [meltano/meltano#6364]
As per [this comment](https://github.com/meltano/meltano/pull/6267#discussion_r914120599), it would be good to add integration tests to both demonstrate and validate our env var capabilities.

As per [this response](https://github.com/meltano/meltano/pull/6267#discussion_r914734084), doing so effectively is blocked by:
- https://github.com/meltano/meltano/issues/6326
- https://github.com/meltano/meltano/issues/6363

**Comment by tayloramurphy** [comment]
@aaronsteers @cjohnhanson this seems important to have, particularly considering how challenging feature adds to this part of the codebase have been. Thoughts on getting this prioritized?

**Comment by cjohnhanson** [comment]
@tayloramurphy @kgpayne agreed that this would be great to have but would prioritize #6253 first. I think centralizing our logic for resolving environment variables would both make this testing easier and do a lot to help head off regressions in this behavior.

**Comment by WillDaSilva** [comment]
Still relevant
