### ISSUE TITLE
Automatically fire CLI inflight telemetry events

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6372]
We currently have some of our CLI comments implemented by `async` functions. We could implement them all as `async` functions, and then run them in a wrapper that yields from them, but also fires an inflight telemetry event automatically each time the CLI function yields? This further takes the burden of implementing telemetry away from the dev who is adding/updating a CLI command.

If we're worried about sending too many inflight events, we could limit them in some way, such as only sending one if it has been X seconds since the previous one was sent.

_Originally posted by @WillDaSilva in https://github.com/meltano/meltano/pull/6341#pullrequestreview-1026761814_

**Comment by WillDaSilva** [comment]
@pnadolny13 Would getting more CLI inflight events be valuable to you?

**Comment by WillDaSilva** [comment]
CLI `inflight` events are described in the code as:

```python
    # Optionally, a command may fire a `inflight` event to signal that its execution is in progress. This is useful for
    # commands that are long-running and may take a long time to finish, and allows them to emit an event with collected
    # contexts.
```

Currently we have manually peppered `add`, `config`, `elt`, `install`, and `invoke` with `tracker.track_command_event(CliEvent.inflight)`. Instead of manually doing this, we could have them be fired automatically from every command whenever the command `await`'s something.

**Comment by pnadolny13** [comment]
@WillDaSilva ok that makes sense although I dont think I'm the right person to comment on if thats the right place to do this or not.

I'd say more generally that we should try not to send too many events that are basically duplicates with no new info other than acting as a heartbeat but I do see the value for long running jobs. From a data consumer perspective it would be good to get some info periodically from a long running job, like if its running for several hours then gets killed I might not know that it was running for several hours without these inflight events. I'm not sure how that compares to current state and it sounds like youre more focused on automating it to simplify the development process/code, so I cant really comment on that part.

**Comment by WillDaSilva** [comment]
Closing as stale.
