### ISSUE TITLE
Meltano installation within docker container running airflow

### ISSUE THREAD

**Issue by abhii-singh** [meltano/meltano#6373]
I wanted to check if this has been tried before and if not what approach the community would suggest:

I have airflow running as docker containers and wanted to install meltano inside these containers so that most of my taps and targets would be available.

Any ideas around this ?

**Comment by halilduygulu** [comment]
I am running meltano in docker(k8s) which is triggered via airflow KubernetesPodOperator. I did not want to have 2 airflows, one in meltano, so I manage meltano schedules with my primary airflow.

**Comment by abhi-quinyx** [comment]
@halilduygulu  any tips on how you did this ( meltano in docker ) . I was able to install meltano in the container but end having pip version related issues when installing the taps or targets inside the container .

**Comment by tayloramurphy** [comment]
@abhi-quinyx were you able to sort this out? Meltano installs plugins in their own virtual environments which helps with the dependency mismatch you're experiencing. We've had some users install Meltano with Airflow separately but that's not our recommended path.

**Comment by abhi-quinyx** [comment]
No luck yet @tayloramurphy . Here are the steps I followed : 

1. run airflow (version - 2.1.4) locally through docker 
2. ran a `pip install meltano` 
3. `meltano init` to create a project 
4. `meltano discover extractors` lists various extractors
5. `meltano add extractor tap-salesforce` results in the following error
```
2022-08-08T15:21:14.605023Z [warning  ] The `discovery.yml` manifest received from https://www.meltano.com/discovery.yml has version 20, while this version of Meltano requires version 19.
2022-08-08T15:21:14.606545Z [warning  ] Please install the latest compatible version of Meltano using `meltano upgrade`.
2022-08-08T15:21:14.608044Z [warning  ] Falling back on the cached `discovery.yml` manifest...
Added extractor 'tap-salesforce' to your Meltano project
Variant:	meltano (default)
Repository:	https://gitlab.com/meltano/tap-salesforce
Documentation:	https://hub.meltano.com/extractors/salesforce.html

Installing extractor 'tap-salesforce'...
Extractor 'tap-salesforce' could not be installed: failed to upgrade pip to the latest version.
Will not install to the user site because it will lack sys.path precedence to setuptools in /home/airflow/my_test_project/.meltano/extractors/tap-salesforce/venv/lib/python3.6/site-packages
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Failed to install plugin(s)

```


The error complains about the pip version from the location - `/home/airflow/my_test_project/.meltano/extractors/tap-salesforce/venv/lib/python3.6/site-packages` . The pip version for tap-salesforce is 18.1 while the pip under airflow container is - 21.3.1. 


I think when you say 

> Meltano installs plugins in their own virtual environments which helps with the dependency mismatch you're experiencing

the above error should not occur , correct ?  I wonder what is wrong in the setup if that is the case.

**Comment by tayloramurphy** [comment]
@abhi-quinyx I'm guessing that whatever docker image you're using as a base may just have an old version of pip and/or meltano. I'm not seeing this on a clean install of meltano. @meltano/engineering any ideas?

**Comment by edgarrmondragon** [comment]
@tayloramurphy @abhi-quinyx I see what's going on with the old pip version. Meltano only upgrades its own version of pip (i.e. the one in its `venv`) when the `meltano install --clean` flag is used. I think when running `meltano add` and the automatic subsequent installation, Meltano _should_ also upgrade `pip`.

That's a quick fix, I think.

**Comment by abhi-quinyx** [comment]
@edgarrmondragon  thanks and that's interesting to know . so is it a fix on my end ? or something which will be handled as a bug fix ?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon thanks and that's interesting to know . so is it a fix on my end , if yes how can I proceed ? or something which will be handled as a bug fix ?

@abhi-quinyx Yeah, I wasn't all that clear 😅. I see you're using Python 3.6 which is EOL and hasn't been supported by Meltano for some time. I think if you use a newer Python, it should also come with a newer pip and could fix your issue.

**Comment by abhi-quinyx** [comment]
@edgarrmondragon  gave another try with `python - 3.7.13` now . It now fails at `pip install meltano` 😓  , tries to install `meltano-2.4.0` but complains in the end with 

```
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/airflow/.local/lib/python3.7/site-packages (from requests<3.0.0,>=2.23.0->meltano) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in /home/airflow/.local/lib/python3.7/site-packages (from requests<3.0.0,>=2.23.0->meltano) (2020.12.5)
Collecting ruamel.yaml.clib>=0.2.6
  Using cached ruamel.yaml.clib-0.2.6.tar.gz (180 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      sys.argv ['/tmp/pip-install-9fndr2jc/ruamel-yaml-clib_0a2bf18c0237428cbad0a24e0890d837/setup.py', 'egg_info', '--egg-base', '/tmp/pip-pip-egg-info-rdfq06fs']
      test compiling /tmp/tmp_ruamel_edup5rpk/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_edup5rpk/test_ruamel_yaml.c
      Exception: command 'gcc' failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by abhi-quinyx** [comment]
all right I was able to fix the previous error by adding gcc in my docker image

```
RUN apt-get update
RUN apt-get -y install gcc
```

but now the same `tap-salesforce` fails with the same error. Meltano complains again about pip version issue. 

```
airflow@ce2173db40a9:~/my_test_project$ meltano add extractor tap-salesforce
2022-08-09T08:27:31.018765Z [info     ] Environment 'dev' is active
Added extractor 'tap-salesforce' to your Meltano project
Variant:	meltano (default)
Repository:	https://gitlab.com/meltano/tap-salesforce
Documentation:	https://hub.meltano.com/extractors/tap-salesforce

Installing extractor 'tap-salesforce'...
Extractor 'tap-salesforce' could not be installed: failed to upgrade pip to the latest version.
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/home/airflow/my_test_project/.meltano/extractors/tap-salesforce/venv/bin/python -m pip install --upgrade pip' command.

Failed to install plugin(s)
airflow@ce2173db40a9:~/my_test_project$ /home/airflow/my_test_project/.meltano/extractors/tap-salesforce/venv/bin/python -m pip install --upgrade pip
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/home/airflow/my_test_project/.meltano/extractors/tap-salesforce/venv/bin/python -m pip install --upgrade pip' command.
airflow@ce2173db40a9:~/my_test_project$ python --version
Python 3.7.13
airflow@ce2173db40a9:~/my_test_project$ pip --version
pip 22.2.2 from /home/airflow/.local/lib/python3.7/site-packages/pip (python 3.7)
```

@edgarrmondragon  now I tried with `python3.7` and `meltano-2.40`

**Comment by aaronsteers** [comment]
> ```
> Extractor 'tap-salesforce' could not be installed: failed to upgrade pip to the latest version.
> ```

@abhi-quinyx - Can you try with `--log-level=DEBUG` in case additional info can be found about why pip is not able to be updated?

**Comment by edgarrmondragon** [comment]
@abhi-quinyx I think what would also help is a look at the Dockerfile. It seems that the base (Airflow?) image being used restricts virtualenvs somehow.
