### ISSUE TITLE
Is there a way run meltano tap+targets with multiple cpu cores?

### ISSUE THREAD

**Issue by halilduygulu** [meltano/meltano#6377]
Hi, I am running meltano to copy data from tap-postgres (wise) to target-redshift (also wise) and things are fine but it is slow for big tables. 
While watching the processes that are running via meltano, I see target-redshift is most of the time at %100 of a single cpu core, also when data is being fetched from postgres, tap is also at %100 of a single core. 

I have tested with a better cpu to understand the performance difference, 
```
A table with 19M rows, copying took = 
around 65 minutes, when meltano pod running on aws fargate 4 vcpus
around 28 minutes, with c6i.4xlarge cpus, though it is only using one core per process, but 3.5ghz is performing better.
around 26 minutes, with m5zn.2xlarge 4.5ghz cpus
```

My question is that is there a way to make this process faster. I am using logical replication, so I think I can not split tables into 2 or more seperate tap-postgres configuration, since there is only one wal_log. My problem is there are around 11 tables in db with more than 100M rows, biggest 3 tables about 3 billion rows and I think initial copy for logical replication will take very very long times. 

It would be nice to learn if there is a way to run any of these processes in parallel while keeping meltano elt state intact.

edit: elt command that I use
```
meltano elt tap-postgres target-redshift --state-id postgresdb-to-redshift
```

**Comment by tayloramurphy** [comment]
@halilduygulu apologies for the delay in responding. Currently there is not, but we have https://github.com/meltano/meltano/issues/2677 which is an older issue looking at performance. We do aim to make improvements to EL performance over the coming months though.

**Comment by tayloramurphy** [comment]
@halilduygulu apologies for the delay in responding. Currently there is not, but we have https://github.com/meltano/meltano/issues/2677 which is an older issue looking at performance. We do aim to make improvements to EL performance over the coming months though.
