### ISSUE TITLE
add test for creating .meltano folder on ephemeral deployments on Windows

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6383]
Have a project that doesn't have a .meltano directory due to it being a ephemeral deployment (ie files from the repo are copied every run)

To repeat
1. Create a folder with only a valid meltano.yml
2. Run `meltano install` 
3. See "DB Connection Failed" Error during install due to systemdb not being available
4. Note that to replicate this you cannot have a `.meltano` directory already created. If it's already created the systemdb will be created as expected

To fix I manually copy a .meltano/db file over

I thought we had an issue about this but I couldn't find it :/

**Comment by BuzzCutNorman** [comment]
@visch is this the issue you were thinking of?  [gitlab issue 3390: meltano init not creating DB](https://gitlab.com/meltano/meltano/-/issues/3390)

**Comment by BuzzCutNorman** [comment]
@visch maybe it is this one that was related.  It seems to match this issues description closer.  [gitlab issue 3328: Create .meltano directory when running `meltano install`](https://gitlab.com/meltano/meltano/-/issues/3328)

**Comment by visch** [comment]
@BuzzCutNorman  yes you're right that's it! 

I upgrade Meltano from `2.1.0` to `2.2.0` and now I don't see this :hmm: I"ll have to play a bit as maybe it's something else going on?

**Comment by tayloramurphy** [comment]
@visch I've updated the title - want to take it and add it to your list?

**Comment by visch** [comment]
@tayloramurphy  yes sir!
