### ISSUE TITLE
Enable dependency license scanning in CI

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6393]
This issue tracks the migration of the functionality provided by the GitLab CI job `license_scanning`

**Comment by WillDaSilva** [comment]
As per https://github.com/meltano/meltano/pull/6403#issuecomment-1181281741, we should begin building up a list of permitted licenses (identified by their [SPDX ID](https://spdx.org/licenses/)). @DouweM @tayloramurphy do either of you have any recommendations for what we should accept from our (direct and transitive) dependencies? A simple start would be:

- 0BSD
- BSD-1-Clause 
- MIT
- MIT-0
- Apache-2.0
- ISC

Beyond that we can run the license check to see what we're missing, and add the missing licenses to the list of permitted licenses one by one as we deem them acceptable, and if we do not deem them acceptable, we can remove the dependency that introduced the unacceptable license.

**Comment by tayloramurphy** [comment]
@WillDaSilva https://gitlab.com/meltano/meltano/-/issues/3206 has some additional context when we looked at this previously. I've used https://about.gitlab.com/handbook/engineering/open-source/#acceptable-licenses as prior art and a pretty good starting point for us.

**Comment by kgpayne** [comment]
Related to https://github.com/meltano/gitops/issues/12
