### ISSUE TITLE
feat: Refactor Superset integration as an external Python plugin

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6397]
_This is a specific implementation issue for https://github.com/meltano/meltano/issues/6130_

### Problem to Solve

When adding Superset as part of the 2.0 launch, we had to touch code in multiple places:

* Meltano https://github.com/meltano/meltano/pull/6031/files
* A new repo for files https://github.com/meltano/files-superset
  * (To be clear, this isn't actually used in the current implementation)
* Metadata definition on MeltanoHub https://github.com/meltano/hub/pull/575/files

This is cumbersome and not contributor-friendly. Additionally, it's difficult to iterate on as it's not clear _where_, _how_, or even _what_ users should do to extend functionality - do they add a command? do they add something to Meltano? Should it be in the file bundle?

There's also the challenge of hooking into the capabilities of Meltano. As we expand what users can do with Meltano across multiple plugins, we dramatically increase the number of places we need to make an update when we update a capability or add additional functionality. 

We need to make it easy to add more plugins to Meltano and to iterate on their capabilities without users having to be aware of the internals of Meltano specifically. 

### Prior Art / Things to Keep in Mind

There is a lot of previous discussion on this:

* Original GitLab Epic https://gitlab.com/groups/meltano/-/epics/134#note_981098666
* Main meta-issue https://github.com/meltano/meltano/issues/6130 
* Pat's Hack Day work https://github.com/pnadolny13/superset_glue

The Meltano SDK for Singer generates a lot of community contributions because it allows users to contribute centrally to the SDK and then benefit incrementally for any tap/target they want to make. A key part of this is the `capabilities`of our Singer integration where buckets of functionality are tied to a specific capability https://hub.meltano.com/singer/docs#tap-specific - 

A key distinction between Singer and other plugins so far is the many to one (class of plugins) vs one to one (single package) relationship. The work done for Superset is specific to the plugin Superset whereas for Singer there are hundreds of plugins with their own YAML files that all use the same glue code. How we build a generic Plugin SDK will need to take this into account.

### Definition of Done

For this issue, there are a few items we'd need to see out of a first iteration. 

* All of the Superset-specific code is in its own package. We'll worry about the monorepo question separately
* This is built with the the skeleton of a true Meltano SDK in mind - bonus if the skeleton is started. This should also be built with Airflow and other generic plugins in mind.
  * https://github.com/meltano/meltano/issues/6398 is an issue specifically for Airflow that is out of scope for this issue, but should be held in the back of the engineers mind when developing.
* User functionality with Superset is basically the same but there will likely be new generic capabilities either used or at least proposed
* Docs are updated in Meltano and the Hub on how the Superset integration is used and changed 
* Hub updated to use new integration

**Comment by DouweM** [comment]
@tayloramurphy What do you think about making this about Superset _and_ Airflow, so that we don't code things too specific to what Superset needs, and forget about more complicated plugins?

**Comment by tayloramurphy** [comment]
https://github.com/meltano/hub/pull/968 is merged! Closing as completed.
