### ISSUE TITLE
bug: Document Meltano 2.2.0 requires SQLite >= 3.25.1

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6405]
As kindly reported by @pdebelak in https://github.com/meltano/meltano/pull/6323#issuecomment-1181955922, the `ALTER TABLE table RENAME COLUMN oldname TO newname` syntax was introduced to SQLite only in version [`3.25.1`](https://sqlite.org/releaselog/3_25_1.html), and so systems with a default version older than that may fail to run the migration and use Meltano.

**Comment by pandemicsyn** [comment]
Might be worth taking a quick survey and checking with what version the common distro's have support for sqlite +3.25.1, so we can build up a recommended distro list. It's supported in Ubuntu LTS 20.04 and up, but looks like Amazon Linux 2 might ship an older version.

**Comment by pandemicsyn** [comment]
Confirmed with a user as well that Amazon Linux 2 is impacted: https://meltano.slack.com/archives/C01TCRBBJD7/p1660078023662099?thread_ts=1660067260.492999&cid=C01TCRBBJD7

**Comment by kastman** [comment]
On amazon linux 2 with meltano==2.5.0, we found that even compiling from source into `/usr/local/bin` and removing the sqlite3 shipped in `/usr/bin` continued failing; not sure if there was something weird about compilation of sqlalchemy or pysqlite from the available headers? Our solution was installing sqlite through conda and using a conda environment.

**Comment by aroder** [comment]
On amazon linux EC2 instance with meltano 2.6.0, I installed `pip install pysqlite3` and get version 3.7.* from `sqlite3 --version`

I followed these instructions to upgrade sqlite version https://developpaper.com/update-sqlite-version-under-centos/

So this confirms everyone else's findings and hopefully sheds a little light on a path forward

**Comment by chstout** [comment]
One thing we noticed is that this is a requirement to install, even if you are using an external (postgres) database for your config db.

**Comment by qbatten** [comment]
A better error message or pre-run check for correct sqlite version would be really helpful. The error message is just a sqlite3.OperationalError with no further context as to why it's happening, etc. I think it could be worth improving handling of this issue specifically bc I suspect that a lot of people are / will be running into this. Repro is basically like... launch an EC2 instance, install Meltano, and try to run it, which I imagine is a workflow that a lot of people use when they're checking out Meltano for the first time.

Also going to drop a larger chunk of the error message in here just to help people find this issue via search:

```
(sqlite3.OperationalError) near "job_id": syntax error
[SQL: ALTER TABLE job RENAME job_id TO job_name]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "job_id": syntax error

...

  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "job_id": syntax error
[SQL: ALTER TABLE job RENAME job_id TO job_name]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Cannot upgrade the system database. It might be corrupted or was created before database migrations where introduced (v0.34.0)
```

**Comment by edgarrmondragon** [comment]
> A better error message or pre-run check for correct sqlite version would be really helpful

This seems like a quick solution by leveraging `sqlalchemy.engine.Dialect.server_version_info`. We could check the version tuple and fail with a clear message for SQLite<3.25.1. cc @aaronsteers @tayloramurphy 

I still think that we Meltano should be shipped with the version of SQLite it expects to work out of the box. Perhaps adding a dependency on https://pypi.org/project/pysqlite3-binary might be worth exploring, although it's lacking [wheels](https://pypi.org/project/pysqlite3-binary/#files) for macOS and Windows at the moment.

**Comment by cwegener** [comment]
> Confirmed with a user as well that Amazon Linux 2 is impacted: https://meltano.slack.com/archives/C01TCRBBJD7/p1660078023662099?thread_ts=1660067260.492999&cid=C01TCRBBJD7

FWIW. Amazon Linux 2022 (which is still in preview) has Python 3.9 and Sqlite 3.34

**Comment by aaronsteers** [comment]
Should we internally disallow `RENAME COLUMN` operations in our contributing guide and for internal operations?

Perhaps even a CI test that searches the alembic migrations folder and throws an error if column renames are proposed?

I do also really like the idea from @edgarrmondragon of shipping with a binary version of SQLite that ensures the minimum capabilities, but the missing MacOS wheels may be a blocker there. 

I don't recall this ever occurring in the past, and I didn't even realize there was a version of SQLite that didn't support column renames. Additionally, Meltano is overall moving in a direction to support non-RDBMS backends for logs, secrets, and settings - so the RDBMS should have an overall decreasing role in the month/years to come. Is it feasible that we can lock down existing tables and disallow renames for at leas the foreseeable future - at least until we are confident that all supported versions of Python have SQLite backends which support column rename?

Another option - with similar results - would be to add a CI test where we force a <2.2.0 version of SQLite - but to be useful, we would need to be sure that this CI test also runs the database migrations and not just from-scratch executions.
