### ISSUE TITLE
docs: Build example Meltano project using `meltano-map-transform` with examples for common uses

### ISSUE THREAD

**Issue by DouweM** [meltano/meltano#6412]
<details>
<summary>Original description</summary>

The README for https://github.com/MeltanoLabs/meltano-map-transform lacks usage instructions, https://docs.meltano.com/concepts/plugins#mappers has an example of `pipelinewise-transform-field` but not `meltano-map-transform`, and I happen to know that some of the docs on https://sdk.meltano.com/en/latest/stream_maps.html apply to `meltano-map-transform` as well, but a user wouldn't know that. 

Since mapping in between extracting and loading is a form of transformation, I think we should document this functionality on https://docs.meltano.com/guide/transformation, and reference it from https://docs.meltano.com/guide/integration as well, as a new user wouldn't know to find the relevant docs in https://docs.meltano.com/concepts/plugins#mappers. I also think it's worth listing the mappers supported out of the box on https://hub.meltano.com/. 

</details>

Proposal (from @aaronsteers):

1. Create a new entry in the `example-projects` repo with a set of example map transforms (hopefully covering all/most of what @sbalnojan outlines [here](https://github.com/meltano/meltano/issues/6412#issuecomment-1277145178)).
2. Link to the new usage examples in:
   - the `meltano-map-transform` readme
   - the related SDK docs page
   - on docs.meltano.com

**Comment by DouweM** [comment]
@tayloramurphy I think this is more important to prioritize than https://github.com/meltano/sdk/issues/801, as users can already get a long way with our existing mapper, without needing to write a custom one.

**Comment by tayloramurphy** [comment]
>  I also think it's worth listing the mappers supported out of the box on https://hub.meltano.com/.

We have https://github.com/meltano/hub/issues/589 which tracks that.

> Since mapping in between extracting and loading is a form of transformation, I think we should document this functionality on https://docs.meltano.com/guide/transformation, and reference it from https://docs.meltano.com/guide/integration as well, as a new user wouldn't know to find the relevant docs in https://docs.meltano.com/concepts/plugins#mappers.

I think that makes sense. Having a short interstitial on the integration guide is good just to get people thinking about it, but then the transformation page can be structured to have "in-flight" and "in-warehouse" transformations.  

I think it makes sense to prioritize as well @DouweM

**Comment by sbalnojan** [comment]
FWIW, I just spent a day wrestling with the meltano-map-transformer, so I would love to get some docs here. At least an extended README with a few sample meltano ymls would be great start and shouldn't take long for someone who knows this stuff.

**Comment by sbalnojan** [comment]
I saw https://github.com/MeltanoLabs/meltano-map-transform already got an update making it way easier to understand. I personally think for now, having a good README will do the job. Some things I would love see are:

1. Minimum of three examples of the configuration
2. Examples of configuration should include the data going in and out (One row, before & after).
3. Examples should vary in complexity AND try to hit the special cases... So
4. One example using just the built in functions
5. One example using "record.get"
6. One example using additional Python functions (like any short lambda function). 
7. I like the one that's already there referencing the "config"!
8. The README should mention an easy way to test my mapping (like using cat and or stdout,...).

@tayloramurphy

**Comment by tayloramurphy** [comment]
@sbalnojan thank you for updating with the context. @aaronsteers is that enough guidance to be able to assign to an engineer?

**Comment by aaronsteers** [comment]
@tayloramurphy - Yeah, definitely. 👍 

I've updated the description to reflect this scope.

**Comment by aaronsteers** [comment]
> * Minimum of three examples of the configuration
> * Examples of configuration should include the data going in and out (One row, before & after).
> * Example data should vary (a flat stream, maybe one with nested things,...)
> * Examples should vary in complexity AND try to hit the special cases... So
> * One example using just the built in functions
> * One example using "record.get"
> * One example using additional Python functions (like any short lambda function).
> * One of the examples should also use the type casting...
> * I like the one that's already there referencing the "config"!
> * The README should mention an easy way to test my mapping (like using cat and or stdout,...).

There are a ton of items here, but the pattern we're most often referencing is a simple MD5 hash. Understanding that this is a ton of work, and engineering time is sparse. 

Can we get by with using this in demos/tutorials if MD5/SHA hash examples are in place? 

That one seems pretty simple and I'd like to unblock usage in tutorials/demos asap.

**Comment by sbalnojan** [comment]
@aaronsteers I don't think so, but I can start bugging some engineers with a couple of specific questions. I assume that would be way faster, I don't really need an engineer to write the examples, etc.

The reason is, that md5 as a built-in function is already well documented. The list of problems I had above is literally the problems I wasn't able to fix to use this flexibly inside the getting started tutorial. (nested streams, type casting, custom python functions, record.get). 

So let me bug a few people and see how far I come ;)

**Comment by sbalnojan** [comment]
@aaronsteers I think I can work around most issues and prepare a few examples myself. 

However, I am either using the stream maps wrong or would like to include some small features as well (https://github.com/meltano/sdk/issues/1500). The one was the "killer" for inclusion in the current doc tutorial.

**Comment by sbalnojan** [comment]
Got a PR open adding 6 examples to the repository. https://github.com/MeltanoLabs/meltano-map-transform/pull/117


Possible follow-ups (not inside this issue):
- Share it on social...
- A blog post about it!
