### ISSUE TITLE
chore: Remove GitLab links in Meltano codebase

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6421]
There are old gitlab links in Meltano https://github.com/meltano/meltano/search?p=2&q=gitlab.com

Thought about this when fixing https://github.com/meltano/meltano/pull/6420

**Comment by tayloramurphy** [comment]
@aaronsteers adding this small issue to the next iteration.

**Comment by aaronsteers** [comment]
@tayloramurphy - Many of these look okay. Some are links to historical issues and some appear to be fabricated urls. I think a few can be cleaned up but I'm not sure exactly which need to be updated.

**Comment by tayloramurphy** [comment]
Thanks for looking through. Most seem okay and the ones in test we'll catch if we update some of those properties. We can close.
