### ISSUE TITLE
Code Coverage reports should report tests as having coverage

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6426]
- I only updated the tests in https://github.com/meltano/meltano/pull/6407#issuecomment-1184910358 , test coverage being impacted on files outside of the `tests/` folder makes sense, but me impacting `tests/*` doesn't make any sense to me.

Code Coverage probably shouldn't look at the `tests` directory? But it's almost like all other files should be checked for their total coverage as I could botch a `fixture` or something and reduce coverage in unexpected ways. Maybe this is already being checked?

**Comment by WillDaSilva** [comment]
For what it's worth, I recently found & removed some dead code from the tests because it was reported as uncovered. Using coverage stats to help ensure that we run all of the test code that we've got may be beneficial.

**Comment by visch** [comment]
> For what it's worth, I recently found & removed some dead code from the tests because it was reported as uncovered. Using coverage stats to help ensure that we run all of the test code that we've got may be beneficial.

Extra information seems ok (maybe as it can overwelm me but I understand folks who are in the code base all the time wanting it, as I am at the moment), but the failure here https://github.com/meltano/meltano/pull/6407/checks?check_run_id=7325652363 doesn't to me

**Comment by visch** [comment]
Thank you!
