### ISSUE TITLE
Document CLI design guidelines

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6440]
Similar to https://docs.meltano.com/contribute/api#api-v2-design-guidelines we should have clearly defined guidelines for creating/updating the meltano `cli`.  How to structure, organize, and even name new CLI additions is a **frequent** source of contention and a stumbling block during iterations and builds.

I think it's worth calling out that it's OK that our CLI's inconsistent right now, and not all `meltano commands` will follow this style guide immediately. However, I think we need a guide in place (even if it's an aspirational one) moving forward so that we can start aiming for a consistent CLI experience for users, and to have a consistent UX style guide in place during feature planning.

This doc should cover:

- Desired verb/command linkage and structure 
- Expected common sub-command's and options
- Expected common output formats
- Use of short and long flags
- Abbreviations
- Global vs argument level flags
- Reusing short flags
- Flag aliases
- Consistent definition of Groups, Commands, Sub-commands, Arguments, and Options
- Expected help and usage
- Doc style guidelines for how to style examples and usage of:
  - Optional arguments/options/flags
  - Required items 
  - Mutually exclusive args
  - Arguments that can repeat
- What belongs the cli module (i.e.`meltano/cli/the_command.py`) and what belongs in meltano.core. 
- Phrasing guidelines for command Deprecation and Preview/Beta commands.

**Comment by aaronsteers** [comment]
@pandemicsyn - I'm in strong favor of this as a high pri item. We've lost a bunch of cycles from _not_ having this and I think we should try to get to this asap.

**Comment by pandemicsyn** [comment]
> @tayloramurphy I was thinking sending along a PR and then letting y'all edit/bikeshed it during the review might be easiest. Since it would let folks thread on the actual things in question.

Quick edit to follow up on that, i'd probably use `schedule` and `jobs` since I'd hope those additions (and refactor in the case of `schedule`) would be good jump of points , at least for the general structure/layout - since we did those relatively recently.

**Comment by pandemicsyn** [comment]
@tayloramurphy @aaronsteers I've got a 1st draft over on https://github.com/meltano/meltano/pull/6539 if y'all want 👀 . Have one section flagged on the PR for you both of y'all and one additional section flagged for @tayloramurphy.
