### ISSUE TITLE
bug: Meltano Upgrade on Windows stops with error "is not a valid Win32 application"

### ISSUE THREAD

**Issue by BuzzCutNorman** [meltano/meltano#6467]
### Meltano Version

2.3.0

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Windows Server 2022 Standard

### Description

I have noticed on Windows if the file(symbolic link) `.meltano/run/bin` is present in your project when you run the upgrade via `meltano upgrade` or the `melatno ui` "Upgrade Button" you will get the following `WinError`.

`[WinError 193] %1 is not a valid Win32 application`

if you remove the file and run `meltano upgrade` the upgrade will complete. I am not sure what the long term ramification of deleting the file is.

![image](https://user-images.githubusercontent.com/55715401/180505118-6370a8ad-5a37-4dab-9216-aa539b1a3eae.png)

**Comment by BuzzCutNorman** [comment]
I found running `meltano install`  will create a `.meltano/run/bin' in my test projects.

**Comment by tayloramurphy** [comment]
@visch do you have any insights on this one? FYI @aaronsteers if there's someone on the team that can have a look as well.

**Comment by visch** [comment]
@tayloramurphy from a quick look the PR looks ok, I need to dive in to see if there's something else we can do on the Windows side. My gut is that pip helps us out a bit more than this, but I could be wrong!

Thanks for the PR @BuzzCutNorman

**Comment by BuzzCutNorman** [comment]
I figured out why it seemed random to me.  If I use Meltano from a venv or pipx installation to initialize a project using `meltano init test-stuff` a `.\.meltano\run\bin` file is not created. If I start a `poetry shell` from my `meltano` local fork clone and I run `meltano init test-stuff` a `.\.meltano\run\bin' file is created.  The same thing happens if I run `meltano install` in a existing project when I am in a `poetry shell`.

1. cd meltano (local fork clone)
2. `poetry shell`
3.  `cd ..`
4. `meltano init test-stuff`
5. `cd test-stuff`
6. `dir .meltano\run` you should see a `bin` file
7. `exit` this should take out of the poetry shell and back to meltano (local fork clone) directory
8. `cd ..`
9. `cd test-stuff`
10. `meltano upgrade`

These steps work to recreate the issue every time.

**Comment by BuzzCutNorman** [comment]
@visch , @tayloramurphy , @aaronsteers ,  I was wondering does Windows even need a `.mletano/run/bin` file?  Currently one is not created and everyone is running on pretty well.  I made the assumption I was missing something vital but maybe running `meltano init` and `meltano install` via `poetry shell` was adding something Windows users do not need.

**Comment by visch** [comment]
> @visch , @tayloramurphy , @aaronsteers , I was wondering does Windows even need a `.\.meltano\run\bin` file? Currently one is not created and everyone is running on pretty well. I made the assumption I was missing something vital but maybe running `meltano init` and `meltano install` via `poetry shell` was adding something Windows users do not need. I guess I am also curious as to what purpose the `.\.meltano\run\bin` symbolic link serves.

Yeah I don't know why it exists at all, I'd imagine there's a reason I just don't know it right now will have to dig :D

**Comment by BuzzCutNorman** [comment]
I think I found it.  Here is the link to the  GitLab issue connected to the current `Project.activate()`

[`meltano init` fails when underlying filesystem doesn't support symlinks](https://gitlab.com/meltano/meltano/-/issues/2373)

The symlink is for the AirFlow DAG Generator.  This needs to be in place or the AirFlow orchestrator plugin will fail when you invoke a schedule.

**Comment by tayloramurphy** [comment]
@BuzzCutNorman I'm not sure. @pandemicsyn @edgarrmondragon @aaronsteers would likely be best to answer

**Comment by BuzzCutNorman** [comment]
If you want to see what the symbolic link .\.meltano\run\bin is targeting in Windows run this from a powershell prompt while in a Meltano project folder.

dir .\.meltano\run\ -recurse -force | ?{$_.LinkType} | select FullName,LinkType,Target

I think you can do this other ways but I found this one at it has worked well for me.

**Comment by BuzzCutNorman** [comment]
I just ran across another area that utilizes the `.\.meltano\run\bin` file.  The `Run Now` button in Pipeline tab of the  `meltano ui` utilizes it as well.  I should say the API path of `/api/v1/orchestrations/run` that the button POST to does.  In the very end `MeltanoInvoker.invoke()` is called by `ScheduleService.run()`.  Since it is not passed a command the default command `meltano` is used.  If the `.\.meltano\run\bin` is present it passes the `elt` arguments to the symlink .

I think any time a sub process is started via `MeltanoInvoker.invoke()` to complete a `meltano` command it will try to utilize a `.\.meltano\run\bin` file if present in the project.

**Comment by pandemicsyn** [comment]
> I guess the other questions I have is. Will the `.meltano/run/bin` symlink be needed once @pandemicsyn finishes the new plugin architecture that he is refactoring AirFlow to use.

> I think any time a sub process is started via MeltanoInvoker.invoke() to complete a meltano command it will try to utilize a .\.meltano\run\bin file if present in the project.

Yep, afaik - thats my understanding as well. There's a few spots where things need to be able to call `meltano` itself, and in the new plugin architecture that's still present...and I think its expected that plugins will need to call `meltano` occasionally.

**Comment by BuzzCutNorman** [comment]
Thanks, for the clarification.  Sounds like I should move forward with making sure a the symlink `.\.meltano\run\bin` is present.

**Comment by BuzzCutNorman** [comment]
Two clarifying questions:

1. You don't need `./.meltano/run/bin` explicitly just the ability for `MeltanoInvoker.invoke()` to call `meltano`?
2. In a simple single shared production server scenario (multiple people logging in and running `meltano` commands against a single project).  Is `meltano` suggested to be installed globally or per user?

**Comment by pandemicsyn** [comment]
1. Not just `MeltanoInvoke.invoke()`, I assume `.\.meltano\run\bin` is present so plugins themselves's have access to the meltano cli. e.g. in the future a plugin my need to use `meltano state` or something. 
2. Not sure as if its really "globally installed" as much as "globally to some pyenv/venv/python". To be honest though, not sure how this plays with pipx or container invoked plugins.

**Comment by BuzzCutNorman** [comment]
Looking at the airflow-files meltano.py it checks for the presence of the `.\.meltano\run\bin` file and then has a fallback of `meltano` being present in the PATH. 
```
if not Path(PROJECT_ROOT).joinpath(MELTANO_BIN).exists():
    logger.warning(
        f"A symlink to the 'meltano' executable could not be found at '{MELTANO_BIN}'. Falling back on expecting it "
        f"to be in the PATH instead. "
    )
    MELTANO_BIN = "meltano"
```    
Would this be the pattern for all plugins?

**Comment by pandemicsyn** [comment]
> Would this be the pattern for all plugins calling meltano ?

I think thats TBD - im not sure that theres any other plugins out there (yet) that call back into meltano other than airflow and perhaps the WIP dagster plugin.

**Comment by aaronsteers** [comment]
> > Would this be the pattern for all plugins calling meltano ?
> 
> I think thats TBD - im not sure that theres any other plugins out there (yet) that call back into meltano other than airflow and perhaps the WIP dagster plugin.

Admittedly I'm not very familiar for the context of why symlinks are created here and if there are other use cases where this is needed. However, it seems some of the context was from the days when Meltano was expecting users to manually create a virtualenv for Meltano, which may or may not be 'activated' at the time of invoking other processes. If Meltano is installed with `pipx`, as we currently recommend, then the `meltano` shim should already be on the `PATH` and I don't know if we still need the symlinks.

I don't want to block a valid fix but I've opened a related item here for longer-term discussion on this topic:

- https://github.com/meltano/meltano/issues/6910
