### ISSUE TITLE
[Bug]: Windows fails silently on Configure Poetry step

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6479]
### Meltano Version

NA

### Python Version

NA

### Bug scope

Other

### Operating System

Windows

### Description

Our tests in CI are running only for Pytho 3.9 on Windows even though our matrix suggests we test on 3.7-3.10. I started https://github.com/meltano/meltano/pull/6478 to validate this and confirmed it after seeing the following debug info in all Python versions on Windows:

```
Poetry
Version: 1.1.14
Python:  3.9.13

Virtualenv
Python:         3.9.13
Implementation: CPython
Path:           C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\meltano-YRQtpV-c-py3.9
Valid:          True

System
Platform: win32
OS:       nt
Python:   C:\hostedtoolcache\windows\Python\3.9.13\x64
Installing dependencies from lock file
```

That means we're not really testing Meltano on Windows for Python 3.7, 3.8 and 3.10. I suspected this while working on https://github.com/meltano/meltano/pull/6395 since that required some refactoring to how Poetry is installed and used, and saw Windows tests passing on Python 3.8 and 3.9, but failing on 3.7 and 3.10.

**Comment by visch** [comment]
Hmm it's almost like we may need to add some tests to CI :O 

https://github.com/meltano/meltano/runs/7509637290?check_suite_focus=true Looks to fail on the `Install Dependencies` task but the job continues to run properly

That looks to be the issue. 

I use https://github.com/AutoIDM/tap-clickup/blob/main/.github/workflows/ci.yml for a different job and this one works fine!

**Comment by edgarrmondragon** [comment]
@visch you might wanna take a look at https://github.com/meltano/meltano/pull/6395#issuecomment-1195057216

**Comment by visch** [comment]
Going to focus first on why the https://github.com/meltano/meltano/runs/7509637290?check_suite_focus=true "Install Dependencies" task isn't reporting a failure to github actions. This is strange to me running the command locally seems to fail so something is up, and we need to be able to trust that a failed proc (non 0 exit code) is going to report to github actions it's a failure.

```
PS E:\code\meltano> poetry env use "3.7"
'python3.7' is not recognized as an internal or external command,
operable program or batch file.

  EnvCommandError

  Command python3.7 -c "import sys; print('.'.join([str(s) for s in sys.version_info[:3]]))" errored with the following return code 1, and output:


  at ~\.poetry\lib\poetry\utils\env.py:346 in activate
       342│                     shell=True,
       343│                 )
       344│             )
       345│         except CalledProcessError as e:
    →  346│             raise EnvCommandError(e)
       347│
       348│         python_version = Version.parse(python_version.strip())
       349│         minor = "{}.{}".format(python_version.major, python_version.minor)
       350│         patch = python_version.text
PS E:\code\meltano>  $LASTEXITCODE
1
```


Based on @edgarrmondragon 's comments on the other issue 3.7 and 3.10 are borked. I'm sure once I fix this it'll confirm that then I'll smoke test that on my machine and if meltano doesnt' work at all we should update the docs.

**Comment by visch** [comment]
> Why is Install Dependencies not failing
Attempted to replicate here https://github.com/visch/gh_actions_windows_poetry_test/runs/7602621751?check_suite_focus=true , this one fails fine :O , so diving more but the strangeness is concerning I'm sure I'll find it

**Comment by visch** [comment]
https://github.com/meltano/meltano/pull/6541/checks 

Shows why Windows actions were succeeding even though so commands were failing along the way. Because the actual fix to the correct python version seems "simple" (famous last words) I'll try it right now and see if I can't get that done. Thought I'd split out the issue as I could see this being a bit controversial!

**Comment by edgarrmondragon** [comment]
> Going to focus first on why the https://github.com/meltano/meltano/runs/7509637290?check_suite_focus=true "Install Dependencies" task isn't reporting a failure to github actions.

@visch that's an intriguing issue with GitHub actions in general, but may not be too relevant anymore at least for our Windows case, since #6395 got merged. I'd be in favor of changing the title of this issue to reference the actual Windows failures, or closing it and create new and separate issues for the failures on Python 3.7 and 3.10. The former I think is the trickier one since it seems to relate to `asyncio`.

**Comment by visch** [comment]
> > Going to focus first on why the https://github.com/meltano/meltano/runs/7509637290?check_suite_focus=true "Install Dependencies" task isn't reporting a failure to github actions.
> 
> @visch that's an intriguing issue with GitHub actions in general, but may not be too relevant anymore at least for our Windows case, since #6395 got merged. I'd be in favor of changing the title of this issue to reference the actual Windows failures, or closing it and create new and separate issues for the failures on Python 3.7 and 3.10. The former I think is the trickier one since it seems to relate to `asyncio`.

Responded here https://github.com/meltano/meltano/pull/6542/files#r935018790 , maybe we could update this issue name to be `[Bug]: Windows fails silently on Configure Poetry step`

**Comment by visch** [comment]
This one should probably stay open, there's probably a fix out there for windows we could find. This just leaves us open for some nasty Windows bugs to sneak in as github actions could miss them

**Comment by visch** [comment]
https://github.com/meltano/meltano/issues/6540#issuecomment-1523993556 solves the long term issue here, we could close this one and leave 6540 open
