### ISSUE TITLE
feature: Add support for `NO_COLOR` env var

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6482]
Latest spec:

- [ ] Parse a `NO_COLOR` env var per instructions at https://no-color.org
- [ ] Optionally, also accept `--no-color` at the CLI.
- [ ] Pass this setting to logging configs.
- [ ] Pass this setting to `click`.
- [ ] Disable or remove color from `rich` exception logging, as needed.

Notes:

- This is not to be a feature flag or a Meltano setting, and therefor will not be able to be set using `meltano config`.
- This should have the equivalent affect as customizing `logging.yaml`. (Bug fixes in `color=false` implementation should solve for both methods of setting.)

**Comment by DouweM** [comment]
@aaronsteers I'm pretty sure we can have code detect whether the output device is color-capable! `istty` would be the first step.

**Comment by aaronsteers** [comment]
@DouweM - Yes, but there seem to be cases where the terminal itself supports color but the recorded log outputs will not. Perhaps a tri-value (`true`/`false`/`auto`) would make sense here, where we default to auto but users can still control/override this as needed.

**Comment by aaronsteers** [comment]
Also, in particular, `istty` just tells us if the terminal is interactive, right? I believe a non-interactive `docker run` may still support color but not be considered a tty. (I could be wrong though; would be good to confirm.)

**Comment by edgarrmondragon** [comment]
I agree with @aaronsteers, and there are cases where color is desired even though the terminal isn't interactive, like GitHub CI.

A number of tools, like `pytest` and `nox`, already use an informal convention of environment variables `FORCE_COLOR` and `NO_COLOR`, or CLI flags alternatively. Pytest additionally offers a `PY_COLORS` that overrides the other two options, and `rich` supports `NO_COLOR`.

Nox docs: https://docs.pytest.org/en/7.1.x/reference/reference.html#envvar-PY_COLORS
Pytest docs: https://nox.thea.codes/en/stable/usage.html#controlling-color-output
Rich docs: https://rich.readthedocs.io/en/latest/console.html#environment-variables
`NO_COLOR` convention: https://no-color.org/

**Comment by aaronsteers** [comment]
@edgarrmondragon - I didn't know about no-color.org. Fascinating.

----

> # NO_COLOR
>
> _Last updated: 2022-07-22_
>
> An increasing number of command-line software programs output text with [ANSI color](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) escape codes by default. While some developers and users obviously prefer seeing these colors, some users don’t. Unfortunately, every new piece of software seems to have a different way of disabling colored text output and some software has no way at all.
> 
> Accepting the futility of trying to reverse this trend, an informal standard is hereby proposed:
> 
> Command-line software which adds ANSI color to its output by default should check for a NO_COLOR environment variable that, when present and not an empty string (regardless of its value), prevents the addition of ANSI color.
> 
> By adopting this standard, users that prefer to have plain, non-colored text output can set one environment variable in their shell to have it automatically affect all supported software.
> 
> To add to this list of supported software, [clone this site’s Git repository](https://github.com/jcs/no_color) and submit a pull request.
>

**Comment by pandemicsyn** [comment]
> A user in [Slack](https://meltano.slack.com/archives/C01TCRBBJD7/p1661961091406679) was asking about disabling color easily.

To be even more explicit, that user already disabled color in his logs, but I think is still getting colored output from Meltano's because of our use click.echo where we colorize the output.

**Comment by pandemicsyn** [comment]
Sorta related: https://github.com/meltano/meltano/issues/6152 (convo in there also about using istty)
And https://github.com/meltano/meltano/issues/6122 (using rich for pretty printing exceptions). I think rich does support NO_COLOR out of the box.  Figured I'd mention it since it does add yet another output handler/formatter and it sounds like pretty printing exceptions might end up being our default 😬

**Comment by aaronsteers** [comment]
As @pandemicsyn mentioned today in a chat:

- [ ] Precedence and config methods, the ways of settings are:
  - [ ] CLI flag (`--no-color`)
  - [ ] Environment vars (such as `NO_COLOR`)
  - [ ] Default/hidden log config (derived dynamically, will get from the above)
  - [ ] Log config (currently highest pri, last applied and overrides above)

- [ ] We still have work to do on no-color compliance:
  - [x] `structlog` (already using no-color preference)
  - [ ] `Click` and our pre-formatted/explicitly-colored print statements that go through Click
  - [ ] (Anything else?)

**Comment by aaronsteers** [comment]
- [ ] From this thread in Slack, we should also try to ensure grayscale codes do not slip through:

https://meltano.slack.com/archives/C01TCRBBJD7/p1662065425046529?thread_ts=1661961091.406679&cid=C01TCRBBJD7
