### ISSUE TITLE
Transition flask-security to a maintained package

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6490]
In https://github.com/meltano/meltano/pull/6474 I (we?) noticed that we use our own flask security fork:  https://github.com/meltano/flask-security. That's forked from https://github.com/mattupstate/flask-security which appears abandoned and unmaintained. 

We should see if we can transition to https://github.com/Flask-Middleware/flask-security/ if it's compatible.

**Comment by edgarrmondragon** [comment]
Looking at the commit history in our fork, it seems like we only forked just so we could have a PyPI release with something that was sitting in `master` of the original 😅

**Comment by WillDaSilva** [comment]
Closing as no longer relevant on account of the removal of the UI and API for Meltano 3.0, which will remove this dependency.
