### ISSUE TITLE
MyPy is not being run in CI

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6491]
The style guide in the contributor docs says:

> MyPy is currently only executed as part of the build pipeline in order to avoid overwhelming developers with the complete list of violations. This allows for incremental and iterative improvement without requiring a concerted effort to fix all errors at once.

We are not currently running MyPy at all. We should immediately update the contributor doc to reflect that. Later we should update our GitHub CI to run MyPy, and work towards getting MyPy passing.

**Comment by edgarrmondragon** [comment]
Approach suggested to @aaronsteers in chat:

> We could introduce it incrementally by adding the CI check and excluding all the subpackages, then enabling one at a time and fix any errors there alone.

That way new modules will be have to be compliant, while we work towards 100% adoption on the existing ones.

**Comment by aaronsteers** [comment]
@edgarrmondragon - I like this approach because it lets us move forward sooner than later. Could you provide a rough `weight` for the proposed first pass?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon - I like this approach because it lets us move forward sooner than later. Could you provide a rough `weight` for the proposed first pass?

@aaronsteers I've add a weight of `4`: set up the CI job, add the initial whitelist and configure mypy for our needs.

**Comment by aaronsteers** [comment]
Great, thanks @edgarrmondragon !

**Comment by edgarrmondragon** [comment]
Burndown:

- https://github.com/meltano/meltano/pull/6708
