### ISSUE TITLE
Upgrade to `pytest-docker` v1

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6496]
https://pypi.org/project/pytest-docker/

`pytest-docker==1.0.0` was released earlier today, and it includes support for Docker compose v2, which is not a Python package. We'll be able to use that to drop our dev dependency on Docker compose v1, which in turn will let us upgrade to the latest major version of `jsonschema`, which is the final Meltano dependency that is considered "out of date" by `libraries.io`/`SourceRank`.

We should wait a week or two to see if any issues come up with the new major release. We're in no rush to make this change, so maybe we'll end up using `pytest-docker==1.0.1`, or something like that instead.

**Comment by edgarrmondragon** [comment]
@WillDaSilva interesting! So `pytest-docker` doesn't depend on [`docker-compose`](https://pypi.org/project/docker-compose/) (and in turn on [`docker`](https://pypi.org/project/docker/), which is likely to become unmaintained: https://github.com/docker/docker-py/pull/2989)?

That'd be neat and I that might fix the failing tests on Windows for Python 3.10.

**Comment by WillDaSilva** [comment]
@edgarrmondragon Yes, it seems like the only reason we have a dependency on `docker` is because of `pytest-docker`, so it should fix the failures observed on Python 3.10. In light of that, I've moved this up to the next iteration.

Relates to #6479

**Comment by WillDaSilva** [comment]
@visch since you're currently looking into https://github.com/meltano/meltano/issues/6479, you probably want to be aware of this.
