### ISSUE TITLE
bug:  Conflicting behavior flags in `meltano config set`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6512]
### Meltano Version

latest

### Python Version

NA

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

any

### Description

From Slack: https://meltano.slack.com/archives/C01TCRBBJD7/p1659032672217559?thread_ts=1658965446.758529&cid=C01TCRBBJD7

With the example invocation:

```console
meltano --environment=prod config target-csv set destination_path ./output
```

The expectation is that meltano would store the value within the environment config. Instead, the value is stored at the top-level meltano config.

## Workaround

The correct behavior can be achieved by also overriding `--store` as in:

```
meltano --environment=prod config target-csv set destination_path ./output --store=meltano_environment
```

## Proposed solution

The default behavior (without specifying `--store` or by using `--store=auto`) should be updated to prefer `meltano_environment` over `meltano_yml` if `--environment` is set to a valid environment name.

## Alternative Approaches

Another option is to remove or deprecate `--store=meltano_environment` in deference to the `--environment` flag being specified or not.

In that case `--store=meltano_yml` would indicate _either_ the top-level yaml declarations (if no environment is set) _or_ the environment-specific section of the yaml (if an environment is set).

Note:

- There are probably good reasons why this alternative wouldn't work, for instance if internally we need to treat these as two different stores and due to the fact that internally we would step through each layer with the top-level and environment-level yaml each being a different important part of that resolution.

**Comment by tayloramurphy** [comment]
> Another option is to remove or deprecate --store=meltano_environment in deference to the --environment flag being specified or not.

@aaronsteers we don't mention `meltano_enviornment` as a store option anywhere in the docs. And it's fairly confusing behavior with the --environment flag imo. I'd be in favor of just getting rid of it.

Either way, this is definitely a bug and should be fixed!

**Comment by tayloramurphy** [comment]
@cjohnhanson point 3 is right and reflects what we have in the documentation https://docs.meltano.com/reference/command-line-interface#using-config-with-environments

> Note: Unlike other commands like [meltano run](https://docs.meltano.com/reference/command-line-interface#run) and [meltano invoke](https://docs.meltano.com/reference/command-line-interface#invoke), the meltano config command ignores any configured [default environment](https://docs.meltano.com/concepts/environments#default-environment). This is to make it easier to configure plugins’ base configuration before adding environment-specific overrides.
