### ISSUE TITLE
[Bug]: Snowplow tracker does not timeout when endpoint is unavailable

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6532]
### Meltano Version

2.3.0

### Python Version

NA

### Bug scope

Other

### Operating System

NA

### Description

First reported by @dingobar here: https://meltano.slack.com/archives/C01TCRBBJD7/p1659099832402809

> Hi all, thanks for a great product! Everything is working great locally, and we've now deployed our meltano project on kubernetes where we already had airflow running. However, there is a hiccup: The job hangs after Environment 'dev' is active (see screenshot). 
> ![image](https://user-images.githubusercontent.com/11428666/181815830-029559ca-a21a-484e-8030-1fe9e5517584.png)
> 
> After about 15 minutes or so, the actual task completes, but the container keeps hanging telling me that the meltano run process has not yet exited and is blocked somehow. To me it seems like it is either stuck in an infinite loop, or trying to call something over the network with (seemingly) infinite retries/timeout.
> 
> We have a strict firewall policy where we explicitly name the domains to be whitelisted for egress out from our environment (required as we are in the telco business with very strict data protection requirements). My theory is that meltano is trying to call out to some external site. I have disabled telemetry in meltano in general (MELTANO_SEND_ANONYMOUS_USAGE_STATS="False" as stated in the docs).
> 
> As evident in the logs, it hangs for about 6 minutes before getting started:
> ![image](https://user-images.githubusercontent.com/11428666/181815889-85030c26-3cf8-4e7d-8116-24fad9ec05ad.png)
> 
> Update: So the culprit is found. It is trying to contact "[sp.meltano.com](http://sp.meltano.com/)" with an exponential retry backoff. How can I disable this behavior?
> ![image](https://user-images.githubusercontent.com/11428666/181815966-ea69a683-d853-42a8-84b9-fa5ae707069c.png)

We should:
- Change the default `request_timeout` value for `meltano.core.tracking.Tracker` from `None` to `3.5`.
- Add a test that simulates the endpoint not responding.

**Comment by tayloramurphy** [comment]
@WillDaSilva thanks for opening and picking up!

**Comment by WillDaSilva** [comment]
I attempted to use `requests_mock` (which we already have as a dependency) to mock the timeout, but unfortunately when it is being used the `requests` library doesn't seem to raise a timeout error. Hosting a basic HTTP server in a subprocess that accepts the connection but never responds to GET/POST requests might be the way to go.
