### ISSUE TITLE
bug: Windows fails on Python 3.7

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6544]
### Meltano Version

Latest

### Python Version

3.7

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Windows

### Description

Windows fails on Python 3.7, 

4 tests are failing we should address them with at least an xfail. 

See https://github.com/meltano/meltano/runs/7618285486?check_suite_focus=true

**Comment by WillDaSilva** [comment]
Will be addressed by:
- #7397
