### ISSUE TITLE
[Feature]: meltano add to project without install

### ISSUE THREAD

**Issue by aphethean1** [meltano/meltano#6550]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

**As a user, I need to add to my meltano project without install**

Adding to a meltano project is currently a very slow operation.  Our requirement is to add all the plugins to the project and then later build (i.e. 'meltano install') the whole project.  This means that the initial 'meltano add' is unnecessarily slow as we don't use any of the pip-installed modules from the initial 'meltano add'

Work arounds considered:
- directly add a meltano.yml format file with our plugin definition to a directory with the root meltano.yml includes referencing that directory path & directly save a lock file to the /plugins directory  (essentially avoiding using 'meltano add' at all)

This proposal is to be able to add to the meltano project rapidly without installing all pip dependencies, and we'd ideally like to be able to freeze those dependencies.

`meltano add --skip-install` should
1. download the lock file
2. add to the meltano.yml
3. add all the lock and meltano.yml files for any `requires` plugins (https://github.com/meltano/hub/pull/505 & https://github.com/meltano/meltano/issues/6107)

Related to:
This feature is related to https://github.com/meltano/meltano/issues/6416
**As a user, I need to add to my meltano project without install and create pip freeze**

`meltano add --skip-install --freeze` consider whether this --skip-install works if --freeze is used (assuming https://github.com/meltano/meltano/issues/6416 might implement --freeze)

**Comment by ReubenFrankel** [comment]
This was resolved by #6578 and can be closed. May need to revisit as per #6416.

**Comment by tayloramurphy** [comment]
Closed via https://github.com/meltano/meltano/pull/6578
