### ISSUE TITLE
Auto bucketized semantic commit/PR descriptions into changelog sections

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6574]
1. The goal here would be to have zero cosmetic or cleanup work to make the changelog, and that part could be fully automated in CI.
2. The pre-work would be for Engineers (with support+guidance from EM and PM) to groom PR titles as closely as possible to what the change log entry should be.
3. Post-work would be for EM, PM, and/or Marketing to groom wording and add links - but this would happen in the Release Notes version and not the changelog.

https://commitizen-tools.github.io/commitizen/customization/#custom-changelog-generator

For instance, this mapping from the sample could be customized for our conventions:

```
    change_type_map = {
        "feat": "Features",
        "fix": "Bug Fixes",
        "refactor": "Code Refactor",
        "perf": "Performance improvements"
    }
```

We may also want to customize other parts of the rendering process, such as removing type prefixes.

Also consider:

1. Do we need to replace PR links with Issue links?
2. Can Commitizen do this for us if so?

**Comment by edgarrmondragon** [comment]
@aaronsteers note that we can map types to headers without needing to implement our own changelog class. In the sdk, we have:

https://github.com/meltano/sdk/blob/26a3a8ff020b1e8b33eab4cf7c61cf9c6258286b/pyproject.toml#L124-L131

**Comment by aaronsteers** [comment]
Closing as resolved. Changelogs are automated now. 🎉 🙌
