### ISSUE TITLE
Docker publish release stage failures

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6575]
While releasing 2.4.0 we ran into failures of the docker publish stage: https://github.com/meltano/meltano/actions/runs/2806611004

Specifically, its complaining about:

https://github.com/meltano/meltano/blob/3bf8d54b69b2758fb2f3fa7fd6bd0abde156ff3c/.github/actions/docker-build-scan-push/action.yml#L72

> /home/runner/work/meltano/meltano/./.github/actions/docker-build-scan-push/action.yml (Line: 68, Col: 12): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.GITHUB_TOKEN

**Comment by pandemicsyn** [comment]
Note for when we pick this up next week. We''ll need to make sure we re-run the publish to ship the images 2.4.0 once this has been resolved.

**Comment by WillDaSilva** [comment]
We are accessing the secret directly within an action, but actions must have secrets passed in as inputs, since they don't get access to the `secrets` context.

**Comment by pandemicsyn** [comment]
> Note for when we pick this up next week. We''ll need to make sure we re-run the publish to ship the images 2.4.0 once this has been resolved.

Kicked this off: https://github.com/meltano/meltano/actions/runs/2819676858
