### ISSUE TITLE
feature: Make `hub_url` setting override the whole url & add a `hub_url_auth` setting to support for custom hubs.

### ISSUE THREAD

**Issue by DanielPDWalker** [meltano/meltano#6579]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

The current `hub_url` setting only allows you to change part of the url.

```python
    @property
    def hub_api_url(self):
        """Return the URL of the Hub API.

        Returns:
            The URL of the Hub API.
        """
        hub_url = self.settings_service.get("hub_url")
        return f"{hub_url}/meltano/api/v1"
```

We have been using a custom `discovery_url` with `discovery_url_auth` for a while, and now we are making the move over to Meltano 2.0+ we want to take advantage of the `hub_url`. We would like to use our `hub_url` with our own path and we also need to be able to supply auth with our request.

I was thinking we could make the default value for the `hub_url` to be Meltano's complete url `https://hub.meltano.com/meltano/api/v1` and make `hub_url` replace this completely. (This makes this setting the same as the `discovery_url` setting logic).

Also for supplying the auth with the request to the `hub_url` just copying the same logic from the `discovery_url_auth` setting as a new `hub_url_auth` setting.

The only issue I can think of is that in changing the logic for the `hub_url` this would break anyone with a project already using the `hub_url` in its current form.

**Comment by aphethean1** [comment]
Adding some context to this issue.

**As a user, I need to enable meltano discover / add to lookup plugins from a private and secure hub**

We are currently using meltano 1.0 to add plugins from our own discovery API.  As the meltano 1.0 API was simply `GET https://.../discovery.yml` - we only need to set the URL and add authentication headers.

To have the same ability to add plugins from an alternative / private hub requires two things:
1. the ability to point meltano add / discover capabilities at a new URL that supports a known API contract
2. the ability to add authentication headers to those custom hub HTTP requests.

As far as I can see from the PR.
- Adding a custom full url is beneficial to point 1 - but we will of course still need to understand how to support the HUB v1 API endpoints
- Support for custom auth has been added.

Alternatives considered:
- don't use `meltano discover` or `meltano add`.  We quickly ruled this out as users would no longer have one of the main meltano benefits.
