### ISSUE TITLE
bug: file bundles not added to `meltano.yml`

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/meltano#6586]
### Meltano Version

2.4.0

### Python Version

3.7

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Linux - Ubuntu 22.04

### Overview
File bundles are not added to the `meltano.yml` when `meltano add files <plugin_name>` is run. `meltano upgrade files` shows nothing to update as a result (possibly since the initial `2.0` release).

![image](https://user-images.githubusercontent.com/60552974/183462841-50bb3ae8-96da-4a5e-a912-c3ac2b801821.png)

Expected behaviour given file bundle in `meltano.yml` with no `update` extra:
![image](https://user-images.githubusercontent.com/60552974/183462733-f6111f36-3f1a-491c-a734-4ba53aeea56a.png)

Expected behaviour given file bundle in `meltano.yml` with `update` extra:
![image](https://user-images.githubusercontent.com/60552974/183462868-6a9ee454-95fb-4b16-82ae-1fe1e7b17435.png)

**Comment by ReubenFrankel** [comment]
Found this when looking into #6585.

**Comment by DouweM** [comment]
@ReubenFrankel This is by design: a file bundle without any "owned" files listed under `update` is not added to `meltano.yml` since it would never be used after the initial `meltano add`: https://github.com/meltano/meltano/blob/main/src/meltano/core/plugin/file.py#L31-L32

Is that incompatible with what you're trying to do?

**Comment by ReubenFrankel** [comment]
Thanks for the clarification @DouweM. I see my tests here were referencing the [hub `files-dbt`](https://github.com/meltano/hub/blob/17978719efec6a2081faa21b2d53137b7272fa43/_data/meltano/files/files-dbt/meltano.yml), which doesn't include the `update` extra. Confusingly, we also have a `files-dbt` internally that does specify this with `transform/profile/profiles.yml: true` - possibly from an old version of the `discovery.yml` (I just assumed the definition had stayed the same for the most part).

I suspect this isn't an actual issue for us now, but I'll circle back to the guys tomorrow morning just to be sure.
