### ISSUE TITLE
Update Yarn packages

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6594]
Our Docker image scanning currently identifies 224 issues: https://github.com/meltano/meltano/security/code-scanning

Many of them stem from us using outdated Yarn packages. In #6587 I updated all of the Yarn packages to their latest version, and then ran the scan again: https://github.com/meltano/meltano/security/code-scanning?page=1&query=ref%3Arefs%2Fheads%2Fupdate-yarn-packages

Updating the Yarn packages reduced the number of alerts from 224 to 73. We may not be able to update every Yarn package to its latest version, but at least as a first pass it would be worthwhile to update what we can.

This issue can (and probably should) be broken into multiple issues to address specific groups of dependencies that need to be updated, e.g. Vue. These sub-issues should be added to [the security audit cleanup milestone](https://github.com/meltano/meltano/milestone/8).

**Comment by rwfeather** [comment]
I've started to investigate the remaining 73 alerts, and write up issues for those that might need followup.

**Comment by rwfeather** [comment]
@WillDaSilva Whoops, didn't realize that the scope on this was limited to just the yarn updates. I'll run those updates and see if I can clear up the alerts.

**Comment by aaronsteers** [comment]
@WillDaSilva - Is this still an issue or have we mostly resolved these as of now?

Thanks!

cc @rwfeather

**Comment by WillDaSilva** [comment]
> Is this still an issue or have we mostly resolved these as of now?

@aaronsteers This is still an issue. Our JS dependencies have largely not been updated in a long time.

> UPDATE: As of rereading, I'm sure there are probably at least some of the 73 not yet resolved. Are there 2 or 3 that are high pri that we should focus on?

The aforementioned 73 issues are unrelated to this issue. They should be addressed after we address the outdated Yarn packages.
