### ISSUE TITLE
bug: CI Sending Telemetry Data

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6599]
Is it possible that our integration tests are sending telemetry data? We've had a bunch of noise in the telemetry data with short lived project IDs from the `random` project ID source that seems to look a lot like our own CI integration tests.

They started in May/June, are all using the `dev` environment, with is_ci_environment flag, using tap-gitlab and targt-jsonl, doing add/config/run.

cc @pandemicsyn @WillDaSilva @aaronsteers

**Comment by WillDaSilva** [comment]
@pnadolny13 What is the value of `is_dev_build` for them? That value is `false` when the release marker is present, and `true` otherwise.

**Comment by pandemicsyn** [comment]
@pnadolny13 @WillDaSilva The integration tests didn't exist until late June early July (merged in on July 1st), definitely didn't exist in May yet. All 3 also have usage turned off via meltano.yml, and they all have project ID's as well. 

If the project IDs were churning, the integration test would actually fail, since we diff the ending meltano YAML against an expected one (with a specific project ID).

**Comment by pandemicsyn** [comment]
@pnadolny13 in case its help's, the project id for the two integration tests that run tap-gitlab target-jsonl is: `abd310b5-698b-4244-a109-9490047fa2ec`: https://github.com/meltano/meltano/blob/main/docs/example-library/meltano-basics/ending-meltano.yml#L3

A quick and easy thing to peek would be throwing a `--log-level=debug` on https://github.com/meltano/meltano/blob/main/docs/example-library/meltano-basics/index.md#running-a-task in a PR, and then checking the output in Github Actions and see if a telemetry state chage event or something gets emitted.

**Comment by pnadolny13** [comment]
@WillDaSilva `is_dev_build` is `true` but I'm now seeing that its using Windows/GCP which wouldnt be us. And @pandemicsyn's merge timeline make this seem unlikely that its us, maybe its someone else's CI pipeline.

Thanks for looking into it and for the context, I'll go ahead and close this.
