### ISSUE TITLE
bug: Table of content links do not scroll page to selected entry

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6603]
### Meltano Version

NA

### Python Version

NA

### Bug scope

Other

### Operating System

Tested with Firefox and Chrome

### Description

Going to https://docs.meltano.com/reference/glossary#singer should result in the page being scrolled down till the "Singer" entry is at the top of the page. Once that page is open, clicking links in the table of contents on the right should result in the page being scrolled up/down, but instead nothing happens.

**Comment by tayloramurphy** [comment]
@afolson can you look at this? I can confirm that it doesn't jump to it, but it works for other pages.

**Comment by sbalnojan** [comment]
I thought this was a quick fix, but there is some jekyll magic at work here I can't see through at the moment. My fix doesn't fix: https://github.com/meltano/meltano/pull/7274.

**Comment by sbalnojan** [comment]
should now work and be closed!
