### ISSUE TITLE
bug: Coverage is only being reported for the `tests/` directory

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6606]
### Meltano Version

NA

### Python Version

NA

### Bug scope

Other

### Operating System

NA

### Description

[Codecov recently reported a 7.44% increase in coverage](https://app.codecov.io/gh/meltano/meltano/commit/bd8ff5b0ce3b3289a6b8af34a0d41067a714b77d). This was because we stopped reporting coverage for the `src/` directory - now we only report coverage for the `tests/` directory.

The PR that switch us over to using Nox for testing is where the change occurred:
- https://github.com/meltano/meltano/pull/6395

**Comment by edgarrmondragon** [comment]
oh this was me then! I'll tackle it.
