### ISSUE TITLE
feature: Make `.meltano` path configurable

### ISSUE THREAD

**Issue by rawwar** [meltano/meltano#6619]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

Making creation of `.meltano`  folder configurable will make it easy when running Meltano projects in read-only file systems. This will be similar to how Meltano accepts `db` path

**Comment by rawwar** [comment]
Thanks @edgarrmondragon . I got confused and created this issue on wrong repo. Thanks for fixing this

**Comment by aaronsteers** [comment]
@rawwar - Love this idea. Thanks for raising. 

Is this a feature you may be interested in contributing?

**Comment by rawwar** [comment]
Yes, I will be working on this. As of now, I am doing some analysis on how meltano supports other configurations. Once I am done with that, i'll post my approach

**Comment by rawwar** [comment]
@aaronsteers .. Can you please check the draft pr.

**Comment by tayloramurphy** [comment]
@edgarrmondragon assigning to you since you're on the PR
