### ISSUE TITLE
Remove legacy telemetry events

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6620]
We've had full coverage for our new unstructured telemetry events for some time now, presumably all major bugs have been spotting, and the downstream Squared dbt transformations [don't rely on the legacy events](https://github.com/meltano/squared/issues/340) as a primary source. We can go ahead and remove any extra code for these legacy events and stop double sending a backup structured event (if were still doing that).

cc @WillDaSilva @tayloramurphy

**Comment by WillDaSilva** [comment]
Thanks for ensuring they're no longer necessary @pnadolny13! Removing the legacy telemetry code will be satisfying.
