### ISSUE TITLE
feature: (docs) remove legacy DBT mentions from guides/docs

### ISSUE THREAD

**Issue by EMCP** [meltano/meltano#6626]
### Feature scope

Other

### Description

I am seeing mentions of the now legacy `dbt` install.. should we just go with 

ie 

https://github.com/meltano/meltano/blob/a95613a146dbfada79584edb6dfdfce25837af8e/docs/src/_guide/plugin-management.md?plain=1#L44

I can do a PR with the ` dbt-snowflake ` or `dbt-postgres` but wasn't sure if there's a reason yet to switch

**Comment by tayloramurphy** [comment]
@EMCP thanks for opening this issue. Yes, we want to point folks towards the adapter-specific versions. I think `dbt-postgres` is good as it promotes open source 😄 

@afolson @sbalnojan this would be good to get prioritized.

**Comment by tayloramurphy** [comment]
Pretty sure @pnadolny13 went through and did a nice cleanup of this.
