### ISSUE TITLE
bug: Test connector - asyncio

### ISSUE THREAD

**Issue by AvinashGupta802** [meltano/meltano#6632]
### Meltano Version

2.4.0

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Rocky Linux release 8.6

### Description

```
meltano config tap-postgres test
```

above command works fine till version 2.1.0 and python 3.9.7.

But it fails when i switched to 2.2.0,2.3.0 and 2.4.0

```
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fcad8ae8670>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 536, in close
    self._close(None)
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 560, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

To fix it , I changed file in `cli/config.y`:

```diff
-- is_valid, detail = asyncio.run(_validate()) (removed)
++is_valid, detail = asyncio.new_event_loop().run_until_complete(_validate())  (added)
```

Kindly get it check at your end and fix it in coming releases.

### Code

To fix it, I changed file in `cli/config.py`:

```diff
- is_valid, detail = asyncio.run(_validate())
+ is_valid, detail = asyncio.new_event_loop().run_until_complete(_validate())
```

**Comment by tayloramurphy** [comment]
@pandemicsyn @edgarrmondragon can you validate this bug and potential fix?

@AvinashGupta802 perhaps a PR for this would be better if you're willing to submit one

**Comment by edgarrmondragon** [comment]
@AvinashGupta802 @tayloramurphy I can't reproduce this on macOS and Python 3.9.13, and Ubuntu with the same Python version doesn't seem to have this issue.

I'd suggest upgrading to the latest Python 3.9.x, because I do see some asyncio bug fixes in the changelog: https://docs.python.org/3.9/whatsnew/changelog.html#python-3-9-8-final

**Comment by AvinashGupta802** [comment]
I tried with Python 3.9.13 same error. Screenshot attached. Post change in code it works. Screenshot attached
![image](https://user-images.githubusercontent.com/68946032/184810352-4f082e6a-33ea-44e9-98d9-3db0997c4660.png)
![image](https://user-images.githubusercontent.com/68946032/184810400-e513e07f-3d8f-4d9e-9f71-fe07f34c95e8.png)
![image](https://user-images.githubusercontent.com/68946032/184810410-c7ab1785-7d7e-4d20-9194-d0de61dcfe6c.png)

**Comment by pandemicsyn** [comment]
@AvinashGupta802 I'm curious, are you seeing similar issues with other commands such as  `meltano invoke` or `meltano test` ?

**Comment by AvinashGupta802** [comment]
invoke command works fine. Issue only with test command

**Comment by pandemicsyn** [comment]
It looks like this is most likely related to https://github.com/python/cpython/issues/88050. The test/validation actually **always** terminate the spawned subprocess early:

https://github.com/meltano/meltano/blob/ecac36b7d1094955e3ba2c7fd98d4f4201c4fe25/src/meltano/core/plugin_test_service.py#L70-L75

This error could also trigger on `meltano run` or `meltano elt` invocations where a plugin is being terminated early (e.g. a target fails and we kill the tap). 

Long term theres a pending fix upstream at https://github.com/python/cpython/pull/32073 but I'm not sure if/when that will actually land. So does feel like a temp fix/work around on our end might be warranted. 

Either the fix that @AvinashGupta802 proposed (probably ok for `test`, but not sure at a glance what the implications would be for switching `run`/`elt` to this), or rolling with one of the workarounds listed in the python bug report. Namely, from https://github.com/python/cpython/issues/88050#issuecomment-1093911484 and adding a call to `process._transport.close()`

**Comment by edgarrmondragon** [comment]
@pandemicsyn @WillDaSilva `process._transport.close()` seems reasonably stable and might be good enough. I guess the options then are

- do we wait for the current state of things to cause more issues for users because of the underlying bug or
- do we use the "protected" API and then wait for that to break with some future Python release

?

**Comment by pandemicsyn** [comment]
Since this is sort of an edge case - personally, i think I'd be ok with using the protected call and trying to keep tabs on that issue to resolve upstream. I'm guessing that's not getting back ported 3.7. This also isn't our first run-in with quirky asyncio.Subprocess behavior. We also had:

https://gitlab.com/meltano/meltano/-/issues/3347#note_894964904

**Comment by pandemicsyn** [comment]
@edgarrmondragon I guess there's also a sort of middle ground. Since this seems more likely to happen in `meltano test` where we always terminate the subprocess, we could maybe only implement the workaround of using the projected API there.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon I guess there's also a sort of middle ground. Since this seems more likely to happen in `meltano test` where we always terminate the subprocess, we could maybe only implement the workaround of using the projected API there.

@pandemicsyn that works for me

**Comment by pandemicsyn** [comment]
@AvinashGupta802 if you would like to take a stab at fixing this we'd definitely be open to a PR that implements the fix from https://github.com/python/cpython/issues/88050#issuecomment-1093911484 for https://github.com/meltano/meltano/blob/ecac36b7d1094955e3ba2c7fd98d4f4201c4fe25/src/meltano/core/plugin_test_service.py#L70-L75. 

@tayloramurphy if this goes on the backlog, realistically it's probably a 2, but I assigned a 4 in case some unexpected side effects pop up.

**Comment by AvinashGupta802** [comment]
@pandemicsyn ,  I have already informed with code changes done at my end  to resolve the issue faced by me.
