### ISSUE TITLE
bug: Error message "Directory meltano already exists." is displayed when user doesn't have write access to a directory for `meltano init`

### ISSUE THREAD

**Issue by pdebelak** [meltano/meltano#6638]
### Meltano Version

2.1.0

### Python Version

3.8

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Ubuntu 18.04 and MacOS

### Description

The error message "Directory meltano already exists." is displayed when you don't have write access to the directly you're trying to run `melano init` in.

### Code

```python
Assuming your user isn't root, you can reproduce like:


$ sudo mkdir example
$ cd example
$ meltano init meltano
Directory meltano already exists.
```

**Comment by edgarrmondragon** [comment]
@pdebelak thanks for reporting!

@tayloramurphy this seems like an easy fix by simply catching the specific exceptions for when the directory already exists, and also when the user doesn't have permission to create the directory.
