### ISSUE TITLE
docs: create deployment guide on deploying Meltano with Airflow on MWAA

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6655]
The K8 deployment is [having some issues](https://github.com/meltano/squared/issues/325) and it's not a great situation to just have one engineer able to support/troubleshoot kubernetes. We need to create a quick deployment guide for MWAA anyway, so this seems like a good opportunity to deploy the squared repo over to the MWAA managed Airflow service and at the same time prep a guide for our users who may want to do the same.

Note:

- Out of scope would be any change to Metabase, Superset, or other 'services' that are 'always on'. This would just be for the scheduled workflows.

**Comment by tayloramurphy** [comment]
This is stale and we're not likely to prioritize it any time soon.
