### ISSUE TITLE
chore: limit `feature_flag` method to `ProjectSettingsService`

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/meltano#6666]
Following up on  [this discussion](https://github.com/meltano/meltano/issues/6485#issuecomment-1226079127) in #6485.

Currently the `feature_flag` decorator is [a method defined on the `SettingsService` base class](https://github.com/meltano/meltano/blob/40a8066c3d3b5ad403bc08a4e51d195ffdd1e02a/src/meltano/core/settings_service.py#L635). However, since feature flags are top-level settings in a Meltano project and currently never defined in plugin settings, this has led to multiple cases of the method being used from a `PluginSettingsService`, where it will always show the given flag as not being set. To avoid this confusion, we should just move the method to `ProjectSettingsService`. 

CC: @edgarrmondragon @kgpayne

**Comment by cjohnhanson** [comment]
FYI @tayloramurphy and @aaronsteers, for some reason I'm not seeing a `weight` field for this, but I'd weight this at a `2`

**Comment by aaronsteers** [comment]
@cjohnhanson - It sounds like you have a good grasp on this so I'm assigning back to you to pickup whenever you're able.

Do I understand the symptom correctly, that the feature flag works as expected, but debug prints will have incorrect/missing values and lead to incorrect assumptions about the feature flag's config'ed value?

cc @pnadolny13 as fyi

**Comment by cjohnhanson** [comment]
@aaronsteers Actually the symptom is more that the feature flag works as expected when used correctly in the code base, but the way it's written right now makes it easy to use "incorrectly". There's no impact to end users right now but any contributors that are using feature flags for a new feature are liable to introduce a bug by using the feature flag method "incorrectly". We had two regressions in 2.3.0 that were a result of such incorrect usage, so this is just a quick refactor to head off those types of mistake and enforce "correct" usage.

**Comment by aaronsteers** [comment]
@cjohnhanson - It's been a while since we've touched or commented on this issue so just want to check in.

Is it okay if I remove the "Urgency=High" flag from this item on our Engineering board? If not, will talk with Taylor and try to prioritize in the next week or two.

**Comment by cjohnhanson** [comment]
@aaronsteers yeah I put this on the backburner since it's definitely a chore that doesn't have any immediate or short-term user impact. It should definitely have the `Urgency=High` flag removed.

**Comment by cjohnhanson** [comment]
This was actually resolved in https://github.com/meltano/meltano/pull/6971; all SettingsServices now have a `project_settings_service` attribute that's used for this. Closing.
