### ISSUE TITLE
Update environment variable resolution and expansion logic for schedules and jobs

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/meltano#6675]
Following up on #6387 and #6386, we'd like for job and schedule envs to have resolution and inheritance behavior as described [in this thread](https://github.com/meltano/meltano/issues/6386#issuecomment-1195887590). 

This should happen downstream of #6295. In working through #6387 I discovered that environment resolution for scheduled jobs are much more complex than environment resolution for plugins alone, since currently we can only really pass environment variables to schedule job invocations via the terminal environment. I pursued a couple dead ends while trying to avoid a full refactor but I think it's unavoidable and it will be easier to just overhaul our environment variable resolution logic and centralize as per #6295

**Comment by cjohnhanson** [comment]
Note: current behavior is that schedule env only takes precedence over terminal and .env layers and _does not do variable expansion_.

**Comment by WillDaSilva** [comment]
Still relevant
