### ISSUE TITLE
bug: `strict_env_var_mode` does not raises exceptions within `config` blocks

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/meltano#6696]
As of now, this works in `env` blocks but not within `config`.

This likely will just involve wrapping an additional `utils.expand_env_vars` call in the feature flag context.

This is a follow-up from https://github.com/meltano/squared/pull/312#issuecomment-1191828551

FYI @pnadolny13

**Comment by aaronsteers** [comment]
Thanks, @cjohnhanson for logging this and for digging in. Do you mind picking this up next week? Feel free to update the weight as needed. Thanks!

**Comment by aaronsteers** [comment]
Related but orthogonal:

- #3171
