### ISSUE TITLE
feature: script or CLI command to import existing dbt project

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6705]
This is a spin off from this spike https://github.com/meltano/meltano/issues/6649.

The first step is to [create docs](https://github.com/meltano/meltano/issues/6704) to explain how to manually migrate an existing project but a second iteration we talked about is to potentially automate it.

See some ideas in https://github.com/meltano/meltano/issues/6649#issuecomment-1233440366

> - accept a git URL or local directory that has a dbt project
> - parse the profiles.yml to get the target (and possible recommend additional environments! we could also parse the Jinja to see what env_var they need to set)
> - auto-install the proper adapter plugin
> - fully replace what's in the file bundle (possibly merge .gitignore but maybe nothing else)
> - prompt them to enter their credentials.

**Comment by WillDaSilva** [comment]
Still relevant
