### ISSUE TITLE
Docs: Consider splitting or moving the "Configuration Guide"

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6714]
https://docs.meltano.com/guide/configuration

In looking for a good docs link to privide inline during interactive config (#5892), I came to the Configuration Guide and found much of the content is more verbose than I thought would make a good linkable reference.

I think we could optionally move some of these topics under `Reference > Configuration` or `Concepts > Configuration`, and maybe keep the "Guide" section more concise. Or, maybe we move this guide to `Concepts > Configuration` and refactor the deeper dives into `Reference`? 

Wdyt @tayloramurphy, @pandemicsyn, @afolson, @kgpayne ?

**Comment by tayloramurphy** [comment]
@sbalnojan related to the PR we've been talking about. 

@aaronsteers yes, I'm in favor of anything that makes our documentation more usable. 

@afolson what's your guidance on how we should best structure these sorts of docs - are we leaning into the Diataxis framework or no?

**Comment by sbalnojan** [comment]
@tayloramurphy @aaronsteers hard to tell but sounds like you're looking for an actual reference? Something table-style? I did draw up a proposed restructuring of the docs: https://github.com/meltano/internal-marketing/issues/649, maybe that helps.

**Comment by tayloramurphy** [comment]
Covered by an internal issue.
