### ISSUE TITLE
chore: add test harness for `--interactive`

### ISSUE THREAD

**Issue by kgpayne** [meltano/meltano#6735]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Once #5892 merges, we will want to have patterns to test interactive functionality going forward if possible. This should include any templating done as part of the interactions (as per [this comment](https://github.com/meltano/meltano/pull/5892/files#r964962714)).

**Comment by kgpayne** [comment]
Having had a brief look, two common approaches appear to be:

- Mocking `stdin`/`stdout` and sending keypresses via `.communicate()`
- Testing the underlying functionality (template rendering, option calculation etc.) without directly invoking the CLI

We would likely want a bit of both 🙂

**Comment by WillDaSilva** [comment]
Still relevant. Here's how we currently test interactive project selection in the Cloud CLI:
https://github.com/meltano/meltano/blob/739d0a75fb5420b715cee7256feed88b145adfbe/src/cloud-cli/tests/cli/test_project.py#L194-L227

The relevant line is 214. It could definitely be made nicer using a test harness that takes a list of keys specified as enum elements. The harder yet more important problem to solve is testing the CLI without using a subprocess to supply input via stdin.
