### ISSUE TITLE
Meltano UI Snowplow Telemetry

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6755]
We should start sending Snowplow telemetry data for the meltano ui to understand page views, etc. Currently we get a CLI event that someone is starting up the UI but nothing from that point forward. It does look like we might be tracking some on GA already, but we need to migrate them to Snowplow.

I think this would entail adding a [javascript tracker](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/) to the relevant pages. 

https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/

cc @tayloramurphy

**Comment by WillDaSilva** [comment]
Closing as no longer relevant on account of the removal of the UI for Meltano 3.0
