### ISSUE TITLE
feature: allow disabling update checks in UI

### ISSUE THREAD

**Issue by dingobar** [meltano/meltano#6760]
### Feature scope

Web UI

### Description

See https://github.com/meltano/meltano/issues/6750#issuecomment-1247116799

Figured I'd file a separate issue for it.

Disabling the update check in the UI while still displaying the current version.

PR to follow shortly.

**Comment by WillDaSilva** [comment]
Thank you for the issue @dingobar. As you've hopefully heard by now, the Meltano UI has been deprecated, and is scheduled for removal in Meltano 3.0. Since no additional work/improvements for the UI are planned leading up to its removal, I'll be closing this issue.
