### ISSUE TITLE
docs: Add an FAQ on Singer / Meltano Community guidelines for connector development and maintenance

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6762]
Based on a discussion in https://github.com/meltano/dragon/discussions/42#discussion-4331307

* What do I do if I want to use a tap but the maintainer is dormant? Theres open PRs with no reviews, the last commit was over a year ago, it seems like most people are forking it and adding anything they need but not doing it in a sharable way, etc.
* When do I rewrite it with the SDK vs try to revive the existing tap?
* Whats expected of me to be a good tap writer so its generically useful so others benefit and help maintain it? i.e. full stream coverage, tests, CI, etc.
* What benefits do I get from making my tap generically useful, in a public repo, on the SDK, etc.?
* What if I don’t want to support it after I re-write it?
* Should I move it to MeltanoLabs? How do I do that? Why wouldn’t I do that?
* What are the expectations of me if I’m a stand alone maintainer in my own github namespace?
* How can I become a maintainer in MeltanoLabs? Why would I do that? How do I quit being a maintainer?
* What do I need to do to make sure my tap is well documented on the hub and functioning within Meltano? Why should I care?
* What happens if a repo gets deleted? I don’t want to risk using a variant if it could be deleted in the future? Should I be keeping a fork in my own namespace? Hard fork?
* Where do I go if I want to pay someone to build a tap or add a feature?
* How do I escalate an issue if it’s not being recognized by the maintainer?
* How do I flag a tap that should be migrated to the SDK for community prioritization?

and likely more!

@sbalnojan @afolson This would be a good effort coming into Tap-toberfest to get some of these clarified. My gut is that we should have this live on the docs, but having it on the Hub could be good as well!

**Comment by sbalnojan** [comment]
@tayloramurphy Agreed. I don't yet see a good plan for this. In the future, I believe this should live on the Hub, but right now I would aim for keeping things together, we already got the docs, the sdk-docs, soon to be the edk docs, the hub. 

Maybe we should just push an interims "Tap-toberfest" FAQ page into the docs (close-to-top level)? After all the questions are very tap specific as they should be for this event. But the answers are really plugin answers, so should be later on expanded.

**Comment by tayloramurphy** [comment]
@sbalnojan I love the tap-toberfest FAQ idea. Then we can pull that info out as we discover better homes for it.

**Comment by tayloramurphy** [comment]
Done in:

* https://github.com/meltano/hub/pull/1132
* https://github.com/meltano/hub/pull/1009
