### ISSUE TITLE
Add integration test that covers the various state manipulation features and behaviors

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/meltano#6773]
While reviewing https://github.com/meltano/meltano/pull/6758 where we're adding custom state id suffixes, thought it might be nice to have a integration test that show cases and covers all the various state manipulation features we gained via the state command as well as the different behaviors for meltano run invocations.

**Comment by pandemicsyn** [comment]
Related 

- https://github.com/meltano/meltano/pull/6742#issuecomment-1249513809

...also floated some state related integration tests there.

**Comment by WillDaSilva** [comment]
Still relevant

**Comment by edgarrmondragon** [comment]
I believe this was addressed by https://github.com/meltano/meltano/pull/6911
