### ISSUE TITLE
feature: consider allowing meltano run plugins to export env vars to context for down stream plugins to use

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6777]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

I have a tap-spreadsheets-anywhere [configuration](https://github.com/meltano/squared/blob/81087cb90817a44e50a0702671dac11861792c03/data/extract/extractors.meltano.yml#L19) that I want to make more dynamic by injecting a DATE into the Azure IP address URL (because its rotated every 14 days). Currently environment variables dont expand at that depth of config so I cant use regular environment variable templating. Also using the scheduled jobs feature I dont have the ability to set environment variables prior to my run like `MY_DATE=$(date +'%Y-%m-%d') meltano run tap-spreadsheets-anywhere target-snowflake` because Airflow builds the command for me for the input `tap-spreadsheets-anywhere target-snowflake`. Another thing to consider is that my production is in read-only mode, I think many others do this too, so I cant make changes to files.

Something I considered doing was writing a python script to populate the config value and try to export it to the meltano environment context, like `meltano run my_script_to_export_env tap-spreadsheets-anywhere target-snowflake`. This is definitely a hack but I wonder if theres other use cases for something like this, maybe multi tenant would also like something like this.

I know theres probably a challenge with the idea of potentially parallelizing these blocks in the future in which case the timing of the script would get messed up.

@kgpayne suggested that we consider adding functionality to the EDK to allow writing back to meltano environment, maybe thats a path forward.

Is there a simpler way to achieve what I want?

Related slack thread https://meltano.slack.com/archives/C01UTUSP34M/p1660163864060499

**Comment by tayloramurphy** [comment]
> using the scheduled jobs feature I dont have the ability to set environment variables prior to my run

@pnadolny13 this came up in slack today. Would https://github.com/meltano/files-airflow/issues/32 solve it? You can specify an `env` on schedules but currently for `meltano run` based schedules it doesn't work as expected.

> Currently environment variables dont expand at that depth of config

https://github.com/meltano/meltano/issues/3171 is the solution for that - will you give that a thumbs up?

**Comment by pandemicsyn** [comment]
> Would https://github.com/meltano/files-airflow/issues/32 solve it?

@tayloramurphy I might be misunderstanding but I think @pnadolny13 has a need for more "dynamic" env vars. Things you define in the schedule config would generally be static.

> Is there a simpler way to achieve what I want?

A context concept is something we've chatted about it in the EDK spec discussions, and something I could definitely see being handy.  A databricks plugin might provision a spark cluster and passing on what cluster was provisioned, etc.

> I know theres probably a challenge with the idea of potentially parallelizing these blocks in the future in which case the timing of the script would get messed up.

IMHO there shouldn't be - if we're smart about how jobs/tasks get parallelized - you would just need to ensure that your script runs before down stream parallel tasks get farmed out. Basically, it "just" means run invocations need to support both sequential and parallel execution stages. Which with our current "Block" architecture is totally doable.

**Comment by pnadolny13** [comment]
>@pnadolny13 this came up in slack today. Would https://github.com/meltano/files-airflow/issues/32 solve it? You can specify an env on schedules but currently for meltano run based schedules it doesn't work as expected.

@tayloramurphy no unfortunately that still doesnt solve it for me. So I think theres actually 2 things here:

1. My variables aren't expanded at the depth I need - solved by https://github.com/meltano/meltano/issues/3171.
2. I have no way (in the default setup) to pass dynamic env vars into my schedule/job.

To get around 1 I can set my whole config as an env var that I expand myself, so thats a limitation but not a complete blocker  i.e. `TAP_SPREAD_SHEETS_ANYWHERE__TABLES='[zyx with my dynamic date included]' meltano run tap-spreadsheets-anywhere target-snowflake`


Like @pandemicsyn suggested the problem is that my env var is dynamic so I need it to regenerate before every run (logic as an excel formula: `=DATE(2022,7,11)+14*ROUNDDOWN((NOW()-DATE(2022,7,11))/14)`).
1. I could theoretically use this syntax to export before running `MY_DATE=$(date +'%Y-%m-%d') meltano run tap-spreadsheets-anywhere target-snowflake`. But the limitation is that I'd need to create a custom Airflow DAG to support that because you can't prepend to the command in schedule/job paradigm we have now.
1. I'd prefer not to try to write that with a bash script since I'm less familiar. Using Python would be ideal, thats why I thought of it as a utility plugin in my run chain `meltano run my_script_to_export_env tap-spreadsheets-anywhere target-snowflake`.

I like the idea of the EDK having a context concept. Another Airflow specific way to solve this would be to create [an Airflow variable](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html) for every DAG thats empty by default but I'm able to edit it to add a list of exports like `MY_DATE=$(date +'%Y-%m-%d')` that gets prepended to my meltano command when it gets built. `[OPTION_AIRFLOW_VAR_CONTENT] meltano run tap-spreadsheets-anywhere target-snowflake`. I dont necessarily love that and it doesnt completely solve my problem but it gives more flexibility so users (and I) can hack it enough to work for these edge cases.

Maybe thats where my edge case takes me past whats expected from the default implementation though 🤔 .

Does that make sense?

**Comment by tayloramurphy** [comment]
@pnadolny13 is a fair generic summary of the feature you want is to support dynamic date calculation in environment variables? 

It seems like if you could define in the `env` key a dynamic date calculation and then if that is evaluated at run/invocation time and is available for use by plugins that would solve your problem. We could say that `env` on schedules, jobs, and environments are available to all plugins whereas `env` on plugins is locally scoped to that plugin. does that work?

**Comment by pnadolny13** [comment]
>@pnadolny13 is a fair generic summary of the feature you want is to support dynamic date calculation in environment variables?

Yes thats my current need.

Although the feature that I want is to have a generic way to pass information from one plugin to the next in the chain. I'm suggesting that be done with env vars right now but maybe theres another way. Other use cases could be for API key rotation - requesting a fresh API key and passing it along before running a tap, retrieving secrets from a custom secret store, etc. Its a way to be more flexible so users can do weird uncommon custom things when they need to, like everyone eventually always has to (i.e. my weird dynamic date logic for tap-spreadsheets).

I think a common reaction by users to these custom workflows is to fork the tap and write the custom logic in there like Christoph suggested [to my question in slack](https://meltano.slack.com/archives/C01UTUSP34M/p1660167937187559?thread_ts=1660163864.060499&cid=C01UTUSP34M) but that proliferates the Singer fork problem and makes it way harder to have a small set of shared commonly useful variants. If users can extend functionality without having to do it in the plugin where it doesnt belong then I think users and the community will be happier.

**Comment by DouweM** [comment]
Related request: use tap-postgres to get get Salesforce credentials for N customers, that are then passed to N tap-salesforce/target-snowflake pipelines.

**Comment by pnadolny13** [comment]
Another related request by @JulesHuisman in slack thread https://meltano.slack.com/archives/C03QCPY1XBQ/p1668112601570319. The idea was to create an extension that allows you to inject env vars from Azure Key Vault like `meltano run vault:inject tap-xyz target-xyz`. This may potentially be solved by secrets backends though.

**Comment by WillDaSilva** [comment]
Still relevant
