### ISSUE TITLE
bug: exit code null on snowplow telemetry

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6778]
In investigating https://github.com/meltano/internal-data/issues/26 I saw a large increase in bad events. Looks like all of the ones from 2.6.0 and 2.5.0 are from:

`$.exit_code: null found, integer expected`

And I dove in on each one and it's from `add` and `discover` events.

queried using:

```sql
select *
from "RAW"."SNOWPLOW"."EVENTS_BAD"
where date_trunc('week', uploaded_at) > '2022-08-22'
and jsontext ilike '%2.5.0%';
```

**Comment by tayloramurphy** [comment]
FYI @WillDaSilva @aaronsteers

**Comment by WillDaSilva** [comment]
We can prevent issues like this in the future by implementing https://github.com/meltano/meltano/issues/6780.
