### ISSUE TITLE
bug: Disabling telemetry from the UI has no effect

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6782]
### Meltano Version

2.6.0

### Python Version

3.8

### Bug scope

Other

### Operating System

Linux - python:3.8 Docker image

#### Reproduction steps:
1. ```
   docker run --entrypoint=/bin/bash -p 5000:5000 -it python:3.8
   ```
2. ```
   pip install pipx && pipx install meltano==2.6.0 && pipx ensurepath && bash
   ```
3. ```
   meltano init testproject && cd testproject && meltano --log-level=debug ui
   ```
4. Open your browser (n.b. I used Firefox) to `http://localhost:5000`
5. In another shell within the environment, create a `ProjectSettingsService` to observe that `send_anonymous_usage_stats` is `True`:
   ```python
   >>> from meltano.core.project_settings_service import ProjectSettingsService
   >>> from meltano.core.project import Project
   >>> ProjectSettingsService(Project('/testproject')).get_with_metadata('send_anonymous_usage_stats')
   (True, {'name': 'send_anonymous_usage_stats', 'source': <SettingValueStore.DEFAULT: 'default'>, 'setting': <SettingDefinition send_anonymous_usage_stats (boolean)>, 'expandable': False, 'auto_store': <SettingValueStore.MELTANO_YML: 'meltano_yml'>, 'overwritable': True})
   ```
   At this point, `meltano.yml` has the following content (modulo the random project ID):
   ```
   version: 1
   default_environment: dev
   environments:
   - name: dev
   - name: staging
   - name: prod
   project_id: testproject-d2c1652c-911d-4ef1-bd54-146c4d2573f5
   ```
   And `.meltano/analytics.json` has `"send_anonymous_usage_stats": true`.
7. Click the "Disable" button in the popup at the bottom right of the browser:
   ![image](https://user-images.githubusercontent.com/11428666/191764427-9787aea9-ec77-4d56-aff4-6b50d3a67974.png)
   No browser console errors/warnings were observed when this button was clicked.
8. Before exiting `meltano ui`, repeat step 5, and observe the same result.
9. Exit `meltano ui` by entering Ctrl-C in it's terminal (i.e. send it `SIGINT`), then wait for it to cleanly shut down.
10. Repeat step 5, and observe the same result.

#### Expected behaviour:
Either step 7 or step 9 (depending on the implementation of the feature) should have caused the `send_anonymous_usage_stats` setting to be changed from `True` to `False`.

The long output of `meltano --log-level=debug ui` can be provided upon request, but it didn't seem to have any interesting information. No log lines were emitted when the "Disable" button was clicked.

**Comment by WillDaSilva** [comment]
fyi @tayloramurphy @aaronsteers

**Comment by tayloramurphy** [comment]
@WillDaSilva thanks for the issue. 

Seems like we have 2 options - make the buttons do what they're supposed or update the text to have folks update their meltano.yml file.

@WillDaSilva what's a weight estimate on just fixing the "Disable" button?

@aaronsteers let's not cut another release until this is fixed please.

**Comment by WillDaSilva** [comment]
> what's a weight estimate on just fixing the "Disable" button?

@tayloramurphy I didn't know that button existed until this morning, so I'm not sure yet. I'll make this issue my highest priority, and get an estimate (or fix) asap.

**Comment by WillDaSilva** [comment]
@tayloramurphy Thoughts on simply removing the popup? The problem here isn't that the UI lacks a way to disable telemetry - it's that it misleads users into thinking that it has been disabled. Removing the popup should be very easy.

**Comment by tayloramurphy** [comment]
@WillDaSilva I'd be fine with removing it. The UI is deprioritized anyways and anything we can do to simplify and reduce code surface area makes sense to me.

**Comment by WillDaSilva** [comment]
Draft PR up: https://github.com/meltano/meltano/pull/6783

Will mark as ready once I've tested it.

**Comment by pandemicsyn** [comment]
@WillDaSilva @tayloramurphy this disables the UI's builting google analytics tracking:

https://github.com/meltano/meltano/blob/dfd9650170ff97fd69fdff7ac8dc7dc0841bf663/src/webapp/src/utils/setupToasted.js#L65

https://github.com/meltano/meltano/blob/dfd9650170ff97fd69fdff7ac8dc7dc0841bf663/src/webapp/src/utils/setupAnalytics.js#L10

So probably need permanen;ly disable/remove that if we're not using it anymore.

**Comment by WillDaSilva** [comment]
@pnadolny13 Are we collecting/using the Google Analytics data from the UI?

**Comment by WillDaSilva** [comment]
> this disables the UI's built-in google analytics tracking
> So, probably need to permanently disable/remove that if we're not using it anymore.

@tayloramurphy @pandemicsyn That the UI's telemetry can only be disabled from a 1-time popup seems like a bug in its own right. Its telemetry settings should come from Meltano's configuration on disk. I'm in favour of disabling it altogether until that is the case.

**Comment by WillDaSilva** [comment]
I have updated https://github.com/meltano/meltano/pull/6783 to remove the UI telemetry code. Alternatively, we can keep it around but disable it until we resolve the configuration issue, but I'd rather not keep unused code around. If we want to re-enable it later, we can refer to the git history.

**Comment by pandemicsyn** [comment]
@WillDaSilva it looks like it was supposed to obey the meltano config:

https://github.com/meltano/meltano/blob/dfd9650170ff97fd69fdff7ac8dc7dc0841bf663/src/webapp/src/main-embed.js#L21

https://github.com/meltano/meltano/commit/124a3ae093131773b4e01510e1a5a3ff3da3fee6

That popup may always present to comply with cookie consent laws now, or its a bug, or something else.  (this is all way before my time, just poking around and sharing)

**Comment by WillDaSilva** [comment]
> (this is all way before my time, just poking around and sharing)

@pandemicsyn Thanks, I appreciate it.

**Comment by WillDaSilva** [comment]
> it looks like it was supposed to obey the meltano config

@pandemicsyn That's good. Assuming it works, that means we can keep the Meltano UI telemetry mostly unchanged. The trouble is that we don't want to display the "disable tracking" toast unless it disables all Meltano Telemetry, rather than just the UI telemetry, but we may have to show it to comply with tracking consent laws. With that in mind, I'm still in favour of disabling it (as https://github.com/meltano/meltano/pull/6783 does) until we can make the "Disable" button in the UI disable it in `meltano.yml` too.

**Comment by pnadolny13** [comment]
>@pnadolny13 Are we collecting/using the Google Analytics data from the UI?

@WillDaSilva yes it looks like we're getting UI events in GA. I'm not pulling them into Snowflake or anything so I'm not personally using them. I also had created https://github.com/meltano/meltano/issues/6755 to track converting those to Snowplow events.

**Comment by tayloramurphy** [comment]
> I'm in favour of disabling it altogether until that is the case.

@WillDaSilva As am I. At this point we need to be completely off GA on the Meltano product side.
