### ISSUE TITLE
bug: Meltano GUI modals don't close when expected [Firefox]

### ISSUE THREAD

**Issue by EMCP** [meltano/meltano#6794]
### Meltano Version

2.7.0

### Python Version

3.10

### Bug scope

Web UI

### Operating System

Ubuntu 22.04.01

### Description

I am utilizing Firefox `v105.0.1 `(not sure if via snap or not) but noticing modals are not closing in multiple areas where i would expect them to ( ie clicking save or close)

https://meltano.slack.com/files/U029UBQETF1/F043HUWCCNT/ezgif-3-3695244762.gif

This occurs in the new pipeline modal as well as the Tap / Target Modal .. like when hitting save on details.. it WILL save but the modal just sits there leaving me doubting I saved.

**Comment by aaronsteers** [comment]
@pandemicsyn and @WillDaSilva - Do we think this is a new unique bug, perhaps related to #6783? It could also be a byproduct of an underlying failure in the state migration issue #6790?

**Comment by WillDaSilva** [comment]
Thanks for the bug report @EMCP! This should be fixed in our next release.
