### ISSUE TITLE
bug: Flaky Meltano tests

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6827]
This issue lists tests which are known to be flaky, i.e. they fail intermittently when they ought to pass. Each flaky test can be broken into a new issue, addressed on its own, then checked off here.

Relates to https://github.com/meltano/meltano/issues/6693, but per @aaronsteers's comment we probably only want to automatically re-run flaky tests as a last resort if they cannot be rewritten to be consistent.

Tip: **Most of these failures won't be reproducible even with the same environment, since they will generally pass on a re-run in CI.** If attempting to reproduce a flaky test listed here, use the `--randomly-seed` pytest parameter set in CI for the run where the test failed. Reproducing the operating system, Python version, Meltano version, processor count, memory, etc. may also be necessary, but don't spend too much time on that without first trying to find the problem by analyzing the CI logs.

---

GitHub's workflow/job search UI doesn't let me filter it down to workflow runs that have more than 1 attempt, so I used this PyGitHub script:

```python
import os

from github import Github

agent = Github(os.environ['GITHUB_TOKEN'])
repo = agent.get_repository('meltano/meltano')
runs = repo.get_workflow_runs(status='success')
test_runs = (x for x in runs if x.raw_data['name'] == 'Tests')
test_runs_with_multiple_attempts = (x for x in test_runs if x.raw_data['run_attempt'] > 1)
# Now things get tricky since PyGitHub doesn't support workflow jobs
prev_attempt_urls = ('https://github.com/' + '/'.join(x.raw_data['previous_attempt_url'].split('/')[4:]) for x in test_runs_with_multiple_attempts)
{print(x) for x in prev_attempt_urls} # Inspect manually
```

---

- [ ] `tests/meltano/cli/test_run.py::TestCliRunScratchpadOne::test_run_elb_mapper_failure`
  - https://github.com/meltano/meltano/actions/runs/3136801194/jobs/5094171268
  - https://github.com/meltano/meltano/actions/runs/3153399664/jobs/5134862454
  - https://github.com/meltano/meltano/actions/runs/3339418003/jobs/5528344676
  - https://github.com/meltano/meltano/actions/runs/3585009701/jobs/6032430292
  - https://github.com/meltano/meltano/actions/runs/3714760211/jobs/6299089376
  - https://github.com/meltano/meltano/actions/runs/4054733556/jobs/6976928663
  - https://github.com/meltano/meltano/actions/runs/4247354877/jobs/7385308374
  - https://github.com/meltano/meltano/actions/runs/4472933889/jobs/7859710299
  - https://github.com/meltano/meltano/actions/runs/4522728566/jobs/7965396188
  - https://github.com/meltano/meltano/actions/runs/4585553739/jobs/8097759636
- [x] https://github.com/meltano/meltano/issues/6854
- [ ] `tests/meltano/api/test_security.py::TestAuthenticationAndAnonymousReadonlyEnabled::test_plugins_add_authenticated`
  - https://github.com/meltano/meltano/actions/runs/3132016030/jobs/5083934615
- [ ] `tests/meltano/api/test_security.py::TestAuthenticationEnabled::test_plugins_add_authenticated`
  - https://github.com/meltano/meltano/actions/runs/3329478164/jobs/5506759851
  - https://github.com/meltano/meltano/actions/runs/3329477705/jobs/5506754466
  - https://github.com/meltano/meltano/actions/runs/3698148524/jobs/6263988311
  - https://github.com/meltano/meltano/actions/runs/3940788424/jobs/6742354155
- [ ] `tests/meltano/cli/test_add.py::TestCliAdd::test_add_transform`
  - https://github.com/meltano/meltano/actions/runs/4522728566/jobs/7965396188
  - https://github.com/meltano/meltano/actions/runs/4545662486/jobs/8013309148
- [ ] `tests/meltano/cli/test_job_cmd.py::TestCliJob::test_job_set`
  - https://github.com/meltano/meltano/actions/runs/3184585185/jobs/5193157667
- [ ] `tests/meltano/cli/test_lock.py::TestLock::test_lock_invalid_options[noop]`
  - https://github.com/meltano/meltano/actions/runs/3191746652/jobs/5209925544
- [ ] `tests/meltano/core/test_plugin_install_service.py::TestPluginInstallService::test_install_all`
  - https://github.com/meltano/meltano/actions/runs/3267515752/jobs/5372786662
  - https://github.com/meltano/meltano/actions/runs/3269312608/jobs/5376677525
  - https://github.com/meltano/meltano/actions/runs/3329477705/jobs/5506754124
  - https://github.com/meltano/meltano/actions/runs/3659356836/jobs/6185268488
  - https://github.com/meltano/meltano/actions/runs/4032452134/jobs/6932338731
  - https://github.com/meltano/meltano/actions/runs/4055323683/jobs/6978314619
  - https://github.com/meltano/meltano/actions/runs/4055739476/jobs/6979286249
  - https://github.com/meltano/meltano/actions/runs/4055845651/jobs/6979538185
- [ ] `tests/meltano/core/test_plugin_install_service.py::TestPluginInstallService::test_install_all[-p=1]`
  - https://github.com/meltano/meltano/actions/runs/4578465364/jobs/8085116719
  - https://github.com/meltano/meltano/actions/runs/4669269577/jobs/8267486627
- [ ] `tests/meltano/core/test_plugin_install_service.py::TestPluginInstallService::test_install_all[-p=2]`
  - https://github.com/meltano/meltano/actions/runs/4522345211/jobs/7964742972
- [ ] `tests/meltano/cli/test_state.py::TestCliState::test_list`
  - https://github.com/meltano/meltano/actions/runs/3490651708/jobs/5842342506
- [ ] `tests/meltano/cli/test_upgrade.py::TestCliUpgrade::test_upgrade_files_glob_path`
  - https://github.com/meltano/meltano/actions/runs/3525144664/jobs/5911493541
- [ ] `tests/meltano/core/logging/test_output_logger.py::TestOutputLogger::test_logging_exception`
  - https://github.com/meltano/meltano/actions/runs/3536279042/jobs/5935167500
  - https://github.com/meltano/meltano/actions/runs/3753357946/jobs/6376530779
  - https://github.com/meltano/meltano/actions/runs/4106334072/jobs/7084425102
  - https://github.com/meltano/meltano/actions/runs/4106321761/jobs/7084395837
- [ ] `tests/meltano/cli/test_upgrade.py::TestCliUpgrade::test_upgrade_files`
  - https://github.com/meltano/meltano/actions/runs/4044948931/jobs/6955746829
  - https://github.com/meltano/meltano/actions/runs/4544469876/jobs/8010541383
- [ ] `tests/meltano/api/test_security.py::TestProjectReadonlyEnabled::test_pipeline_schedules_save`
  - https://github.com/meltano/meltano/actions/runs/4058145440/jobs/6984724927
- [ ] `tests/meltano/cli/test_add.py::TestCliAdd::test_add_files_with_updates`
  - https://github.com/meltano/meltano/actions/runs/4545662486/jobs/8013308443
  - https://github.com/meltano/meltano/actions/runs/4545662486/jobs/8013306633
- [ ] `tests/meltano/cli/test_add.py::TestCliAdd::test_add_files_without_updates`
  - https://github.com/meltano/meltano/actions/runs/4545662486/jobs/8013308443
  - https://github.com/meltano/meltano/actions/runs/4580875274/jobs/8089983751
- [ ] `tests/meltano/cli/test_add.py::TestCliAdd::test_add_files_that_already_exists`
  - https://github.com/meltano/meltano/actions/runs/4862405870/jobs/8668725395
- [ ] `tests/meltano/core/tracking/test_tracker.py::TestTracker::test_get_snowplow_tracker_invalid_endpoint`
  - https://github.com/meltano/meltano/actions/runs/5764993276/job/15630071331

**Comment by aaronsteers** [comment]
@meltano/engineering - Please drop additional tests here if you know of any that are failing/flaky.

Also - from the above three, let me know if you have thoughts on any of these:

1. How difficult to fix/rewrite the test?
2. Is the test adding value and worth keeping?
