### ISSUE TITLE
Change the `default_environment` default setting to `null` and change `meltano run` to require an environment

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6833]
Resolves 

- https://github.com/meltano/meltano/issues/6677

This is a two-part change:

- [X] Make `environment` required for `meltano run`.
   - Ideally this would be paired with or complemented by improved error messaging as logged in #6832 
- [X] Revert the default value for `default_environment` to `null` instead of `'dev'`.

Related to:

- #6862

**Comment by tayloramurphy** [comment]
@aaronsteers not sure I agree with this. Can you give me more insight/context?

**Comment by tayloramurphy** [comment]
@aaronsteers and I synced on this. I had misunderstood this proposal as wanting to set `default_environment: null` for all new installations. This is about the default when nothing is present. We're good here.
