### ISSUE TITLE
Ignore default Meltano Environment on non-execution CLI commands

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6834]
Per:

- https://github.com/meltano/meltano/issues/6677#issuecomment-1228821208

We should ignore `default_environment` for all of the following commands:

> ...these are the commands that can't apply an environment and probably shouldn't have a default environment applied:
> 
> - [add](https://docs.meltano.com/reference/command-line-interface#add)
> - [discover](https://docs.meltano.com/reference/command-line-interface#discover)
> - [environment](https://docs.meltano.com/reference/command-line-interface#environment)
> - [init](https://docs.meltano.com/reference/command-line-interface#init)
> - [install](https://docs.meltano.com/reference/command-line-interface#install)
> - [lock](https://docs.meltano.com/reference/command-line-interface#lock)
> - [remove](https://docs.meltano.com/reference/command-line-interface#remove)
> - [ui](https://docs.meltano.com/reference/command-line-interface#ui)
> - [upgrade](https://docs.meltano.com/reference/command-line-interface#upgrade)
> - [user](https://docs.meltano.com/reference/command-line-interface#user)
> - [version](https://docs.meltano.com/reference/command-line-interface#version)

> These could have an environment applied or not, but probably should follow the meltano [config](https://docs.meltano.com/reference/command-line-interface#config) behavior of the user specifying it explicitly:
>
> - config
> - [job](https://docs.meltano.com/reference/command-line-interface#job)
> - [schedule](https://docs.meltano.com/reference/command-line-interface#schedule)
> - [select](https://docs.meltano.com/reference/command-line-interface#select)
> - [state](https://docs.meltano.com/reference/command-line-interface#state)

Which then leaves these as applying `default_environment` automatically:

> These could be run without an environment and should auto-apply the default if available:
> 
> - [elt](https://docs.meltano.com/reference/command-line-interface#elt)
> - [invoke](https://docs.meltano.com/reference/command-line-interface#invoke)
> - [test](https://docs.meltano.com/reference/command-line-interface#test)
>
> This should really not be run without an environment, because behaviors like auto-state tracking won't work as expected when no environment is set:
> 
> - [run](https://docs.meltano.com/reference/command-line-interface#run)

**Comment by tayloramurphy** [comment]
@aaronsteers I've already pulled this into:

* https://github.com/meltano/meltano/issues/6767

This is likely worth doing an ADR on and then opening issues on the work needed to accomplish it. 

Can we close this as a duplicate?
