### ISSUE TITLE
feature: Include environment_name prefix in state_id for schedules

### ISSUE THREAD

**Issue by qbatten** [meltano/meltano#6848]
### Feature scope

API

### Description

When you use the CLI to run a `meltano run <tap> ... <target>` command, the state id for that job will be automatically prefixed with the current environment. However, schedules do not behave this way, and they just use the schedule name as the state_id/job_name. I think this could result in a dev environment unintentionally overwriting prod state, if the two environments share a meltano system database.

I'd like it if schedules used an environment prefix as well. This would protect users from inadvertently altering state across environments.

The environment prefix behavior of `meltano run` is [documented here](https://docs.meltano.com/reference/command-line-interface#run), and I confirmed through a check in my own environment that v2.4.0 does not use environment prefixes for schedules, whether orchestrated or called via CLI (`meltano schedule run`).

Related:

- #6853

**Comment by qbatten** [comment]
There's also a bit of discussion related to this [on Slack here](https://meltano.slack.com/archives/C01TCRBBJD7/p1664380053801389?thread_ts=1664314402.975189&cid=C01TCRBBJD7)

**Comment by tayloramurphy** [comment]
> I confirmed through a check in my own environment that v2.4.0 does not use environment prefixes for schedules, whether orchestrated or called via CLI (meltano schedule run).

@qbatten this highlights the need for better versioned docs! cc @afolson @sbalnojan 

Agreed that this would be a good feature to have. I wasn't aware that `schedule` didn't defer to `meltano run` for the state id. @pandemicsyn @aaronsteers is that your understanding of the behavior?

**Comment by qbatten** [comment]
Simple workaround is to set state_id_suffix for each env you use, but that requires users to know about this issue, so it doesnt protect them from running into it accidentally. Also that functionality was added in a very-recent version I believe

**Comment by tayloramurphy** [comment]
Ping on this @aaronsteers @pandemicsyn https://github.com/meltano/meltano/issues/6848#issuecomment-1267631607

**Comment by aaronsteers** [comment]
@tayloramurphy - I agree this sounds like an important issue.

@qbatten - There are two methods of configuring schedules - you can configure schedules as EL jobs, with our older syntax, or you can configure schedules to run named jobs. Can you confirm if you are able to observe this behavior (using `schedule_name` as `state_id`) for just the EL-defined syntax, and _not_ also the job-defined syntax?

**Comment by aaronsteers** [comment]
> I'd like it if schedules used an environment prefix as well. This would protect users from inadvertently altering state across environments.

Assuming the above assumptions are correct, perhaps we could set logic so that:

> - If the schedule uses job syntax, _or_ if it defines 'environments: {}', then the newer state_id naming convention is used.
> - Else: the older convention is applied, which uses schedule name as the state ID.

We could do this as part of this:

- #6853 

And technically, it would only be a breaking change for legacy users _when and if_ they expand their `meltano.yml` to declare an environment mapping for those legacy schedules.

@tayloramurphy, @qbatten - what do you think?

**Comment by tayloramurphy** [comment]
@aaronsteers I don't have an immediate concern with that 👍

**Comment by WillDaSilva** [comment]
Still relevant
