### ISSUE TITLE
Meltano `config list` and `config set` should print settings with `kind:secret` as `(redacted)`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6858]
As reported in slack and I have confirmed locally.

Currently `meltano config set` will print the setting value in clear text after setting it, and similarly, `config list` will print the secret value in clear text as well.

Proposed changes:

1. `meltano config set` would print `(redacted)` in place of the setting value when confirming that the value has been stored.
2. `meltano config list` would print `(redacted)` in place of the current value when printing the list of all settings.

cc @tayloramurphy

**Comment by aaronsteers** [comment]
Steps to reproduce (from the squared repo):

```console
aj@AJs-MacBook-Pro data % meltano config target-snowflake set password supersecret
2022-10-05T19:37:56.666962Z [info     ] Environment 'userdev' is active
2022-10-05T19:37:56.901772Z [info     ] The default environment (userdev) will be ignored for `meltano config`. To configure a specific Environment, please use option `--environment=<environment name>`.
2022-10-05T19:37:58.098408Z [error    ] Your project's local `discovery.yml` manifest could not be parsed.
2022-10-05T19:37:58.099296Z [warning  ] Falling back on the `discovery.yml` manifest received from https://discovery.meltano.com/discovery.yml...
Loader 'target-snowflake' setting 'password' was set in `.env`: 'supersecret'
aj@AJs-MacBook-Pro data % meltano config target-snowflake list                     
2022-10-05T19:38:28.602383Z [info     ] Environment 'userdev' is active
2022-10-05T19:38:28.876655Z [info     ] The default environment (userdev) will be ignored for `meltano config`. To configure a specific Environment, please use option `--environment=<environment name>`.
2022-10-05T19:38:30.158472Z [error    ] Your project's local `discovery.yml` manifest could not be parsed.
2022-10-05T19:38:30.159501Z [warning  ] Falling back on the `discovery.yml` manifest received from https://discovery.meltano.com/discovery.yml...
account [env: TARGET_SNOWFLAKE_ACCOUNT] current value: 'epa06486' (from `meltano.yml`)
        Account: Snowflake account name (i.e. rtXXXXX.eu-central-1)
dbname [env: TARGET_SNOWFLAKE_DBNAME, TARGET_SNOWFLAKE_DATABASE] current value: None (default)
        DB Name: Snowflake Database name
user [env: TARGET_SNOWFLAKE_USER, TARGET_SNOWFLAKE_USERNAME] current value: None (default)
        User: Snowflake User
password [env: TARGET_SNOWFLAKE_PASSWORD] current value: 'supersecret' (from the TARGET_SNOWFLAKE_PASSWORD variable in `.env`)
        Password: Snowflake Password
```

**Comment by aaronsteers** [comment]
@kgpayne - Do you mind sizing this for us, and if capacity allows and `weight` is not too large, would be good to pick up in a coming iteration.

cc @tayloramurphy

**Comment by DouweM** [comment]
@aaronsteers @tayloramurphy I think we should still have some way to verify it's been set correctly. We had a bug in the past where env-var expansion would accidentally remove anything following a `$` from a password, for example, that would be hard to identify without being able to see what Meltano will actually pass on to the plugin. 

A new flag on `config list` perhaps? Or do you think `meltano config` showing the unredacted value will be sufficient (assuming you left that one out in the description on purpose)?

**Comment by aaronsteers** [comment]
@DouweM - Thanks for the extra context. It's pretty common for secrets to be set in a one-way capacity, without visibility after the value being set.

I would personally lean towards also redacting on `meltano config` (with no subcommand) but adding something like `--secrets` `--with_secrets` or `--secrets=true` allowing users to skip redactions.

**Comment by aaronsteers** [comment]
Related but a tangent, it might be worthwhile to map the `meltano config` base behavior (while prints a json string in the style we'd pass as `config.json`  to a tap or target) into a more explicit subcommand like `debug` or `dump`. 

With either `debug` or `dump` as the subcommand, printing the clear text secrets also becomes more a more predictable UX - with or without any additional CLI args... 🤔💭

**Comment by tayloramurphy** [comment]
@kgpayne can you give this a size estimate on the Product Roadmap project. I don't think we're ready to build yet, but need that estimate. cc @aaronsteers

**Comment by edgarrmondragon** [comment]
Probably still relevant

**Comment by ReubenFrankel** [comment]
Hi, would you accept a PR for this? @edgarrmondragon @tayloramurphy

**Comment by tayloramurphy** [comment]
@ReubenFrankel yep!
