### ISSUE TITLE
bug: meltano test - tap-snowflake, reports success but the tap doesn't work

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6860]
### Meltano Version

2.7.1

### Python Version

3.8

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Ubuntu

### Description

Follow the steps here https://hub.meltano.com/extractors/tap-snowflake

1. add snowflake
2. Configure snowflake incorrectly
3. Run meltano test tap-snowflake

The test success even though I"m missing a required key of "Tables"

![image](https://user-images.githubusercontent.com/8680264/194373876-b41cc386-51d0-4016-83b6-af440be63084.png)

**Comment by edgarrmondragon** [comment]
The `tap-snowflake` was not selected by the test command (`0 test(s) successful. 0 test(s) failed`).

@visch does `meltano config tap-snowflake test` work as expected?

**Comment by visch** [comment]
@edgarrmondragon  Yes `meltano config tap-snowflake test` works as expected! Maybe this is a hub issue then as it's asking to run the wrong command
![image](https://user-images.githubusercontent.com/8680264/194387944-14f48b75-77c7-4232-90d5-55c692f70134.png)

**Comment by edgarrmondragon** [comment]
Started a PR to change the suggested command: https://github.com/meltano/hub/pull/881

**Comment by visch** [comment]
This is fixed with the doc update I believe!
