### ISSUE TITLE
feature: Add support for `state` in meltano ui

### ISSUE THREAD

**Issue by spacecowboy** [meltano/meltano#6874]
### Feature scope

Web UI

### Description

We are running our jobs using the new pipeline syntax: `meltano run ...`

And we are running our jobs as Kubernetes Cron Jobs (so not Airflow).

For us `meltano ui` is just blank essentially. Entirely pointless.

But if the UI could show the current state, a bit like `meltano state` does, then that would be valuable to us.

That would make it possible to view states for any pipeline, regardless of how and where they execute.

**Comment by tayloramurphy** [comment]
@spacecowboy we're not prioritizing the UI right now and I would expect it to fall further behind the CLI at least for the next few months. We will get back to it in 2023 though and start to improve parity, but investments will be in the CLI and API for a while.

**Comment by WillDaSilva** [comment]
Closing as no longer relevant on account of the removal of the UI for Meltano 3.0
