### ISSUE TITLE
feature: Testing Guides in Docs

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6881]
### Feature scope

Other

### Description

It would be great to test docs see comments here https://github.com/meltano/meltano/issues/3112#issuecomment-1277131112 

Specifically the getting started docs, at a minimum those should continually works. https://gitlab.com/meltano/meltano/-/blob/master/.gitlab/ci/sample_code.gitlab-ci.yml#L20-42 had it before, and I've seen that test save a few things back on gitlab 🤷

**Comment by afolson** [comment]
Couldn't agree more. We also have this one on the radar (also from you :D) https://github.com/meltano/meltano/issues/3394

**Comment by visch** [comment]
Forgot about that one! I'll close this @afolson
