### ISSUE TITLE
Make version bump workflow comment a link to the draft release

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6900]
Draft releases are no longer shown in the releases tab for whatever reason. Having the version bump workflow add a comment to the new draft release is a simple workaround.

**Comment by WillDaSilva** [comment]
The workaround until this is implemented is to find the link to the draft release in the workflow job logs.

**Comment by edgarrmondragon** [comment]
@WillDaSilva is this still an issue? They do display for me.

**Comment by WillDaSilva** [comment]
@edgarrmondragon Let's check: https://github.com/meltano/meltano/actions/runs/3291024120
