### ISSUE TITLE
feature: Pool database connections - don't open new connections all the time

### ISSUE THREAD

**Issue by spacecowboy** [meltano/meltano#6908]
### Feature scope

Other

### Description

We run Meltano in Kubernetes on Google Cloud. To access the state database the connection must go via a proxy server. This is how the logs looks when Meltano is running:

![Screenshot from 2022-10-18 10-16-30](https://user-images.githubusercontent.com/223655/196375865-dee48494-62e5-433b-ab2e-763b75f9f62c.png)

Would be great if Meltano would stop opening new connections all the time and instead reuse connections.

**Comment by WillDaSilva** [comment]
Still relevant
