### ISSUE TITLE
Lock file doesn't contain all of the metadata, i.e. `description`, `logo_url`, etc.

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6914]
Raised by Aaron in office hours.

**Comment by aphethean1** [comment]
Thanks!  100% this is it.

## As a user, when I 'meltano add ...' my /plugins/*.lock files do not have the plugin description

**Comment by tayloramurphy** [comment]
@edgarrmondragon thanks for the detail. Can you add a weight estimate to the Product Roadmap project for future reference?

**Comment by edgarrmondragon** [comment]
@tayloramurphy gh won't let me edit the Prelim Weight field, but this is probably a `2`

**Comment by tayloramurphy** [comment]
@edgarrmondragon oh! that's an access thing. I invited the engineering team to have write access, so should be good there for the future. thanks!
