### ISSUE TITLE
How to represent arrays contents in plugin definitions?

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6916]
Is there a more detailed way to define the plugin settings when theyre arrays/objects? I'm thinking of something like[ tap-csv](https://github.com/MeltanoLabs/tap-csv#settings) that has a list of file definitions and the [definition on the hub](https://github.com/meltano/hub/blob/1ecf10628cb2500e3eb1d05de565a9ce77ba9267/_data/meltano/extractors/tap-csv/meltanolabs.yml#L19) just assigns it as an array and describes the nested structured of each element in the description. Is there a way to describe these in more detail?

I know we already have the dot syntax for object like `setting.sub_setting` but is there a way to do that for arrays?

```json
"setting": {
   "sub_setting": "x"
}
```

Like `files.0.setting.sub_setting`?

```json
"files": [
  {
    "setting": {
         "sub_setting": "x"
      }
  }
]
```

I'm not sure if something like this already exists or if we would even want it if not but wanted to check. This was following a discussion in office hours about more detailed settings definitions.

**Comment by tayloramurphy** [comment]
> I know we already have the dot syntax for object like setting.sub_setting but is there a way to do that for arrays?

@pnadolny13 Seems like we should be able to do `setting[n].sub_setting`. @meltano/engineering ?

**Comment by WillDaSilva** [comment]
> Seems like we should be able to do `setting[n].sub_setting`. 

@tayloramurphy @pnadolny13 Yeah, that can be done. Shouldn't be difficult. We cannot, however, have an attribute name that starts with a digit*.

---

*Unless we're being very pedantic, in which case I'd clarify that though we can have such an attribute, we wouldn't be able to access it with the normal dot notation.

**Comment by pnadolny13** [comment]
@tayloramurphy @WillDaSilva yeah this would be nice to have! Assuming we build this and allow support for indexing a setting somehow this makes me think of a few other related features also:

1. I should be able to define the schema of my settings without the index in settings_group_validation somehow so the plugin definition says "for every array element you must include sub_setting_x and sub_setting_y".
2. Interactive config should enter a loop when accepting an array - this might already be possible.

This makes me wonder if we should support a more detailed json schema notation in the kind field. Like we use the basic `kind` values we have today but if theres something more advanced we can add a more complex json schema definition. I noticed also that with SDK based connectors more people are using complex nested configs because the SDK tap.py in combination with Meltano lets you to easily define those with JSON schema notation vs previously singer.io manual configs made that harder so it was less common.

**Comment by edgarrmondragon** [comment]
> This makes me wonder if we should support a more detailed json schema notation in the kind field. Like we use the basic `kind` values we have today but if theres something more advanced we can add a more complex json schema definition.

@aaronsteers and I were discussing just that the other day. It's an interesting idea.

**Comment by aaronsteers** [comment]
@pnadolny13 - Can you help me better understand your use case? Are you wanting to get assist in setting values with `meltano config set` - or in entering the metadata for the setting? For metadata, I think likely every entry in the array would have the same description, correct? So, for instance, we'd want to set a description and type specification for `files[].setting.sub_setting`, but not necessarily needing a separate description and type constraint for `files[0].setting.sub_setting`, `files[1].setting.sub_setting`, etc., correct?

**Comment by tayloramurphy** [comment]
We have an old issue related to this as well https://github.com/meltano/hub/issues/22

**Comment by tayloramurphy** [comment]
We also have https://github.com/meltano/hub/issues/24#issuecomment-1195835961 @aaronsteers where we'd talked about this previously.

**Comment by pnadolny13** [comment]
@aaronsteers I think both but I spun off https://github.com/meltano/meltano/issues/6926 as a separate issue, so this discussion can be specifically about plugin definitions.

My challenge is that while going through and adding settings I'm seeing a bunch of configs that are arrays like https://github.com/meltano/hub/blob/1ecf10628cb2500e3eb1d05de565a9ce77ba9267/_data/meltano/extractors/tap-csv/meltanolabs.yml#L19 where all we can do in the hub definition is call it "array" type and put a long description text describing what the contents of that array should be. Ideally that would be something that we can define in a more rigid schema definition.

Sounds like theres a couple issues/discussions around this already - I can close this an cross link in
https://github.com/meltano/meltano/discussions/6237 if thats better.

**Comment by pnadolny13** [comment]
Closing this issue and moving the discussion to https://github.com/meltano/meltano/discussions/6237
