### ISSUE TITLE
feature: Add a `--refresh` option for `meltano select` to refresh a new copy of the discovered catalog

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6919]
This feature would add a `--refresh` option, or similar CLI arg to the `meltano select` CLI command. https://docs.meltano.com/reference/command-line-interface#select

```
# Refresh the cached catalog by re-running discovery
meltano select tap-github --refresh

# Print the normal --list output *after* refreshing the catalog
meltano select tap-github --list --refresh
```

This would give users the ability to force a refresh of the cached `catalog.json` file.

## Related

- https://github.com/meltano/meltano/issues/6915
- https://github.com/meltano/meltano/issues/6763
- https://github.com/meltano/meltano/discussions/6757#discussioncomment-3650870

**Comment by TyShkan** [comment]
Since the ‎[SingerTap.catalog_cache_key explicitly‎ ignores selection filter rules update](https://github.com/meltano/meltano/blob/265b61e4a80d1f3ba297fd688bc2a9e85269449f/src/meltano/core/plugin/singer/tap.py#L603), this feature would be nice to have instead of manual unlinking of .meltano/run dir before running select --list

**Comment by edgarrmondragon** [comment]
For anyone interested in taking a looking at this, the caching logic lives in https://github.com/meltano/meltano/blob/ab6e2d9607291be1ce994e9ada34057045374c54/src/meltano/core/plugin/singer/tap.py#L362-L371

**Comment by edgarrmondragon** [comment]
Another user ran into this, with tap-salesforce this time: https://www.linen.dev/s/meltano/t/16176363/tap-salesforce-not-adding-new-columns#242718da-e029-470b-a9bb-37e110669d4d.

**Comment by isoctcolo** [comment]
Hello all, 
It was me who ran into the issue. Is this --refresh command an acceptable solution to be taken into consideration ?
As described above I think the refresh would be enough. As I understood the lis takes then the cached catalog anyway.

**Comment by edgarrmondragon** [comment]
> Hello all, It was me who ran into the issue. Is this --refresh command an acceptable solution to be taken into consideration ? As described above I think the refresh would be enough. As I understood the list takes then the cached catalog anyway.

@isoctcolo I think it is acceptable. The idea is that the `--refresh` flag would force the catalog to be refreshed, disregarding whether a catalog exists or the cache key matches.

**Comment by isoctcolo** [comment]
Ok I dig into the code - could take me some time but for me it is good practice to get to know meltano better
