### ISSUE TITLE
docs: Make it clear the UI is not currently prioritized

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6924]
* https://docs.meltano.com/guide/production#meltano-ui
* https://docs.meltano.com/reference/ui#undefined
* few other places

We should clearly indicate that the UI is deprioritized and likely doesn't work with many of the newer features.

**Comment by aaronsteers** [comment]
Internal discussion: https://github.com/meltano/internal-general/discussions/443#discussioncomment-3684123
