### ISSUE TITLE
feat: Config Interactive - Iterate arrays

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6926]
If the plugin definition kind is an array we should enter a loop in the interactive config session to build all the elements. Right now it accepts a single value so the user has to write the whole array at once. We can have it request a single element, then keep looping until the user is done instead.

![Screen Shot 2022-10-24 at 1 16 16 PM](https://user-images.githubusercontent.com/27376735/197586360-8e1e8f6a-9ec2-4fcb-a744-3ad02f6d4769.png)

As an example but doesnt need to be this exact UX:

```
Add array elements one at a time, leave blank to exit:
  New value (array element 1): {"entity": "abc", "path": "", "keys": []}
  New value (array element 2): {"entity": "def", "path": "", "keys": []}
  New value (array element 3): <Hits Return> 
INFO New Value Added -> [{"entity": "abc", "path": "", "keys": []}, {"entity": "def", "path": "", "keys": []}]
```

**Comment by WillDaSilva** [comment]
Still relevant
