### ISSUE TITLE
feature: Print/log Meltano version at the start of execution

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6939]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Either at the DEBUG or INFO level, a line at the very top of the output indicating the version of Meltano, and possibly the operating system, would make it easier for the team and community to help users troubleshoot their issues.

**Comment by aaronsteers** [comment]
@edgarrmondragon - thanks for logging. Do you think debug level is sufficient? I could probably be fine with either but 'debug' is probably the easiest thing to say 'yes' to.

**Comment by edgarrmondragon** [comment]
@aaronsteers Yes, debug level may be sufficient.

**Comment by aaronsteers** [comment]
Okay, thanks @edgarrmondragon. This is a very rare case where I'm estimating a "Prelim Weight" of `1`. 😄 

Feel free to bump up higher if you think it's larger than that.

**Comment by WillDaSilva** [comment]
Still relevant

**Comment by ashu565** [comment]
@WillDaSilva @edgarrmondragon  Can I pick this up?

**Comment by WillDaSilva** [comment]
@ashu565 Sure thing!
