### ISSUE TITLE
feature: `--cwd` CLI option

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#6943]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

As seen in some other CLIs, it'd be nice to have a `--cwd` option which takes a path to a directory as an argument, and runs the program as-if it were invoked from that directory. This could be implemented by calling [`os.chdir`](https://docs.python.org/3/library/os.html#os.chdir) right after the CLI options are parsed if the `--cwd` option is provided.

**Comment by edgarrmondragon** [comment]
Meltano does have `MELTANO_PROJECT_ROOT` which has a similar function. A cli option would be nice.

**Comment by WillDaSilva** [comment]
@edgarrmondragon I wasn't aware `MELTANO_PROJECT_ROOT` could be set before execution to make Meltano use that directory. I just thought it was set by Meltano to be used by plugins and for env var expansion in settings. Thanks for the tip, and yeah, even with that I'd still appreciate a CLI option.
