### ISSUE TITLE
SQLAlchemy error after downgrading Python version

### ISSUE THREAD

**Issue by evanaze** [meltano/meltano#6947]
### Meltano Version

2.8.0

### Python Version

3.8

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Linux - Ubuntu 20.04

### Description

I created a meltano project with a virtual environment with the Python version 3.10.4. The `superset` connector is not yet compatible with Python 3.10. I deleted the old virtual environment and created a new one with Python version 3.8.14.

After re-installing meltano and running any command such as `meltano config` I see the following error. It seems to be a SQLAlchemy error related to some database that meltano is using internally.

I tried to create a new meltano project and copy over the `meltano.yaml` file, thinking that maybe by getting a new hash it would resolve the issue, but I'm seeing the same error.
[meltano_stacktrace.txt](https://github.com/meltano/meltano/files/9897617/meltano_stacktrace.txt)

### Code

The full stack trace is linked above.
```
│ /home/evan/workspace/awsdx-hackathon/venv/lib/python3.8/site-packages/sqlalchemy/engine/default. │
│ py:736 in do_execute                                                                             │
│                                                                                                  │
│    733 │   │   cursor.executemany(statement, parameters)                                         │
│    734 │                                                                                         │
│    735 │   def do_execute(self, cursor, statement, parameters, context=None):                    │
│ ❱  736 │   │   cursor.execute(statement, parameters)                                             │
│    737 │                                                                                         │
│    738 │   def do_execute_no_params(self, cursor, statement, context=None):                      │
│    739 │   │   cursor.execute(statement)                                                         │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    context = <sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at               │ │
│ │              0x7f15d1fa5e80>                                                                 │ │
│ │     cursor = <sqlite3.Cursor object at 0x7f15d21c6a40>                                       │ │
│ │ parameters = ()                                                                              │ │
│ │       self = <sqlalchemy.dialects.sqlite.pysqlite.SQLiteDialect_pysqlite object at           │ │
│ │              0x7f15d221a520>                                                                 │ │
│ │  statement = 'ALTER TABLE embed_tokens ADD COLUMN resource_type VARCHAR'                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OperationalError: (sqlite3.OperationalError) duplicate column name: resource_type
[SQL: ALTER TABLE embed_tokens ADD COLUMN resource_type VARCHAR]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Cannot upgrade the system database. It might be corrupted or was created before database migrations where introduced (v0.34.0)
```

**Comment by edgarrmondragon** [comment]
This is probably caused by #6405.

@evanaze I'll list some potential workarounds for you:

## Build Python with a newer SQLite

One workaround is, if you can, to build 3.8 on your system. Easiest way to do that is probably with pyenv:

```
pyenv install 3.8.15
```

That should build Python 3.8.15 with the latest available SQLite in your system:

```console
$ for ver in 3.8 3.9 3.10 3.11
do
  echo -n "SQLite bundled in Python $ver: "
  "python$ver" -c 'import sqlite3; print(sqlite3.sqlite_version)'
done
SQLite bundled in Python 3.8: 3.37.0
SQLite bundled in Python 3.9: 3.37.0
SQLite bundled in Python 3.10: 3.37.0
SQLite bundled in Python 3.11: 3.37.0
```

Otherwise we should to ship Meltano with a version of SQLite cc @aaronsteers 

## Point to a different database

Set [`database_uri`](https://docs.meltano.com/reference/settings#database_uri) to point to an external Postgres database.

**Comment by evanaze** [comment]
Thank you for the reply @edgarrmondragon. It looks like my `.meltano/meltano.db` must've been created with an older version of SQLite3, because I installed Python `3.8.15` and upgraded my SQLite3 to `3.31.1`, the latest on apt. 

What ended up working for me was just deleting `.meltano` and running `meltano install`.
