### ISSUE TITLE
feat: Cloud CLI `meltano cloud status` command as a default action for users to take

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#6958]
This is more relevant for Managed, but having a `status` command that users could run at any time may provide a nice UX for knowing what to do when starting at a blank terminal screen. 

This command could return:

* Status of any deployment
* Latest change to the system
* Number of running jobs and their general status
* Tips and hints for what to do with the command line

@aaronsteers thoughts on this? My thinking is that users may not need "help" per se, but would want to see the overall status and have a "default" place to go on the CLI.

**Comment by tayloramurphy** [comment]
@WillDaSilva I've updated the title. My preference would be to have this in Cloud first.

**Comment by pnadolny13** [comment]
@tayloramurphy personally I dont necessarily need this right now although it could be nice to have.

With the ideas in the issue description and from https://github.com/meltano/meltano/issues/7424 it sort of feels like the info fits in two separate buckets to me. One for cloud summary info to see status of my deployment and another for the status of my current CLI session to see if I'm ready to start interacting with cloud. Does that make sense? Were you leaning towards one vs the other?

## Cloud Summary

With an Airflow/Meltano deployment I would normally open up the Airflow landing page in the morning and look for green circles to know that everything is healthy and go from there if anything failed. Now that I'm using Cloud I dont necessarily have something like that although the slack webhook messages are basically doing the job but in a slightly ugly/noisey way. It could be nice to have a way to get a summary of my deployment in the morning, I think this is what some users were imagining a web UI would have, not tons of functionality but a pretty overview of statuses. Personally if I had a status CLI option and a UI I'd choose the UI.

## CLI Session Status and Helper

I think the term `status` is playing off the `git status` that everyone knows and is a default thing to type when you land on the terminal. I use it as a check to make sure everything is as expected before I take any actions e.g. branch, changes staged, etc. I'm imaging a similar feature in the cloud CLI would tell me if I'm logged in and what deployment and project I'm using, maybe some suggested commands. This implies some kind of stickiness with the cli like setting project/deployment for a session to avoid having to pass in `--deployment=xyz` with each command.

**Comment by WillDaSilva** [comment]
> This implies some kind of stickiness with the cli like setting project/deployment for a session to avoid having to pass in `--deployment=xyz` with each command.

Side note: we currently have this for projects via `meltano cloud project use`, and plan to add it for deployments via `meltano cloud deployment use`. Would either be done as part of this underspecified issue, or as a follow-up:
- https://github.com/meltano/meltano/issues/7465

**Comment by tayloramurphy** [comment]
> CLI Session Status and Helper

@pnadolny13 thanks for the feedback! I think another avenue I hadn't mentioned was a place for notifications. If we wanted to push a notifications to users that could be a place to do it too.

Do you have another idea for a command? `about`, `home`, `dashboard`? I'd be interested if there's prior art or other examples of this in other tools too..
