### ISSUE TITLE
bug: Flaky tests in `meltano add` for `files` plugins

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6965]
Looks like we're getting other failures on `main` too: https://github.com/meltano/meltano/actions/runs/3405886679/jobs/5664185706

I'm not sure if these are related. I have not yet looked into them.

_Originally posted by @WillDaSilva in https://github.com/meltano/meltano/issues/6962#issuecomment-1304891919_

**Comment by aaronsteers** [comment]
@edgarrmondragon and @WillDaSilva - Just wanted to confirm the classification on this is Urgency=High. Are we still seeing this regularly, and if so, should we prioritize highly for this coming week?

**Comment by edgarrmondragon** [comment]
@aaronsteers I haven't seen it for a while, and as for an estimate I think the quickest thing would be to use something like [`pytest-retry`](https://pypi.org/project/pytest-retry/) and that would make it a `4` imo.

**Comment by WillDaSilva** [comment]
@aaronsteers I also haven't seen this in a while. I don't yet know what caused it, but the issue is no longer pressing, so I've lower the urgency to `default`.

**Comment by aaronsteers** [comment]
I'm closing as 'not planned'. Please reopen is the issue recurrs.
