### ISSUE TITLE
docs: tutorial needs to be updated following default tap-github variant change

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6983]
The default variant for [tap-gihub was changed](https://github.com/meltano/hub/pull/895) a while ago but the [tutorial](https://docs.meltano.com/getting-started/part1) looks to be using the non-default variant. This was raised in Slack by a user [that got stuck trying to complete the tutorial.](https://meltano.slack.com/archives/C01TCRBBJD7/p1668441919326509?thread_ts=1668188059.315489&cid=C01TCRBBJD7)

We should probably start including the variant name in tutorial `add` commands so they arent affected by hub default changes. Also in this case we might want to consider switching to the new default meltanolabs variant for the tutorials, although I know thats probably not super easy. 

cc @sbalnojan @tayloramurphy 

@edgarrmondragon @aaronsteers @WillDaSilva (idk who to tag here) Do we still have tutorial integration tests running? Shouldn't they be failing on this?

**Comment by sbalnojan** [comment]
@pnadolny13 @WillDaSilva @edgarrmondragon the tutorial integration tests only work on code blocks that I could not reproduce with the "cool animations". (Lacking the JS skills) 

Oh well, more updates for the tutorial I guess.

**Comment by pnadolny13** [comment]
@WillDaSilva I was referring to the part 1-4 tutorials https://docs.meltano.com/getting-started/part1, they do use tap-github. And I see we use tap-gitlab in the complete tutorial https://docs.meltano.com/getting-started/. @sbalnojan are these suppose to be matching? Like you can choose to do the 1-4 parts or consume it all at once in the complete guide? If so, it looks like we need to get the complete guide to use github also.

**Comment by sbalnojan** [comment]
Got a hot fix: https://github.com/meltano/meltano/pull/6984 for now. 

@pnadolny13 No they are not supposed to match, I just did not want to delete the old one. (And there still is some content in there I haven't moved into separate documents)
