### ISSUE TITLE
ci: Bug in CI test actions

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6994]
`Command pytest --randomly-seed=3780789350 -m 'not concurrent' failed with exit code 1`

https://github.com/meltano/meltano/actions/runs/3477277758/jobs/5813278569

<img width="1521" alt="image" src="https://user-images.githubusercontent.com/18150651/202118262-e26a08d3-1b73-4b59-9710-f81d6f95b5ca.png">

**Comment by WillDaSilva** [comment]
Flaky test failures should be recorded in the description of:
- #6827
