### ISSUE TITLE
bug: strict_env_var_mode feature flag not respected?

### ISSUE THREAD

**Issue by qbatten** [meltano/meltano#6998]
### Meltano Version

2.10

### Python Version

3.7

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Amaon Linux

### Description

I think the change in strict_env_var_mode that came out w 2.10 (https://github.com/meltano/meltano/pull/6971) is causing issues for me with [pipelinewise/target-snowflake](https://hub.meltano.com/loaders/target-snowflake/). Not 100% sure if its a real bug or something's messed up in my setup that was revealed by that change. But upon upgrade to 2.10, all my runs started failing with `"Environment variable 'TARGET_SNOWFLAKE_SCHEMA' referenced but not set`. I don't think I've ever set that variable and I dont... think(?) that plugin is actually expecting that env var? I am also noticing that this error gets thrown only for schedules that are defined in the "legacy ETL" syntax, not via "jobs".

### Code

```python
2022-11-16T22:36:29.972001Z [error    ] ("Environment variable 'TARGET_SNOWFLAKE_SCHEMA' referenced but not set", 'Make sure the environment variable is set') 
Traceback (most recent call last):
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/utils/__init__.py", line 495, in subst
    val = str(env[var])
KeyError: 'TARGET_SNOWFLAKE_SCHEMA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/logging/output_logger.py", line 201, in redirect_logging
    yield
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/cli/elt.py", line 257, in _redirect_output
    yield
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/cli/elt.py", line 271, in _run_elt
    elt_context = context_builder.context()
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/elt_context.py", line 467, in context
    env.update(loader.env)
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/elt_context.py", line 77, in env
    return {**self.plugin.info_env, **self.config_env()}
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/elt_context.py", line 68, in config_env
    return self.settings_service.as_env(session=self.session, **kwargs)
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/settings_service.py", line 287, in as_env
    for _, config in self.config_with_metadata(*args, **kwargs).items():
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/settings_service.py", line 240, in config_with_metadata
    **kwargs,
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/settings_service.py", line 362, in get_with_metadata
    value, env=expandable_env, raise_if_missing=env_var_strict_mode
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/utils/__init__.py", line 511, in expand_env_vars
    return subst(fullmatch)
  File "/home/ec2-user/meltano/venv/lib64/python3.7/site-packages/meltano/core/utils/__init__.py", line 504, in subst
    raise EnvironmentVariableNotSetError(e.args[0])
meltano.core.utils.EnvironmentVariableNotSetError: ("Environment variable 'TARGET_SNOWFLAKE_SCHEMA' referenced but not set", 'Make sure the environment variable is set')
```

**Comment by qbatten** [comment]
It's possible that I'm just doing something wrong on my end, just ran into this at the very end of the workday and wanted to get it out there in case anyone else sees something similar. I can experiment a bit and add more detail later tonight/tomorrow.

**Comment by aaronsteers** [comment]
@qbatten - Thanks for logging this for us! The reason we made 'strict mode' an environment variable is exactly because we wanted folks to be able to turn if off if they ran into any issues (edge cases?) like the above. We'll dig in and let you know what we find.

**Comment by aaronsteers** [comment]
@qbatten - Strangely, I don't see the text `'TARGET_SNOWFLAKE_SCHEMA'` on this definition: https://github.com/meltano/hub/blob/main/_data/meltano/loaders/target-snowflake/transferwise.yml

Do you mind checking you have a lock file for this plugin locally, and if so, can you tell us if you see any references to `'TARGET_SNOWFLAKE_SCHEMA'` in the lock file or elsewhere in your project repo?

Thanks!

**Comment by qbatten** [comment]
Yeah it's pretty weird... I know that *used* to be a relevant env var, pre-migration to v2 (see [the migration guide](https://docs.meltano.com/guide/v2-migration#updating-your-project) > target_snowflake > transferwise).

I grepped for it and I do see it in the cached discovery.yml. There are two other places it appears, but I dont think they could be relevant: it's in logs and in the [readme for the plugin](https://github.com/transferwise/pipelinewise-target-snowflake/blob/aa6ac2e392b6148994f9138241630ba8d684adac/README.md?plain=1#L191)). Relevant result from grep: `./meltano-main/.meltano/cache/discovery.yml:  target_schema: $TARGET_SNOWFLAKE_SCHEMA`

Could it possibly be because of [this line](https://github.com/meltano/hub/blob/72ec44e6373aa44d4bc235932c30fd2963068bd7/_data/meltano/loaders/target-snowflake/transferwise.yml#L6) in the Meltano hub yaml file? I don't think that's it bc that should aiui translate to TARGET_SNOWFLAKE_TARGET_SCHEMA(?) under the new env var syntax for plugins, but just throwing it out there.

And just to describe the sequence of events that led to this:
- Was on Meltano v2.8 & pipelinewise/target-snowflake v2.2
- Ran `meltano upgrade` & `meltano install`, which upgraded me to meltano v2.10 and upgraded airflow files
- Started the scheduler again, `meltano invoke airflow scheduler`
- Jobs all failed w that error
- I tried setting MELTANO_FF_STRICT_ENV_VAR_MODE and I ... dont think that solved it, but it's possible I did something wrong here. At this point i just downgraded to v2.9 and that fixed it.

**Comment by qbatten** [comment]
Ok I just tried the upgrade again and it does seem like the feature flag env var is not being respected. Got the exact same error with the `MELTANO_FF_STRICT_ENV_VAR_MODE=False`

```
(venv) [ec2-user@ip-192-168-94-5 meltano-main]$ echo $MELTANO_FF_STRICT_ENV_VAR_MODE
False
```

**Comment by qbatten** [comment]
1. config dump & grep. 
```
(venv) [ec2-user@redact meltano-main]$ meltano config meltano | grep "strict_env_var_mode"
2022-11-17T17:24:06.807913Z [info     ] Environment 'prod' is active
    "strict_env_var_mode": false`
```

2. Wasn't able to get to this yet, I figured I'd post this for now anyway

3. It's not set in the .env file, nor in meltano.yml. Just queried the system DB and the `plugin_settings` table has 0 rows.

**Comment by qbatten** [comment]
I'm not messing around with this anymore; too messy and finicky to try again in prod. I'm just upgrading all our schedules from elt syntax to job syntax which should sidestep this issue (... if it is even a real issue)

We can close if you want

**Comment by qbatten** [comment]
Actually this problem does seem to be occurring with jobs too.

I worked around it by setting TARGET_SNOWFLAKE_SCHEMA in my dotenv file. The variable isn't actually used by pipelinewise/target-snowflake so it doesnt affect the schema written to.

Still not sure what the root cause is, but it is definitely still happening with `MELTANO_FF_STRICT_ENV_VAR_MODE=false` in dotenv. And I also confirmed that the way I'm setting it is indeed changing the config; When I set it to true, the output of `meltano config meltano | grep strict` does show it changing to true.

<details>
<summary>Here's a debug error printout (heavily redacted) that shows that strict_env_var_mode is indeed set to false, *and* that it's missing that env_var.</summary>

```

 [debug    ] Creating engine '<meltano.core.project.Project object at 0x12341234>@postgresql://xxxxxxxxxxx'
 [info     ] The default environment 'dev' will be ignored for `meltano schedule`. To configure a specific environment, please use the option `--environment=<environment name>`.
 [debug    ] Creating engine '<meltano.core.project.Project object at 12341234>@postgresql://xxxxxxxxxxxxx'
 [info     ] Environment 'dev' is active
 [debug    ] expanding job to tasks         job_name=job-xxxxxxxx-0 tasks=['xxxxxxxx-0', 'target-snowflake-xxxxxxxx']
 [debug    ] Encoding detection: ascii is most likely the one.
 [debug    ] Found plugin parent            parent=tap-postgres plugin=tap-postgres-xxxxxx source=discovery
 [debug    ] Found plugin parent            parent=tap-postgres-xxxxxxxx plugin=xxxxxxxx-0 source=inherited
 [debug    ] found plugin in cli invocation plugin_name=xxxxxxxx-0
 [debug    ] Found plugin parent            parent=target-snowflake plugin=target-snowflake source=discovery
 [debug    ] Found plugin parent            parent=target-snowflake plugin=target-snowflake-xxxxxxxx source=inherited
 [debug    ] found plugin in cli invocation plugin_name=target-snowflake-xxxxxxxx
 [debug    ] head of set is extractor as expected block=<meltano.core.plugin.project_plugin.ProjectPlugin object at 12341234>
 [debug    ] found block                    block_type=loaders index=1
 [debug    ] blocks                         idx=1 offset=0
 [debug    ] Environment variable 'TARGET_SNOWFLAKE_SCHEMA' referenced but not set. Make sure the environment variable is set. 
╭─────────────────────────────── [1;31mTraceback [1;2;31m(most recent call last) ────────────────────────────────╮
│ xxxxxxxxxxxxxxx/venv/lib64/python3.7/site-packages/meltano/core/utils/[1;33m__init__.py:49 │
│ 5 in subst                                                                                       │
│                                                                                                  │
│   492 │   │   try:                                                                               │
│   493 │   │   │   # the variable can be in either group                                          │
│   494 │   │   │   var = next(var for var in match.groups() if var)                               │
│ ❱ 495 │   │   │   val = str(env[var])                                                            │
│   496 │   │   │                                                                                  │
│   497 │   │   │   if not val:                                                                    │
│   498 │   │   │   │   logger.debug(f"Variable '${var}' is empty.")                               │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              env = {                                                                         │ │
│ │                    │   'MELTANO_FF_STRICT_ENV_VAR_MODE': 'false',                            │ │
│ │                    │   'MELTANO_DATABASE_URI':'postgresql:// xxxxxxxxxxxxxxxxxxxxxxxxxxxx    │ │
│ │                    │   ... +123                                                              │ │
│ │                    }                                                                         │ │
│ │            match = <[1;95mre.Match object; span=[1;39m(0, 24[1;39m), match='$TARGET_SNOWFLAKE_SCHEMA'>         │ │
│ │ raise_if_missing = 'false'                                                                   │ │
│ │              var = 'TARGET_SNOWFLAKE_SCHEMA'                                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[1;91mKeyError: 'TARGET_SNOWFLAKE_SCHEMA'

```

</details>

**Comment by nadiia-caspar** [comment]
Hey, is there any workaround for this?

I have updated Meltano from v2.6.0 to v2.11.0 and got the same errors in the ETL logs. The Airflow schedules are failing because of these errors, but if you trigger Meltano pipelines manually - it works.

**Comment by qbatten** [comment]
@nadiia-caspar What I'm doing right now is just setting the values it's complaining about. I set them to an arbitrary value since they aren't actually being used in the env I'm in.

**Comment by tayloramurphy** [comment]
@cjohnhanson do you have any updates on this issue? If it's a quick fix maybe we can get another engineer to fix it while you're on PTO.

**Comment by cjohnhanson** [comment]
@tayloramurphy no updates yet -- it's my top priority for this week though.

**Comment by cjohnhanson** [comment]
See https://github.com/meltano/meltano/issues/7291#issuecomment-1489442070 for root cause on why strict env var mode was being erroneously set in Airflow.
