### ISSUE TITLE
Make `ui` a Python package extra

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7006]
@z3z1ma pointed out that removing the UI libraries significantly decreases the size of the meltano install. 

It could impact our tests and might take a while to get right, but it probably is worth considering.

**Comment by peter-malcolm-bw** [comment]
I came here to open this issue as our CI failed during the install of one of the flask related packages required by the UI.

**Comment by WillDaSilva** [comment]
@peter-malcolm-bw The Meltano UI is currently deprecated, and is scheduled for removal in Meltano 3.0. I'm closing this issue as it is no longer relevant since the UI will be removed relatively soon, and because we do not intend to do additional work on/for the UI leading up to its removal.

**Comment by WillDaSilva** [comment]
Reopening because this isn't really an investment in the UI, but rather an investment in Meltano by getting the UI out of the way.

**Comment by rawwar** [comment]
I want to give this a shot. werkzeug gave me a really hard time when I included it in requirements.txt to be installed on MWAA. For almost a week, MWAA kept going down and no useful logs pointing to the conflict between versions of `werkzeug` of meltano and MWAA itself.

**Comment by edgarrmondragon** [comment]
The UI has been removed altogether in v3
