### ISSUE TITLE
bug: Integration tests failing on main

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7020]
### Meltano Version

N/A

### Python Version

NA

### Bug scope

Other

### Operating System

N/A

### Description

Example failures on `main`:
- https://github.com/meltano/meltano/actions/runs/3534445738
- https://github.com/meltano/meltano/actions/runs/3534480620

Example success on `release/2.10.0`:
- https://github.com/meltano/meltano/actions/runs/3534468951

Affects all integration tests, and may be responsible for failures in the Pytest workflow:
- https://github.com/meltano/meltano/actions/runs/3534001638/jobs/5930358463
- https://github.com/meltano/meltano/actions/runs/3534001638/jobs/5930359021
- https://github.com/meltano/meltano/actions/runs/3534001638/jobs/5930359587

**Comment by WillDaSilva** [comment]
I have not been able to reproduce this locally yet. Undoing the recent update to the `virtualenv` package had no effect.

**Comment by WillDaSilva** [comment]
Deleting the relevant caches from https://github.com/meltano/meltano/actions/caches also resulted in the tests failing.

**Comment by WillDaSilva** [comment]
I have reproduced the issue inside of a `ubuntu:20.04` Docker container.

**Comment by WillDaSilva** [comment]
The issue stems from running `pip install simplejson==3.11.1` within the plugins' venv.

**Comment by WillDaSilva** [comment]
Found the source of the problematic dependency: https://github.com/singer-io/singer-python/blob/2c053f4c5f468235bba85a203a252438b1b3c704/setup.py#L15

**Comment by edgarrmondragon** [comment]
> Found the source of the problematic dependency: [singer-io/singer-python@`2c053f4`/setup.py#L15](https://github.com/singer-io/singer-python/blob/2c053f4c5f468235bba85a203a252438b1b3c704/setup.py#L15)

Part of the reason we removed https://github.com/transferwise/pipelinewise-singer-python as a dependency in the sdk. It had the same issue of pinned dependencies in a library.

@WillDaSilva We used to pin `setuptools` because upgrades used to break installation of many packages, but we changed that recently: https://github.com/meltano/meltano/commit/91ec59ed0a45c09fc75b155c97aed3be49ad7103.

**Comment by WillDaSilva** [comment]
> We used to pin setuptools because upgrades used to break installation of many packages, but we changed that recently: https://github.com/meltano/meltano/commit/91ec59ed0a45c09fc75b155c97aed3be49ad7103.

That'll do it. I'll open a PR to re-add the pin as a short-term fix. Hopefully we can find a better approach for the long-term. Thanks @edgarrmondragon!
