### ISSUE TITLE
Use `flakeheaven` as a wrapper around `flake8`

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7039]
https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/integrations/flakeheaven.html

Flakeheaven allows us to establish a baseline when running Flake8 on the entirety of the Meltano repository. On subsequent runs it will only fail if we break a Flake8 rule that wasn't previously broken.

Currently we do something akin to this by only running `pre-commit` on changes files. This prevents us from using https://pre-commit.ci, since that is only able to run on the entire repository.

By using Flakeheaven (and its pre-commit hook) around Flake8 we can:
- Use https://pre-commit.ci instead of our custom `pre-commit` GitHub workflow.
- Progressively address Python lint issues in a granular way. We should no longer run into the problem of having to fix every lint issue in a (large) file just because we made a small change in it.

The Flakeheaven baseline file will need to be committed into the repository. I'm not yet sure how we/CI should update it.

**Comment by edgarrmondragon** [comment]
TIL folks were keeping `flakehell` alive 😅. [We removed it a while ago](https://gitlab.com/meltano/meltano/-/merge_requests/2458) because it was no longer being maintained. I'm glad some of the old maintainers are keeping a fork alive.

**Comment by aaronsteers** [comment]
🚀 

> This project is a fork of [FlakeHell](https://github.com/life4/flakehell). FlakeHell and other forks of it such as flakehell/flakehell are https://github.com/flakehell/flakehell/issues/25 and do not work with Flake8 4.0.x.
>
> FlakeHeaven works with Flake8 4.0.1 or greater. This fork will be https://github.com/flakeheaven/flakeheaven/discussions/1 that developed the existing forks.
