### ISSUE TITLE
bug: Docs still recommends ELT command

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7052]
I updated the title for this issue to make it more general, we still recommend the elt command a lot in the docs when run would be better.

- Replicate data - https://docs.meltano.com/guide/integration
- Orchestrate - https://docs.meltano.com/guide/orchestration
- Getting started guide - https://docs.meltano.com/getting-started/#schedule-pipelines-to-run-regularly
- etc.

Orignal description

> The getting started guide still recommends using the legacy extractor/loader/transform=skip syntax for scheduling pipelines.
> 
> https://docs.meltano.com/getting-started/#schedule-pipelines-to-run-regularly
> 
> The orchestrate data guide is updated to use job/task syntax https://docs.meltano.com/guide/orchestration.
> 
> Related to slack thread https://meltano.slack.com/archives/CMN8HELB0/p1670337451689919. We should update the GSG to use the new syntax because some users are getting confused with the mix of elt/run syntax.
> 

cc @sbalnojan

**Comment by tayloramurphy** [comment]
FYI @sbalnojan @afolson

**Comment by pnadolny13** [comment]
@tayloramurphy @sbalnojan I updated this issue because its more widespread than just the getting started guide. I think this is urgent from my view.

I would expect new users at this point to basically be unaware of the `elt` command because `run` is preferred. Maybe I'm wrong in that assumption. If I'm not then we should make the docs reflect it. It feels painful to see new users start their project with `elt`.

**Comment by sbalnojan** [comment]
@pnadolny13 @tayloramurphy Sadly I agree :-/ I keep on stumbling over a lot of people who think the elt command is the command to use meltano. And I'm having a hard time saying "please don't use that" because it's quite widespread.

**Comment by tayloramurphy** [comment]
@sbalnojan @pnadolny13 to be clear, we're not deprecating the `elt` command so it's not necessarily a bad thing that folks are using it. 

That said, we can likely reframe `elt` as useful for more advanced users as there are things you can do with `elt` that you can't do with `run`. (We've also talked about renaming this to just `el` in a future major release). So I'm supportive of reworking the docs to guide users to `meltano run` as it's broadly more powerful for ELT+. 

> It feels painful to see new users start their project with elt

Agreed - it should be on `run`. I just want us to be considered about how and where we talk about the `elt` command.

**Comment by pnadolny13** [comment]
@tayloramurphy yeah I like that framing, `meltano run` is the preferred flexible command by default but if you need some of the el specific features that arent supported by run then users can fall back to `elt`.

@sbalnojan I can explore a bit more but I linked most of the main ones I saw in the description of this issue https://github.com/meltano/meltano/issues/7052#issue-1479390640.

**Comment by sbalnojan** [comment]
Ok so let's make this concrete, based on the data I would suggest a reasonable action is to:

1. Get rid of all meltano ELT in the getting started complete guide (that's just a small task, it's only mentioned on the sidelines)
2. Rewriting the Replicate Data piece to completely meltano run only.
3. Removing the meltano elt mentions inside the Orchestrate Guide.

That's very much the 20% for 80% of the benefit. 

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/43072233/214565367-88a63d09-7a07-4797-b7b4-13ee24a7948d.png">

**Comment by sbalnojan** [comment]
@pnadolny13 @afolson @tayloramurphy  I've provided a PR.

**Comment by pnadolny13** [comment]
@sbalnojan yeah good point the complete tutorial is mostly converted. I'd say this section where we recommend the elt-esque scheduling syntax is probably the only thing we'd probably want to update https://docs.meltano.com/getting-started/#schedule-pipelines-to-run-regularly.

**Comment by sbalnojan** [comment]
@pnadolny13 good point, that part I didn't find by looking for "meltano elt" :-D

**Comment by pnadolny13** [comment]
Closed by https://github.com/meltano/meltano/pull/7301
