### ISSUE TITLE
Add deprecation warning to `meltano ui` command

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7075]
Meltano UI is deprecated, and is scheduled for removal in Meltano v3. We should make that known to all who currently use the UI by printing a clear warning message when they run `meltano ui` that states that:
- it is *currently* deprecated
- it will be removed in Meltano v3

Relates to https://github.com/meltano/internal-general/discussions/460

Migration strategies likely fall outside the scope of this issue. From a chat with @aaronsteers on 2022-12-12 the priority will be providing feature-parity with equal-or-better UX via the CLI.

A UI as part of Meltano Cloud (possibly accessible after `meltano login` even if not running workloads on Meltano Cloud) may be available in the future for users who absolutely love UIs and have no interest in moving away from the Meltano UI to the CLI, but that's more or less entirely unplanned, so no promises at this point.

Because we cannot make promises about what we'll be doing to replace the UI, at this point I recommend we keep the deprecation warning minimal and fact-based. Doing so may lead to users asking (many) questions about the impending removal on Slack. This will be a good opportunity for us to discuss with them to figure out what the best path forward will be, i.e. we can ask them why they like the UI, if they'd be happy with the CLI, etc.

Once we've got a more concrete idea for what comes next (and likely after it has been implemented and released), we can update the deprecation warning to advertise it.

@sbalnojan @afolson @tayloramurphy

**Comment by tayloramurphy** [comment]
Love this - thanks for opening and taking @WillDaSilva
