### ISSUE TITLE
Feature request: Support `meltano init` in non-empty directory

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7077]
Follows from

- https://github.com/meltano/meltano/pull/6814, 

which was authored by @ReubenFrankel and which allows `meltano init` to target existing (empty) directories.

This new feature would _also_ add support for non-empty directories.

Safety considerations:

If the operation would overwrite any critical project files such as `meltano.yml`, then the `init` operation should fail _before_ beginning any file or directory write operations. (Aka, it should not fail mid-operation.)

Optionally, a `--force` option could be utilized to bypass checks and simply write all files and overwrite existing directory contents.

## Handling `.gitkeep` files

When we check for meltano init safety, we probably want to ignore the presence of .gitkeep files and directories themselves. The argument goes that, while adding a new meltano project to an existing repo would not have those conflicts, the tutorial use cases will have those conflicts.

In order to streamline tutorial use cases, we would not want the user (or the tutorial maintainer) to have to first delete all the .gitkeep files before they are able to run or re-run meltano init.

**Comment by aaronsteers** [comment]
When we check for `meltano init` safety, we probably want to _ignore_ the presence of `.gitkeep` files and directories themselves. The argument goes that, while adding a new meltano project to an existing repo would _not_ have those conflicts, the tutorial use cases _will_ have those conflicts.

In order to streamline tutorial use cases, we would not want the user (or the tutorial maintainer) to have to first delete all the `.gitkeep` files before they are able to run or re-run `meltano init`.

**Comment by aaronsteers** [comment]
> > the tutorial use cases will have those conflicts.
> 
> @aaronsteers If the `<plugin type>/.gitkeep` files are present, maybe tutorial repos could have a `meltano.yml` already present too, so I'm curious

Yes. I thought of this too. Currently, @sbalnojan's walkthrough tutorial _does_ run `meltano init`, so I assume it is valuable to do so. Mainly, I think the goal is to give the user a 'feel' for the flow of how to start their project, while not starting them _entirely_ from scratch.

> * what would `meltano init` accomplish in those cases?

It generates the boilerplate `meltano.yml` file.

> * do we want to _fail_ the init operation if `meltano.yml` is present?

Good question. I think we could make a good case either way: either allow `--force` to override an existing `meltano.yml` or else make `meltano.yml` the one file that `--force` will not overwrite. (Instead, we'd ask you to delete it first if that's really what you want to do.)

**Comment by edgarrmondragon** [comment]
> Good question. I think we could make a good case either way: either allow `--force` to override an existing `meltano.yml` or else make `meltano.yml` the one file that `--force` will not overwrite. (Instead, we'd ask you to delete it first if that's really what you want to do.)

@aaronsteers that makes sense. Poetry does a similar thing

```console
$ poetry init
A pyproject.toml file with a poetry section already exists.
```

Meltano would have a `--force` flag to override it in that case.
