### ISSUE TITLE
Feature: Add type hint during `meltano config set --interactive`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7082]
_Originally posted by @menzenski in https://github.com/meltano/meltano/issues/7080#issuecomment-1349163293_

Some other thoughts: while the JSON schema does indicate that this field is a string, not an int (`'view_id': {'type': ['string'], 'description': 'Google Analytics View ID'}`), the type isn't indicated when it's set interactively:

![Screen Shot 2022-12-13 at 11 22 04 AM](https://user-images.githubusercontent.com/4371752/207401566-10205be8-33fb-4629-b8d9-286267362784.png)

And if I enter nine digits `123123123`, it's not coerced to a string. The correct thing for me to do is to enter it with quotes `'123123123'` here but that's not obvious.

**Comment by WillDaSilva** [comment]
Still relevant

**Comment by edgarrmondragon** [comment]
> And if I enter nine digits `123123123`, it's not coerced to a string. The correct thing for me to do is to enter it with quotes `'123123123'` here but that's not obvious.

I can't reproduce this behavior. Inputting an integer value for a setting of `kind` string stores the quoted value in `meltano.yml`. A setting without `kind` also works since the default is string.
