### ISSUE TITLE
bug: Tutorial Part 2 broken for Python 3.10

### ISSUE THREAD

**Issue by sbalnojan** [meltano/meltano#7087]
The loading part of the tutorial currently uses target-postgres. That defaults to the transferwise variant. And that one (as of now) is broken for Python 3.10, 3.11. The issue has been fixed October, but no new wheel has been built. 

I am unsure on how to best fix the tutorial @aaronsteers @tayloramurphy @pnadolny13 @visch, your thoughts?

I'm really tempted to not go out of the meltano context (ever) again for the tutorial. That would mean using our target-postgres as well.

**Comment by tayloramurphy** [comment]
@sbalnojan seems like we have a few options:

* indicate at the start of the tutorial that this only works with 3.9 currently. 
* build a codespace just for the tutorial and have them work through that - still keep it scoped to 3.9
* I see in the extractor setting that we already have introduced the `--variant` flag, so we could just do that for the target as well and use the meltanolabs variant

We'll need to separately figure out acceptance criteria to make the meltanolabs variant the default, but I haven't made it a priority to dig into that yet.

**Comment by pnadolny13** [comment]
@sbalnojan two things come to mind for this:

- Short term we can update [the hub definition](https://github.com/meltano/hub/blob/aa5240a09cae37b59e316e21941f108a6ed9e9ef/_data/meltano/loaders/target-postgres/transferwise.yml#L11) to use the git url and pin the commit hash of the bug fix that they havent released yet.
- Long term option 1 - ideally we'd get meltanolabs variant cleaned up enough to be default for target-postgres
- Long term option 2 -  it might be better to switch to a more tutorial-like set of plugins with less dependency friction. I suggested sqlite in this discussion https://github.com/meltano/meltano/discussions/6950. duckdb seems the most relevant lightweight db right now, although I cant speak to the maturity/stability of those plugins (tap/target/dbt duckdb) as of today. It unclear if theyre ready for the lime light or not.

**Comment by sbalnojan** [comment]
@pnadolny13 thanks for these suggestions!

I played around with @visch with a few options as well. And I'm 100% positive I don't want to leave the meltanolabs comfort ever for the tutorial :-D So I'm not at all comfortable with duckdb for the codespaces demo right now.

I think the ideal structure would be the following:

1. Super Quick Tutorial = Current Codespaces tutorial (having a few helper functions and stuff to speed up things)
2. Tutorial (the one we have right now), complemented by a possible codespace (but not necessarily), offering short cuts (not mandatory!) - this would e.g. launch a postgres with a one liner https://github.com/sbalnojan/meltano-tutorial. 

So what I'm now doing is to first convert the tutorial over to Meltanolabs based taps and targets. (the accompanying GitHub repository already has a small set of tests)

Thanks to @visch for fixing the target and showing me that this is quite straight forward.

**Comment by sbalnojan** [comment]
Tutorial converted.
