### ISSUE TITLE
`ARG MELTANO_PROJECT_ROOT=workspaces` in a Dockerfile causes `RUN meltano install` to fail

### ISSUE THREAD

**Issue by seajhawk** [meltano/meltano#7106]
### Meltano Version

2.11.0

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

FROM python:3.9 (Docker image)

### Description

Slack thread: https://meltano.slack.com/archives/CQUDGG7U2/p1671281603158709?thread_ts=1671114633.969079&cid=CQUDGG7U2

ok, this one is a bit crazy - re-adding my own code step-by-step to the Dockerfile I ran into one line that causes `RUN meltano install` to fail.

drum roll please....

`ARG MELTANO_PROJECT_ROOT=workspaces`

And the problem is the arg name, not the value.

In the following Dockerfile, if I enable the arg it will fail, but disabled the `meltano install` command works.
```
FROM python:3.9

WORKDIR /workspaces/vs

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
  gcc \
  g++ \
  git \
  make \
  python3-dev \
  python3-venv \
  unzip \
  wget \
  && rm -rf /var/lib/apt/lists/* \
  && pip install --no-cache-dir meltano==2.10.0

COPY meltano.yml ./ 

# ARG MELTANO_PROJECT_ROOT=workspaces

RUN meltano --environment=docker install
```

I thought perhaps there was a conflict with an env var used by meltano, or some other variable name, but I can't find it on github.
So, this feels like a bug, but I've got no idea what's causing it yet.

Here is the contents of my `meltano.yml` file
```
version: 1
default_environment: docker
project_id: efd9f8fe-81a0-4972-a1d0-de76d13fbefd
environments:
- name: dev
- name: staging
- name: prod
- name: docker
```

**Comment by WillDaSilva** [comment]
Hi @seajhawk. I do not believe this is a bug, so I am closing this issue. Please let me know if you would like it to be reopened.

Per convention, environment variables prefixed with `MELTANO_` are reserved for use by Meltano.

In this case, `MELTANO_PROJECT_ROOT` sets the path which Meltano will use as the project root, which should contain `meltano.yml` and `.meltano/`.

You have it set to the relative path `workspaces`, and your current directory is `/workspaces/vs`, so Meltano is trying to use `/workspaces/vs/workspaces/` as its project root, which explains the failure during `meltano install`.

You should either set `MELTANO_PROJECT_ROOT` to the directory with your `meltano.yml` file (i.e. `/workspaces/vs/`), or avoid setting that environment variable.

**Comment by seajhawk** [comment]
@WillDaSilva - I agree.

After working around it, I stumbled across a doc that showed use of MELTANO_PROJECT_ROOT.

I didn't realize that MELTANO_* was reserved, but that's good to know!

Thanks for looking into it and Merry Christmas!

Chris
