### ISSUE TITLE
bug: Error: Setting value set via multiple environment Azure connection string (state backend).

### ISSUE THREAD

**Issue by JulesHuisman** [meltano/meltano#7118]
### Meltano Version

2.12.0

### Python Version

3.10

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Linux - Ubuntu 20.04

### Description

I am running into the same issue as #7059, but with the Azure connection string. 

I solved the issue when running the Meltano cli. However, the issue came back when I tried to run the Dagster utility. 

### Code

```python
Error: Setting value set via multiple environment variables: ['MELTANO_STATE_BACKEND_AZURE_CONNECTION_STRING', 'AZURE_STORAGE_CONNECTION_STRING']
```

**Comment by tayloramurphy** [comment]
@cjohnhanson this seems like it'd have a similar solve as the previous issue, right?

**Comment by cjohnhanson** [comment]
@tayloramurphy seems likely. I'll double-check the client libraries to confirm that they'll default to the relevant env vars when not explicitly provided and then go ahead and un-alias the GCP env vars as well to head off any such issues with that backend.

**Comment by cjohnhanson** [comment]
Closed by https://github.com/meltano/meltano/pull/7174
