### ISSUE TITLE
bug: Unclear error message `argument after ** must be a mapping` after `pip install meltano`

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7147]
### Meltano Version

2.11.1

### Python Version

3.10

### Bug scope

Other

### Operating System

macOS M1 ARM

### Description

Originally raised on Slack:

Reproduction steps from a clean venv on macOS M1 ARM using Python 3.10.9:
```
pip install meltano
git clone https://github.com/aaronsteers/aj-dataops-personal demo
cd demo 
meltano invoke tap-rickandmorty --help
```

Error message:
```
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

meltano.core.task_sets.TaskSets() argument after ** must be a mapping, not str
```

Meltano should not be installed via `pip install`, but ideally it would work anyway. Even if it doesn't work, the error message should be more clear that this.

**Comment by WillDaSilva** [comment]
Result of `pip freeze`, to aid with reproduction: 

```
aiodocker==0.21.0
aiohttp==3.8.3
aiosignal==1.3.1
alembic==1.9.1
aniso8601==9.0.1
anyio==3.6.2
asgiref==3.6.0
async-timeout==4.0.2
atomicwrites==1.4.1
attrs==22.2.0
Authlib==1.2.0
Babel==2.11.0
backoff==2.2.1
bcrypt==3.2.2
blinker==1.5
cached-property==1.5.2
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
click-default-group==1.2.2
commonmark==0.9.1
croniter==1.3.8
cryptography==39.0.0
dnspython==2.2.1
email-validator==1.3.0
fasteners==0.17.3
Flask==2.1.3
Flask-BabelEx==0.9.4
Flask-Cors==3.0.10
Flask-Executor==0.10.0
Flask-Login==0.6.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-RESTful==0.3.9
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.0.1
flatten-dict==0.4.2
frozenlist==1.3.3
gunicorn==20.1.0
h11==0.14.0
httptools==0.5.0
idna==3.4
itsdangerous==2.1.2
Jinja2==3.1.2
jsonschema==4.17.3
Mako==1.2.4
MarkupSafe==2.1.1
meltano==2.12.0
meltano-flask-security==0.1.0
multidict==6.0.4
packaging==21.3
passlib==1.7.4
psutil==5.9.4
psycopg2-binary==2.9.5
pycparser==2.21
Pygments==2.14.0
pyhumps==3.8.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-dotenv==0.20.0
python-gitlab==3.12.0
pytz==2022.7
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
requests==2.28.1
requests-toolbelt==0.10.1
rich==12.6.0
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
six==1.16.0
smart-open==6.3.0
smtpapi==0.4.12
sniffio==1.3.0
snowplow-tracker==0.10.0
speaklater==1.3
SQLAlchemy==1.4.46
structlog==21.5.0
typing_extensions==4.4.0
tzdata==2022.7
tzlocal==4.2
urllib3==1.26.13
uvicorn==0.17.6
uvloop==0.17.0
watchgod==0.8.2
websockets==10.4
Werkzeug==2.1.2
WTForms==3.0.1
yarl==1.8.2
```

**Comment by archiewood** [comment]
It's interesting you say meltano should not be installed via `pip install`

I think the page on your docs I was following recommended it?

https://docs.meltano.com/getting-started/installation

**Comment by tayloramurphy** [comment]
@WillDaSilva can you add more context to "not being installed with pip"? I think @sbalnojan wanted to have pip in there since it's the quickest way to get it installed - are you saying it's not ideal for production deployments? How do you think we should update the docs?

**Comment by sbalnojan** [comment]
I think @WillDaSilva already caught the gist of it. Meltano can be installed via pip, and thus it will be installed via pip the majority of time, no matter what we do.

So ideally, pip installs should work out of the box. And clean environments don't really have anything to do with pip IMHO. 

But, I think we did decide in another issue to switch the language over to recommend pipx out of the box, even for first time installs. (@visch, that just hasn't happened yet - haven't had time yet). 

@archiewood thanks for pointing this out!

**Comment by WillDaSilva** [comment]
@archiewood Thank you for pointing that out. We may want to update those docs to explain that if `pip` is going to be used, it should be installed into a virtual environment. Additionally, we may want to recommend `pipx` ahead of `pip`, and briefly explain why.

@sbalnojan I agree with everything you've said above.

@tayloramurphy The issue is not `pip` specifically (i.e. Meltano can be installed properly using `pip`), but `pip` doesn't enforce the use of a clean environment (unlike `pipx` and Docker), and `pip` also doesn't make reproducibility particularly easy (unlike Docker).

I eagerly await the day when a PEP that permits Python applications to be packaged into wheels that automatically install into a clean environment with locked dependencies.

**Comment by WillDaSilva** [comment]
Looks like the issue is because of a malformed `jobs` field in `meltano.yml`:

```
jobs:
  build:
  - - tap-rickandmorty target-bigquery
    - tap-strava target-bigquery
    - tap-spotify target-bigquery
  - dbt-bigquery:run
  - dbt-bigquery:test
  - evidence:build
```

Since #7148 adds schema validation for `meltano.yml`, and would print warnings that clearly highlight the problem, I'm going to close this issue once it has been merged.
