### ISSUE TITLE
feature: Getting Started Tutorial Guided Walkthrough

### ISSUE THREAD

**Issue by sbalnojan** [meltano/meltano#7149]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

**Problem:**
When I (= first time meltano user) try meltano for the first time, I would like to have a "meltano tutorial/getting started" command so that my experience is a close to the real thing as possible. 

**Context:**
- Ideally, my meltano getting-started command runs on my local desktop as well as inside codespaces
- related discussion: https://github.com/meltano/meltano-codespace-ready/issues/3
- it should be "externally sourced" enough that we can fix bugs quickly (say it should start with a call to get the most recent getting-started init script)
- it could provide prompts along the way after running each command (like after meltano init, it should tell me to now do step 2,..., or after changing a line inside the YAML file, it should tell me to now head to step 3).

@tayloramurphy @aaronsteers

**Comment by tayloramurphy** [comment]
@sbalnojan I think I'm having trouble understanding what you're asking for here. Are you wanting a new command that when a user runs it they'll be told what commands to run next? Could you mockup what you're thinking from the a UX standpoint?

**Comment by sbalnojan** [comment]
@tayloramurphy Yeah, so what I could imagine could work differently when I'm in one of the main starting places for Meltano:

1. When I'm NOT inside codespaces but on my local laptop: 

```
$ meltano get-started-guide
> .... Welcome to Meltano! This is your first time firing up Meltano? Then you're at the right place.
.... downloading ...github.com/meltano/get-started-guide to this directory....
.... you're now getting supplied with a few resources that will make learning Meltano really fast!
 ... placing: 
data/customers.csv README.md meltano.yml
.... Nice! 
... Step 0: To learn what you're going to build here Take a look into data/customers.csv and then run "meltano run tap-csv hide-ips target-duckdb".
$ ...meltano run tap-csv ... 
> [...]
> Nice work! Take a look into your target with your favourite editor, or use the helper function ....
> Step 1: ...
```

2. When I'm  inside codespaces: I think I want to be able to replace all the calls I currently am doing to helper functions with one call to meltano get-started-guide. 

Maybe its a terrible idea, I kind of liked CLI based walkthroughs especially when they help to replace "copy this, do that,..." kind of instructions with helper functionality and have prompts inside the CLI.

**Comment by tayloramurphy** [comment]
@sbalnojan interesting... this seems like a fairly big lift and I'm not _really_ sure how we'd do it. 

That said - this makes me think of a self-guided onboarding to Meltano Cloud and we may need something like this for new users generally 🤔

**Comment by tayloramurphy** [comment]
Still relevant but not a high priority.
