### ISSUE TITLE
Bug: Missing error message detail in Tutorial project when adding non-existent plugin ref

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7154]
Missing error message detail here. My assumption is that 'tap-smoke-test' doesn't exist, but I don't get any explanation of the failure.

```
root@codespaces-dc72ab:/workspaces/meltano-codespace-ready# meltano add extractor tap-smoke-test
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

```

This can be reproed by launching the Codespace demo from meltano.com and then running this as first step.

**Comment by aaronsteers** [comment]
I noticed the project has a mostly-empty `meltano.yml` file. Not clear as of yet if the error is due to what I'd expect (missing plugin name) or if it's something to do with the present-but-not-yet-valid `meltano.yml` file. Tomorrow we'll get 

- #7077 

released and then it would probably be worth revisiting the initialization process on that tutorial project.

**Comment by WillDaSilva** [comment]
Could not reproduce. I assume this has been fixed.
