### ISSUE TITLE
feature: Allow S3 state backend to accept additional credentials

### ISSUE THREAD

**Issue by psaini-qontigo** [meltano/meltano#7158]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

Currently the S3 state backend only accepts `aws_access_key_id` and `aws_secret_access_key`. There are additional types of authentication already supported by boto3, and it would be nice to allow the `S3StateStoreManager` class to accept these authentication.

1. Temporary security credentials (AWS STS)
2. AWS profile
3. Instance profiles

**Comment by pankajsaini-wr** [comment]
[Here](https://github.com/transferwise/pipelinewise-target-redshift/pull/31) is a related PR in [pipelinewise-target-redshift](https://github.com/transferwise/pipelinewise-target-redshift) to enable these authentication methods. 

I have tried some changes in my local, and they seem to work well with these additional authentication methods. I am happy to make a contribution.

**Comment by tayloramurphy** [comment]
@pankajsaini-wr we'd love a PR if you're willing to contribute!

**Comment by edgarrmondragon** [comment]
I think this is already supported:

https://github.com/meltano/meltano/blob/6a3708be20e81948d954c134d01be74e0dd14f30/src/meltano/core/state_store/s3.py#L108-L123

**Comment by psaini-qontigo** [comment]
> I think this is already supported:
> 
> https://github.com/meltano/meltano/blob/6a3708be20e81948d954c134d01be74e0dd14f30/src/meltano/core/state_store/s3.py#L108-L123

I think the S3 state store only supports aws_access_key_id and aws_secret_access_key, and it fails if they are not supplied. I think we should also include aws_session_token, aws_profile and also [instance profiles](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html).

**Comment by WillDaSilva** [comment]
@psaini-qontigo Looking at the linked section of code, if neither `aws_secret_access_key` and `aws_access_key_id` are provided we create a boto3 session without providing any parameters, which lets boto3 check for all of the different ways it can be configured. That should include setting the `AWS_SESSION_TOKEN` environment variable, among other things.

With that in mind, do you believe there is still an issue with this?
