### ISSUE TITLE
bug: Secrets leak in logs if `asyncio.create_subprocess_exec()` fails (or if log-level=debug)

### ISSUE THREAD

**Issue by visch** [meltano/meltano#7167]
### Meltano Version

2.13.0

### Python Version

3.8

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Ubuntu

### Description

Meltano failed for me in production and during the printing of the huge line of stack traces (Which most of the traces are pretty useless to me while I"m in "user mode" unless I"m running in debug mode).

Ideally envs wouldn't print out. I was running `meltano run dashboard` which is a job name

```
 /venv/lib/python3.9/site-packages/meltano/core/plugin_invoker.py:453 in      │
│ invoke_async                                                                 │
│                                                                              │
│   450 │   │   │   popen_options,                                             │
│   451 │   │   │   popen_env,                                                 │
│   452 │   │   ):                                                             │
│ ❱ 453 │   │   │   return await asyncio.create_subprocess_exec(               │
│   454 │   │   │   │   *popen_args,                                           │
│   455 │   │   │   │   **popen_options,                                       │
│   456 │   │   │   │   env=popen_env,                                         │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │          args = ('--discover',)                                          │ │
│ │        kwargs = {                                                        │ │
│ │                 │   'stdout': -1,                                        │ │
│ │                 │   'stderr': -1,                                        │ │
│ │                 │   'universal_newlines': False                          │ │
│ │                 }                                                        │ │
│ │    popen_args = [                                                        │ │
│ │                 │                                                        │ │
│ │                 '/builds/autoidm/prodder/.meltano/extractors/tap-gmail/… │ │
│ │                 │   '--config',                                          │ │
│ │                 │                                                        │ │
│ │                 '/builds/autoidm/prodder/.meltano/run/tap-gmail/tap.c25… │ │
│ │                 │   '--discover'                                         │ │
│ │                 ]                                                        │ │
│ │     popen_env = {                                                        │ │
│ │                 │                                                        │ │
│ │                 'TAP_GMAIL_PERSONAL_OAUTH_CREDENTIALS_REFRESH_TOKEN':    │ │
│ │                 'refreshtoken_listd_here… │ │
│ │                 │   'TAP_GMAIL_USER_ID': 'me',                           │ │
│ │                 │   'CI_PROJECT_NAMESPACE': 'autoidm',                   │ │
│ │                 │   'GITLAB_USER_ID': 'userid',                         │ │
│ │                 │   'CI_RUNNER_VERSION': '15.6.0~beta.186.ga889181a',    │ │
│ │                 │   'FF_SKIP_NOOP_BUILD_STAGES': 'true',                 │ │
│ │                 │   'CI_SERVER_NAME': 'GitLab',                          │ │
│ │                 │   'CI_RUNNER_DESCRIPTION':                             │ │
│ │                 '2-blue.shared.runners-manager.gitlab.com/default',      │ │
│ │                 │   'GITLAB_USER_EMAIL': 'dvisch@autoidm.com',           │ │
│ │                 │   'CI_SERVER_REVISION': 'fd1954e655c',   
```

**Comment by menzenski** [comment]
I've noticed this as well. It'd be preferable to have the value of environment variables excluded from logs. If I'm running locally it's not the end of the world, but this is enough to keep me from enabling debug logging in a remote execution environment.

**Comment by visch** [comment]
> I've noticed this as well. It'd be preferable to have the value of environment variables excluded from logs. If I'm running locally it's not the end of the world, but this is enough to keep me from enabling debug logging in a remote execution environment.

I'm also not running with debug logging in this scenario so it impacts me in prod :/

**Comment by aaronsteers** [comment]
@visch - Thanks for logging. I've updated this issue description to exactly describe this exception point.

@visch and @menzenski, if either of you find similar cases, I do appreciate you logging them.

I've marked with as `security` tag, urgency `High` and weight `2` (very small).

The preferred handling here would be to make this a Meltano-handled error (subclassed from `MeltanoError`), with a custom error message that does not print the details of env vars.

**Comment by aaronsteers** [comment]
Related:

- https://github.com/meltano/meltano/issues/7184

**Comment by edgarrmondragon** [comment]
@aaronsteers I think https://github.com/meltano/meltano/issues/7184 is not a dupe

- `asyncio.create_subprocess_exec()`: env vars are leaked as part of the `env=popen_env` argument passed to the function
- debug logs: this is logged explicitly in https://github.com/meltano/meltano/blob/a13651fd7165c438d7093e5b58ac0fef3a3e8902/src/meltano/core/plugin_invoker.py#L429

**Comment by aaronsteers** [comment]
@edgarrmondragon - Got it! Thanks for checking - and confirming. 👍
