### ISSUE TITLE
feat: add meltano version when `Env` dict is output

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#7183]
We put a lot of info in the Env dictionary when running with `log-level=debug`. That should include the meltano version!

**Comment by tayloramurphy** [comment]
Still relevant I believe

**Comment by edgarrmondragon** [comment]
@tayloramurphy We stopped logging the the Env dictionary in https://github.com/meltano/meltano/pull/7212 so that probably leaves this as a duplicate of https://github.com/meltano/meltano/issues/6939

**Comment by tayloramurphy** [comment]
Duplicate of https://github.com/meltano/meltano/issues/6939

**Comment by tayloramurphy** [comment]
Thanks for the cross-link @edgarrmondragon !
