### ISSUE TITLE
feature: Add Meltano command information to Hub API request

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#7185]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

When Meltano sends requests to the Hub API, currently sets the `X-Project-ID` and `User-Agent` headers: https://github.com/meltano/meltano/blob/193a3ae4c7adfa29e102a65d31b7e865d9eea349/src/meltano/core/hub/client.py#L113-L125

However, it'd be good to include the CLI command where the request is coming from.

**Comment by tayloramurphy** [comment]
I'd like to see this done relatively soon as this was part of the original scope in https://github.com/meltano/internal-general/issues/444

**Comment by edgarrmondragon** [comment]
@tayloramurphy I overlooked the file yesterday, the Meltano version should already be available in the user-agent, e.g. `User-Agent: Meltano/2.13.0`

**Comment by pnadolny13** [comment]
@edgarrmondragon I was about to cross post https://github.com/meltano/internal-data/issues/68#issuecomment-1387343286, I noticed thee same thing. Version does come through, as long as we can confirm that its a reliable way to get it.
