### ISSUE TITLE
docs: recommend utility EDK plugins over transformer/orchestrators

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7186]
We still recommend the transformers/orchestrators plugins over the sibling utilities using the EDK. If we want people to migrate to the new recommendation we need the docs to reflect it. New projects should all be on the EDK utilities to avoid having to eventually do a migration. Superset is already using the EDK utility but the others are not updated.

- [ ] https://docs.meltano.com/getting-started/part3
- [x] https://docs.meltano.com/guide/transformation
- [x] https://docs.meltano.com/guide/orchestration

Theres also this related [hub issue](https://github.com/meltano/hub/issues/1115) to hide the legacy plugins and make the EDK the recommendation.

cc @sbalnojan @tayloramurphy

**Comment by tayloramurphy** [comment]
@aaronsteers any concerns around this? This elevates the support requirements around the EDK for these plugins.

**Comment by edgarrmondragon** [comment]
@tayloramurphy fwiw the EDK already seems somewhat critical. Yesterday https://github.com/matsonj/nba-monte-carlo was broken because of an EDK bug.

**Comment by tayloramurphy** [comment]
@edgarrmondragon agreed - my goal is to get clear alignment on the urgency around the EDK

**Comment by pnadolny13** [comment]
@tayloramurphy @edgarrmondragon the squared project was also broken yesterday and I wasnt able to run locally either for the whole day (btw thanks for fixing Edgar, I'm not complaining 😅 but want to make sure we understand the impact to users). This is actually why I opened this issue because I was confused why we didn't have more complaints yesterday, after looking at the data I realized most users are still on transformers so they weren't impacted.

**Comment by aaronsteers** [comment]
I opened the issue today to pin to a specific published EDK version. We should definitely prioritize that on all edk-based plugins first. That would address/prevent the above-mentioned breakages in future.

Perhaps there are other things we'd want to prioritize also, but that version pinning would be first.

**Comment by pnadolny13** [comment]
@sbalnojan this is basically done other than updating the part 3 transformation sections of the getting started guide. Would you be able to refresh that section?

**Comment by sbalnojan** [comment]
@pnadolny13 I'm on it. https://github.com/meltano/meltano/pull/7619
