### ISSUE TITLE
feature: Documentation on how to debug with Meltano

### ISSUE THREAD

**Issue by LukePammant** [meltano/meltano#7191]
### Feature scope

Other

### Description

I'm trying to figure out why Meltano isn't passing the state into my ELT pipeline. I've followed the documentation on [how to debug a custom extractor](https://docs.meltano.com/guide/debugging-custom-extractor) but since it's running the tap.py directly I'm unable debug Meltano's state management. 

### The ask:

It would be great to have a guide or video on how to debug an ELT pipeline in VS Code so I can see all the parts working together.

### My current troubleshooting steps: 

I can see that the state is correct via: `meltano --environment prod state get daily-ga-lcp-load`

But when I run the ELT and log `self.state` from the tap I get an empty object. This is the command I'm running: `meltano --environment prod elt --state-id daily-ga-lcp-load tap-ga--report-lcp target-postgres --transform run`

**Comment by visch** [comment]
Here's how I do it, maybe some have better ways. 

How to debug a tap with state that you've been running with Meltano. 

1. First find the state value you want to use, `meltano state list` 
2. Send the state to a file `meltano state get {state_name} > state.json` state_name is from the list comand above
3. Open the `state.json` file and remove the "singer_state" object that wraps everything. ie you'll get something like

```
{"singer_state": {"bookmarks": {"conversation": {}, "message": {}}}}
```

We want it to be 
```
{"bookmarks": {"conversation": {}, "message": {}}}
```

Save the state.json file. 
4. Generate the config  the tap. `meltano invoke --dump=config tap-name > config.json` 
5. Generate the catalog the tap. `meltano invoke --dump=catalog tap-name > catalog.json
6. Pass the state.json file into the tap directly, `tap-name --config config.json --state state.json --catalog catalog.json`

Because this only takes me a minute or so and I do it infrequently I don't mind the steps 🤷

**Comment by LukePammant** [comment]
Thank you @visch that was helpful! This thread can serve as documentation for anyone stuck like I was :)

I managed to debug it with the state that I exported using your steps and everything works fine. What's strange is that when running it using the ELT pipeline the state doesn't seem to make it into the extractor. Any ideas on this?

**Comment by visch** [comment]
> Thank you @visch that was helpful! This thread can serve as documentation for anyone stuck like I was :)
> 
> I managed to debug it with the state that I exported using your steps and everything works fine. What's strange is that when running it using the ELT pipeline the state doesn't seem to make it into the extractor. Any ideas on this?

If you could share your meltani.yml, my guess is that the tap doesn't have state added as a capability. Hard to know this one, I'm not sure of a good solution to make users aware that this is the case.

**Comment by LukePammant** [comment]
> If you could share your meltani.yml, my guess is that the tap doesn't have state added as a capability.

What's strange is that it _saves_ to the state just fine. I see `Incremental state has been updated at 2023-01-21 23:01:06.418219.` in the logs and using `meltano state get` returns:

```
{"singer_state": {"bookmarks": {"LCP_1500_2000_66350024": {"testing": "20230120", "replication_key": "ga_date", "replication_key_value": "20230120"}}}}
```

 Would this mean the state capability is detected fine? It just seems to have trouble fetching the state and giving it to my tap.

**Comment by LukePammant** [comment]
Hi @visch - I'm curious if you have any other insights on this. I'm still running into the issue where the state passed into the tap/streams is empty. 

I can see that the tap's capabilities include "state" if I log out the `self.capabilities` (I'm using the Meltano SDK). I also see that the stream/tap is _writing_ to the state table in Postgres so it appears to have the correct db settings and is able to access the database.

When I run the tap directly and pass in the `--state state.json` I can see that it works fine so I don't believe it is an issue with my tap code.

It only appears to be when running via meltano with `meltano invoke my-tap --state-id my-id`, or `meltano elt my-tap --state-id my-id`, or even when running via airflow

**Comment by LukePammant** [comment]
Closing as this was my own confusion with which `meltano.yml` file to add the capabilities to. I was under the assumption that it would pull the capabilities from the tap but it looks like you need to define it yourself in your project file's meltano.yml file as pointed out by @aaronsteers [here](https://github.com/meltano/sdk/issues/1384). 

Thanks for the help guys!
