### ISSUE TITLE
CLI: `meltano cloud el status`

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/meltano#7201]
# Success criteria
 - Users can run `meltano cloud job <state id> status` to see the status (success, running, failed) of the most recent job run for the job with state id <state id>
 - If user is not logged in, they are prompted to login
 - Should be implemented in such a way that the authentication pattern is reusable for future commands (i.e., via a `requires_login` decorator that checks the user is logged in, prompts them to do so if not, and then passes an authenticated `requests.session` for use in API calls in the command)
 - Up for discussion: this `meltano cloud` subcommand should not be merged into main and released widely right away. We should have a parallel branch which differs from `main` _only_ insofar as it makes the `meltano cloud` subcommand and all sub-subcommands available for use. 
 
 # Context
 Cloud users should be able to quickly and easily check status of their job runs from the CLI.  
 
 # Resources
- https://github.com/meltano/infra/discussions/238
- https://meltano.slack.com/archives/C03GKHWS0HM/p1671478362577159
- https://github.com/meltano/infra/issues/318

**Comment by tayloramurphy** [comment]
Added a link above to https://github.com/meltano/infra/issues/318 where I spent some time writing a more detailed spec.

**Comment by aaronsteers** [comment]
@tayloramurphy - I've moved this from Private Beta to Public Beta bucket. 

Lmk if you would like to revert.

**Comment by tayloramurphy** [comment]
@aaronsteers thanks for the tag. I agree with the move 👍

**Comment by aaronsteers** [comment]
> Flagging for later that I don't think `el` is the correct subcommand for this as the scope of what we could be fetching status on is more than just extract and load.

Only `el` jobs have a `state_id`, which is referenced as the lookup artifact in the description above. 

If not focusing on state ID, then this cover the generic scope I think:

1. https://github.com/meltano/infra/issues/321 (internal link)

Presumably that command could be filterable by certain attributes that we index in the execution log table. And that command could also return 'Running' or 'In Progress' if a job is still in progress.

**Comment by tayloramurphy** [comment]
> If https://github.com/meltano/infra/issues/321 covers the needed scope, we can close this in favor of that one.

@aaronsteers I'll close this for now as the linked issue does cover it from a Beta perspective.
