### ISSUE TITLE
feature: lock file usage telemetry

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7218]
Related to discussion in https://github.com/meltano/squared/issues/115

We should have an attribute or event that gets fired to Snowplow so we can understand where the plugin metadata is coming from when it's executed. Particularly related to understanding if lock files are used. I think the options are:

- lock file
- hub api directly
- meltano.yml for custom plugins
- custom hub api - Matatika does this
- discovery.yml (? idk if this is ever the case anymore)

**Comment by aaronsteers** [comment]
@pnadolny13, @WillDaSilva - Would it be reasonable to expand the PluginContext to include the plugin ref source? So, whenever a PluginContext is instantiated, it would have a instantiation source. Could be from: `manifest`, `lock file`,  `discovery.yml`, `hub API`, etc.

**Comment by WillDaSilva** [comment]
@aaronsteers That seems reasonable. I looked at the different places `ProjectPlugin` is instantiated, and while keeping track of this info may be a bit messy, it should be possible.

**Comment by aaronsteers** [comment]
> @aaronsteers That seems reasonable. I looked at the different places `ProjectPlugin` is instantiated, and while keeping track of this info may be a bit messy, it should be possible.

Cool! Another lense to think about about this from would be post-`manifest.json`. Specifically: in our compiled manifest file, what differences if any would be in the final manifest structure that might be able to give the requisite context?
