### ISSUE TITLE
feature: non-project Meltano config/data directory

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7224]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

For Meltano Cloud (and in particular `meltano login`) we need to be able to store config/data outside of a project directory on a user's computer. This would likely go somewhere under `AppData` on Windows, `$HOME/.config/meltano` on Linux, etc.

There may exist a library we can use to find these locations for us regardless of what platform we're on.

**Comment by edgarrmondragon** [comment]
Might be worth taking a look at

- [The XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (for Unix)
- https://github.com/platformdirs/platformdirs
