### ISSUE TITLE
Preview Meltano Cloud CLI

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7226]
Prior discussions:
- https://github.com/meltano/cloud-planning/discussions/33
- https://meltano.slack.com/archives/C03GKHWS0HM/p1671478362577159

---

I propose we create a feature branch based off of `main` called `cloud`, which will be kept up to date with `main`.

On this branch we would develop Meltano Cloud features that need a CLI, or otherwise interact with `meltano` in some way.

Meltano Cloud alpha/beta users would install this branch as opposed to the regular Meltano from PyPI by using `pipx install git+https://github.com/meltano/meltano.git@cloud`.

Running `meltano upgrade` would not work because it tries to upgrade using `meltano` from PyPI. As such, the `upgrade` command should be temporarily disabled.

Likewise, building the UI requires Yarn & Node v16 as system dependencies (among other things), and so because installing directly from source normally forces the user to build the UI, we should skip building the UI in `scripts/build.py` on this feature branch, and ensure that `meltano` works fine without it (i.e. the `ui` command should error with a clear message). The full removal of the UI should wait until Meltano v3 at least, and so will not be part of this branch.

A first iteration of this branch should provide the `meltano cloud` command group as a minimal Click CLI. Initially it may have a simple no-op command under it, but in the future we expect to add several commands including `log`, `login`, `run`, etc.

In particular, there would be immediate value for Meltano Cloud Alpha users in being able to re-run their scheduled jobs. This is currently possible through a curl command, but we could integrate it into the Cloud CLI. This would be done as a follow-up.

We will likely want to implement the Meltano Cloud CLI in `src/meltano-cloud/` as a separate Python package. In addition to being imported by `meltano` to provide the `meltano cloud` CLI, this package would also provide its own CLI as `meltano-cloud`.

Ideally `meltano` can import from `meltano-cloud`, but `meltano-cloud` cannot import from `meltano`. Maintaining this separation essentially reduces `meltano-cloud` to a simple CLI that handles HTTPS requests and responses to/from Meltano Cloud API endpoints. `meltano-cloud` would then be usable on its own as a lightweight utility, and would not interact with local Meltano projects.

**Comment by WillDaSilva** [comment]
> We will likely want to implement the Meltano Cloud CLI in src/meltano-cloud/ as a separate Python package. In addition to being imported by meltano to provide the meltano cloud CLI, this package would also provide its own CLI as meltano-cloud.

This would require us to transition to a monorepo structure where the `meltano` tests, `pyproject.toml`, etc., are all moved under `src/meltano`, and the current content of `src/meltano` is moved to `src/meltano/src`. The scope of this issue has been intentionally kept small, and transitioning to a monorepo is no small task, so we'll have to forgo this organization for now.

**Comment by tayloramurphy** [comment]
Another likely positive benefit to this structure is that we can encapsulate all open source code it one directory and all proprietary code in another.

**Comment by aaronsteers** [comment]
PR open:

#7261

**Comment by WillDaSilva** [comment]
@aaronsteers Thanks. It didn't auto-close when I merged the PR because the PR was targeting `cloud` instead of `main`. I wonder if there's some way to make GitHub close issues when PRs that claim to close them are merged into `cloud`. It's already marked as a protected branch.
