### ISSUE TITLE
feature: `--force` CLI flag for `meltano add`

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7277]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

We currently support the `--force` CLI flag for `meltano install`. Since `meltano add` installs by default, it should also support this flag.

**Comment by WillDaSilva** [comment]
Still relevant.

**Comment by XshubhamX** [comment]
@WillDaSilva Can I work on this?

**Comment by WillDaSilva** [comment]
@XshubhamX We'd gladly accept a contribution of this feature. I've assigned it to you. Feel free to reach out to us in the Meltano Slack if you run into any difficulties. Once your changes are working, tested, and documented, please open a PR, and we'll review it promptly.
