### ISSUE TITLE
bug: Cannot set integer settings with environment variables in meltano.yml

### ISSUE THREAD

**Issue by msg555** [meltano/meltano#7293]
### Meltano Version

2.15.2

### Python Version

3.8

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Linux/Docker (using the image `meltano:v2.15.2-python3.8` pushed a few hours ago)

### Description

I have been using an environment variable to configure the port of my mysql tap with something like the below in my meltano.yml.

```yaml
plugins:
  extractors:
    - name: tap-mysql
      variant: transferwise
      pip_url: pipelinewise-tap-mysql
      config:
        host: '${MY_TAP_HOST}'
        port: '${MY_TAP_PORT}'
```

This use to work but appears to be broken now, presumably due to https://github.com/meltano/meltano/pull/7232. Now you'll get an error ending with

```
│ /venv/lib/python3.8/site-packages/meltano/core/setting_definition.py:374 in cast_value           │
│                                                                                                  │
│   371 │   │   │   if self.kind == SettingKind.BOOLEAN:                                           │
│   372 │   │   │   │   return utils.truthy(value)                                                 │
│   373 │   │   │   elif self.kind == SettingKind.INTEGER:                                         │
│ ❱ 374 │   │   │   │   return int(value)                                                          │
│   375 │   │   │   elif self.kind == SettingKind.OBJECT:                                          │
│   376 │   │   │   │   value = json.loads(value)                                                  │
│   377 │   │   │   │   if not isinstance(value, dict):                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: invalid literal for int() with base 10: '${MY_TAP_PORT}'
```

I realize there are other ways I could accomplish this, e.g. setting TAP_MYSQL_PORT and leave this out of meltano.yml. I mostly want to confirm if this is intended behavior and see if there are any workarounds that allow me to express something similar within meltano.yml.

**Comment by aaronsteers** [comment]
Thanks for raising @msg555 !

We're looking into this and we expect to have a fix within 24 hours. Are you able to downgrade to the prior version in the meanwhile?
