### ISSUE TITLE
bug: SSL: CERTIFICATE_VERIFY_FAILED - Meltano >= 2.14.0 hub commands stop working with custom CA Root Certificates

### ISSUE THREAD

**Issue by cwegener** [meltano/meltano#7298]
### Meltano Version

2.14.0

### Python Version

3.10

### Bug scope

Other

### Operating System

Linux

### Description

Starting with v2.14.0, meltano hub interactions have switched to manual request preparation with `Session.prepare_request`, which results in the problem where the standard `requests` and `curl` environment variables are now no longer being honoured unless the environment variables are explicitly merged into the requests session again during the explicit request preparation.

https://github.com/meltano/meltano/pull/7188
https://requests.readthedocs.io/en/latest/user/advanced/#prepared-requests

The impacted environment variables are:

- `HTTP_PROXY`
- `HTTPS_PROXY`
- `REQUESTS_CA_BUNDLE`
- `CURL_CA_BUNDLE`

This breaks `meltano discover` and `meltano add` for users who must use a custom Certificate Authority Root Store for whatever reasons:
1.  using Zero Trust Network Proxy with SSL Inspection. 
2. using http debugging (e.g. `mitmproxy`)
3.  people who may run their own private "hubs" with private PKIs

In the case of explicitly configured (non-transparent) proxy set-ups, the HTTP communication with the hub also no longer flows through the manually configured proxy after this change, due to `HTTP_PROXY` and `HTTPS_PROXY` variables being ignored now as well.

To reproduce:

1. Install meltano v2.14.0 or higher
2. Install an SSL intercepting proxy e.g. `pip install mitmproxy`
3. Launch `mitmproxy` and install the mitmproxy Root CA cert https://docs.mitmproxy.org/stable/concepts-certificates/
4. Configure `requests` to use the mitmproxy Root CA cert: `export REQUESTS_CA_BUNDLE=${HOME}/.mitmproxy/mitmproxy-ca-cert.pem`
5. Set HTTP_PROXY and HTTPS_PROXY vars: `export http_proxy=http://localhost:8080` `export https_proxy=http://localhost:8080/`
4. Run `meltano discover` 

## Expected result (behaviour with meltano 2.13.0 and earlier)

- `meltano discover` succeeds and prints all available plugins from the hub
- all HTTP traffic to the hub is flowing throw `mitmproxy` correctly, honouring the mitmproxy custom Root CA cert

## Actual result (behaviour with meltano 2.14.0 and higher)

`meltano discover` fails in two ways:

1. HTTP request to the hub are no longer flowing through the `mitmproxy` due to `HTTP_PROXY` and `HTTPS_PROXY` variables being missing from the request session
2. Even when somehow managing to steer the HTTP requests to the hub through the proxy (e.g. with transparently proxying with iptables https://docs.mitmproxy.org/stable/howto-transparent-vms/), the request still fails with `[SSL: CERTIFICATE_VERIFY_FAILED]` due to `REQUESTS_CA_BUNDLE` env var not being merged into the requests session.

Related: https://gitlab.com/meltano/sdk/-/merge_requests/256

**Comment by edgarrmondragon** [comment]
Oh, I think I know what's going on. In https://github.com/meltano/meltano/pull/7188, I changed

```python
self.session.get(...)
```

into

```python
request = requests.Request("GET", url)
# set headers, etc.

prepared_request = self.session.prepare_request(request)
self.session.send(prepared_request)
```

The former calls [`Session.request`](https://requests.readthedocs.io/en/latest/_modules/requests/sessions/#Session.request), which merges environment settings, and the latter does not.

I do like having the option in the API to arbitrarily mutate the unprepared request, but we could do

```python
settings = self.session.merge_environment_settings(prepared_request.url, None, None, None)
return self.session.send(prepared_request, **settings)
```

I've labeled this with https://github.com/meltano/meltano/labels/Accepting%20Pull%20Requests if someone wants to take this.

**Comment by cwegener** [comment]
> I do like having the option in the API to arbitrarily mutate the unprepared request, but we could do

I do wonder how many other meltano users other than you and me actually would know that such mutators exist under the hood and would even have a use case for this particular mutation of the requests API :grin:
