### ISSUE TITLE
Remove the `meltano repl` command

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7309]
Reasons for removal:
- Our telemetry data shows this command has only been used twice with telemetry enabled, once on 2022-10-11, and the other time on 2022-10-31.
- It is only potentially useful for Meltano developers and others who are digging into the Meltano internals, but no Meltano engineers questioned about it during our engineering all-hands on 2023-02-14 claimed they used it.
- It appears untested.
- It errors in an unclear way if run outside of a project.
- It has (personally) been a source of confusion/hesitation while making changes that might affect it.
- It is hidden from the CLI.

**Comment by tayloramurphy** [comment]
@DouweM do you have any context on this command that we should be aware of? I didn't know it existed.
