### ISSUE TITLE
bug: misparsing of State backend URI in S3

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/meltano#7318]
### Meltano Version

2.14.0

### Python Version

3.10

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

ECS Fargate, S3 state backend

### Description

Part of the bucket name for the S3 state backend is being cut off, resulting in `AccessDenied` errors when attempting to read and write state.

**Comment by tayloramurphy** [comment]
FYI @seth-meltano I added to the Engineering Board

**Comment by cjohnhanson** [comment]
Looks like [a misuse of `rstrip`](https://github.com/meltano/meltano/blob/main/src/meltano/core/state_store/filesystem.py#L90) is the culprit here. 🤦 

I'll have a bugfix PR up momentarily.

**Comment by cjohnhanson** [comment]
Impact here is limited to filesystem backends where the hostname for the URI ends with characters which are also in its directory path. E.g. if you had `s3://meltano-job-state/eta`, that `rstrip` would mean that Meltano will look for state in `s3://meltano-job-s/eta`.
