### ISSUE TITLE
Bug: Setting array values with `--interactive` doesn't support common array syntaxes, and doesn't provide a format hint.

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7339]
In configuring values that are stored as string arrays, we don't provide any hint about how to set those value.

These all do not work:

- `asdf`
- `asdf, asdf2`
- `'asdf', 'asdf2'`
- `"asdf", "asdf2"`
- `[asdf]`
- `['asdf']`

The only error message is something like

> Failed to set value: Expecting value: line 1 column 2 (char 1)

Or:

> Failed to set value: Extra data: line 1 column 7 (char 6)

The expected syntax is square brackets, with double-quoted strings:

- `["asdf"]`
- `["asdf", "asdf2"]`

A simple fix would be to update the error handling to print a message with the required syntax whenever the input fails to parse. Something like:

> Failed to set value: Extra data: line 1 column 7 (char 6).
> Expected array syntax: ["item1", "item2"]

Raise in slack:

- https://meltano.slack.com/archives/C01TCRBBJD7/p1676926823957639

**Comment by WillDaSilva** [comment]
While we're addressing this, we should consider updating the places where we currently use `json.loads` for these values to use `ast.literal_eval` instead.

Making this change would broaden the accepted formats to a superset which includes e.g. `['asdf', "asdf",]` (note the trailing comma), or using parentheses instead of square brackets, or using no brackets at all.

Type checking would be required to ensure that a `collections.abc.Sequence` instance is received, but that's currently true as well since a user could enter something like `{"key":"value"}` as a JSON input.

This may be worth splitting off into a separate issue. Thoughts? @aaronsteers @tayloramurphy

**Comment by aaronsteers** [comment]
I'm not familiar with ast.literal_eval, but if that improves the UX experience, I think it's a valid solve for this issue. As always, we still need to watch out for regressions and scope creep, but I'm in favor of that as a fix here if it's relatively small scope.

**Comment by WillDaSilva** [comment]
@aaronsteers I've updated my comment with a link to the docs for `ast.literal_eval`. In summary (paraphrasing):

> Evaluate a string containing only a Python literal, which consists of the following Python literal structures: strings, bytes, numbers, tuples, lists, dicts, sets, booleans, `None` and `Ellipsis` (i.e. `...`). This is specifically designed not to execute Python code, unlike the more general `eval()`.

**Comment by aaronsteers** [comment]
Nice.

<details>
<summary>Details</summary>

```py
aj@AJs-MacBook-Pro ~ % python
Python 3.10.6 (main, Sep 30 2022, 13:17:42) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ast import literal_eval
>>> literal_eval("[foo,bar]")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aj/.pyenv/versions/3.10.6/lib/python3.10/ast.py", line 108, in literal_eval
    return _convert(node_or_string)
  File "/Users/aj/.pyenv/versions/3.10.6/lib/python3.10/ast.py", line 88, in _convert
    return list(map(_convert, node.elts))
  File "/Users/aj/.pyenv/versions/3.10.6/lib/python3.10/ast.py", line 107, in _convert
    return _convert_signed_num(node)
  File "/Users/aj/.pyenv/versions/3.10.6/lib/python3.10/ast.py", line 81, in _convert_signed_num
    return _convert_num(node)
  File "/Users/aj/.pyenv/versions/3.10.6/lib/python3.10/ast.py", line 72, in _convert_num
    _raise_malformed_node(node)
  File "/Users/aj/.pyenv/versions/3.10.6/lib/python3.10/ast.py", line 69, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 1: <ast.Name object at 0x109100dc0>
>>> literal_eval("['foo','bar']")
['foo', 'bar']
>>> literal_eval("[\"foo\",'bar']")
['foo', 'bar']
>>> literal_eval("\"foo\",'bar'")
('foo', 'bar')
>>> literal_eval("{\"foo\",'bar'}")
{'foo', 'bar'}
>>> literal_eval("{\"foo\": 'bar'}")
{'foo': 'bar'}
>>> literal_eval("'foobar'")
'foobar'
>>> literal_eval("'foobar'")
```

</details>
