### ISSUE TITLE
bug: `meltano add` throws an error on `2.16.0` when using proxies

### ISSUE THREAD

**Issue by drbjim** [meltano/meltano#7346]
https://github.com/meltano/meltano/blob/dc04f5eb69837220fcf62542913bc92f64eb2722/src/meltano/core/hub/client.py#L235

second arg(proxies) should be `{}`, otherwise it throws Nonetype error from requests/sessions.py when you run `meltano add loader ?`

<img width="936" alt="image" src="https://user-images.githubusercontent.com/25624918/221057426-bbf3860e-ddda-4586-aae9-0ee5af2e1a36.png">

**Comment by edgarrmondragon** [comment]
Hi @drbjim! Thanks for the report. I think your assessment is right, but can you share a bit more details for reproducibility?

For example, which environment variable you set to configure proxies.

**Comment by drbjim** [comment]
Thanks for the quick response,
Here are environment variables for proxy setting
HTTP_PROXY
HTTPS_PROXY
NO_PROXY
http_proxy
https_proxy
no_proxy

**Comment by edgarrmondragon** [comment]
Thanks @drbjim! I got a failing test and in soon a PR 🙂
