### ISSUE TITLE
bug: manifest contains passwords when using `<PLUGIN_NAME>_<SETTING_NAME>` syntax

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7355]
### Meltano Version

2.16.1

### Python Version

3.9

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

macOS

### Description

Using the new beta [compile](https://docs.meltano.com/reference/command-line-interface#compile) command to generate manifest files causes some of my sensitive settings to be included. As I understand it thats not supposed to happen.

I have some settings defined in my .env file using the `<PLUGIN_NAME>_<SETTING_NAME>` syntax and it looks like theyre getting through to my manifest file. For example `TAP_GITHUB_AUTH_TOKEN`. It's set as a password type in [the plugin definition](https://github.com/meltano/squared/blob/ac3eee55102c275a1c6a706279d645e3522a401d/data/plugins/extractors/tap-github--meltanolabs.lock#L47) sourced from the hub.

**Comment by WillDaSilva** [comment]
Still relevant
