### ISSUE TITLE
bug: `meltano add` logs variant as default when its not

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7365]
When I add a [non-default meltanolabs target-postgres](https://hub.meltano.com/loaders/target-postgres--meltanolabs/) variant to my project from the hub it says that its the default variant in the logs even though its not the default.

<img width="1091" alt="Screen Shot 2023-03-06 at 4 55 36 PM" src="https://user-images.githubusercontent.com/27376735/223243919-d8e52b4d-2113-41ec-9d29-31462a923301.png">

I confirmed with a request to the hub api that the results coming from the hub are correct. It seems like Meltano might not be retrieving the default name from the hub api properly.

<img width="1002" alt="Screen Shot 2023-03-06 at 4 58 15 PM" src="https://user-images.githubusercontent.com/27376735/223244314-04b77b01-a28b-464e-b1a5-ac24ed23ef34.png">

**Comment by edgarrmondragon** [comment]
Yeah, there's a bit on conflict between legacy variant lists within a single _plugin definition_ and the new Hub schema with separate variants. I think I have a fix.
