### ISSUE TITLE
Ability to test `meltano add` on a plugin prior to a Hub PR being merged

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7368]
I'd love to have a way to test `meltano add ...` on a plugin before we publish to the Hub.

Any ideas? I initially thought to use the `hub_url` overrides to target the preview deployment, but I am pretty sure we are not publishing the JSON API to Netlify. We also can't use the S3 files since many of these are run from community forks and won't have any S3 publish permissions.

Perhaps we need to implement a `--from=HUB_YAML_FILE_URL` arg in the CLI for `meltano add` or else make it process to download the yaml file from the hub directly into the location where the lockfile would be?

cc @edgarrmondragon, @pnadolny13 - I think you two are the more knowlegeble on these processes. Any ideas?

**Comment by ReubenFrankel** [comment]
> Perhaps we need to implement a --from=HUB_YAML_FILE_URL arg in the CLI for meltano add or else make it process to download the yaml file from the hub directly into the location where the lockfile would be?

What about merging it directly into the `meltano.yml`, kinda of like how `meltano add --custom` works?

**Comment by pnadolny13** [comment]
@aaronsteers I could have sworn that the preview hub url worked but youre right, I got something like "utility matatika" not found when I tried for that PR.

>Perhaps we need to implement a --from=HUB_YAML_FILE_URL arg in the CLI for meltano add or else make it process to download the yaml file from the hub directly into the location where the lockfile would be?


....
>What about merging it directly into the meltano.yml, kinda of like how meltano add --custom works?

Yeah I like those ideas of having a way to point to the hub yaml file and let it install from there as a custom plugin and pull out all the relevant keys that it needs to install.

**Comment by aaronsteers** [comment]
> > Perhaps we need to implement a --from=HUB_YAML_FILE_URL arg in the CLI for meltano add or else make it process to download the yaml file from the hub directly into the location where the lockfile would be?
> 
> What about merging it directly into the `meltano.yml`, kinda of like how `meltano add --custom` works?

This might work... I'm not sure. I considered it, but backed down just because it seemed pretty messy with the amount of time I had on Tuesday night to test. Definitely worth a shot, I think.

There would be a ton of extra properties that meltano might (?) complain about, and manually you'd need to at least indent the code and add under a bullet.

**Comment by edgarrmondragon** [comment]
I like the idea. Only the `docs` and `logo_url` would be wrong because the need the base URL, but otherwise all the info returned from the API would be there 👍. It's a low effort too AFAICT.

**Comment by ReubenFrankel** [comment]
IMO still relevant and related to #6615.

**Comment by ReubenFrankel** [comment]
N.B. this is now possible, but not yet added as PR check
