### ISSUE TITLE
bug: Plugin name exists still throws "not known"

### ISSUE THREAD

**Issue by sbalnojan** [meltano/meltano#7392]
### Meltano Version

2.1.17

### Python Version

3.10

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Ubuntu 20.04

### Description

Situation: I already have an extractor with the name "tap-postgres" inside my meltano.yml and want to add a different variant on the same name, I get the following error:

```
@sbalnojan ➜ /workspaces/demo-expert-computing-machine (main) $ meltano add extractor tap-postgres --variant meltanolabs
Extractor 'tap-postgres' already exists in your Meltano project
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Extractor 'tap-postgres' variant 'meltanolabs' is not known to Meltano. Variants: transferwise (default)
```
=> Extractor 'tap-postgres' variant 'meltanolabs' is not known to Meltano. Variants: transferwise (default)

That line at the bottom is quite confusing if one does not read the first line. (Yes that happened to me multiple times).

Instructions how to fix this problem might also be nice.

**Comment by tayloramurphy** [comment]
@sbalnojan thanks for the issue. I think we should just automatically make this succeed for the user and print out what actions we took. 

```bash
 $ meltano add extractor tap-postgres --variant meltanolabs
Extractor 'tap-postgres' already exists in your Meltano project 
Adding the plugin and renaming to 'tap-postgres-meltanolabs'. 
Installing... etc. 
```

What about that? @aaronsteers thoughts on this?

**Comment by aaronsteers** [comment]
@tayloramurphy - it's a much smaller scope, I think, to remove the second print line (probably a 1 or 2), versus adding with custom name (probably a 4). 

I'm in favor of both, but I prefer the quick win if it otherwise will take time to prioritize the larger fix.

I think we actually may already have an issue for supporting auto-adding a second variant, but I'm not sure.

**Comment by tayloramurphy** [comment]
@aaronsteers agreed on the quick fix.

I made https://github.com/meltano/meltano/issues/7393 to track the new behavior. I couldn't find a relevant issue.

**Comment by edgarrmondragon** [comment]
@aaronsteers @tayloramurphy the pre-2.0 behavior was to print some instructions:

```
To switch from the current 'transferwise' variant to 'meltanolabs':
1. Update `variant` and `pip_url` in your `meltano.yml` project file:
    name: tap-postgres
    variant: meltanolabs
    variant: <variant pip url>
2. Reinstall the plugin:
    meltano install extractor tap-postgres
3. Check if the configuration is still valid (and make changes until it is):
    meltano config tap-postgres list

To learn more, visit https://docs.meltano.com/guide/plugin-management#switching-from-one-variant-to-another"

Alternatively, to keep the existing 'tap-postgres' with variant 'transferwise'
add variant 'meltanolabs' as a separate plugin with its own unique name:
    meltano add extractor tap-postgres--meltanolabs --inherit-from tap-postgres --variant meltanolabs

To learn more, visit https://docs.meltano.com/guide/plugin-management#multiple-variants
```

Do we want to

1) keep all of it or
2) only suggest the second bit?

The former is a larger effort because it requires refactoring, since it needs the new variant's pip URL, which before was immediately available in `discovery.yml`, but now requires either passing down the Hub's `/<type>/index` response or making a new call.

**Comment by tayloramurphy** [comment]
@edgarrmondragon ideally I'd like to keep all of it. But to keep it simple we could just add another link for folks to go find the pip_url and have a follow on issue to to automatically show it. 

`variant: <variant pip url> # Check https://hub.meltano.com/extractors/tap-postgres--meltanolabs for the current URL and version`

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon ideally I'd like to keep all of it. But to keep it simple we could just add another link for folks to go find the pip_url and have a follow on issue to to automatically show it.
> 
> `variant: <variant pip url> # Check https://hub.meltano.com/extractors/tap-postgres--meltanolabs for the current URL and version`

@tayloramurphy I may actually be easier to fix than I first thought: https://github.com/meltano/meltano/pull/7399

**Comment by tayloramurphy** [comment]
@edgarrmondragon you love to see it!

**Comment by tayloramurphy** [comment]
@edgarrmondragon I just tested this today and I think there's just one mistake. The `variant` on the first set of instructions is wrong. It has the plugin name, not the variant name.

```
❯ meltano add extractor tap-postgres --variant meltanolabs
Extractor 'tap-postgres' already exists in your Meltano project

To switch from the current 'transferwise' variant to 'meltanolabs':
1. Update `variant` and `pip_url` in your `meltano.yml` project file:
        name: tap-postgres
        variant: tap-postgres
        pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
2. Reinstall the plugin:
        meltano install extractor tap-postgres
3. Check if the configuration is still valid (and make changes until it is):
        meltano config tap-postgres list

To learn more, visit https://docs.meltano.com/guide/plugin-management#switching-from-one-variant-to-another

Alternatively, to keep the existing 'tap-postgres' with variant 'transferwise',
add variant 'meltanolabs' as a separate plugin with its own unique name:
        meltano add extractor tap-postgres--meltanolabs --inherit-from tap-postgres --variant meltanolabs

To learn more, visit https://docs.meltano.com/guide/plugin-management#multiple-variants
```

**Comment by edgarrmondragon** [comment]
@tayloramurphy thanks for testing, should be ok now
