### ISSUE TITLE
Remove Python 3.7 support

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7397]
Python 3.7 reaches it's end of life on 2023-06-27:
- https://devguide.python.org/versions/
- https://peps.python.org/pep-0537/

After this release, we should drop support for Python 3.7. This will let us use newer versions of several dependencies, let us use features only available in Python 3.8+, and let us clean up Python 3.7 compatibility workarounds.

Python 3.8+ features we'll now be able to use include:
- [Assignment expressions](https://peps.python.org/pep-0572/) (i.e. the walrus operator) `:=`. The common case were this kind of expression is clear and valuable is with if statements that operate on a variable only if the variable has a truthy value. Instead of this:
  ```python
  value = asdf()
  if value:
      # do something with value
  ``` 
  We can do this:
  ```python
  if value := asdf():
      # do something with value
  ```
- [Positional-only parameters](https://peps.python.org/pep-0570/), which let us use `/` within a parameter list similarly to how `*` can be used, except instead of specifying that all arguments afterwards must be provided as a keyword argument as `*` does, `/` specifies that all arguments _before_ must be specified as a positional argument. This prevents callers from creating a dependency on the name of the parameter, effectively allowing the creator of the function to remove the affected parameter names from the contract of the API.
  ```python
  def f(pos1, pos2, /, pos_or_kwd, *, kwd1, kwd2):
        -----------    ----------     ----------
          |             |                  |
          |        Positional or keyword   |
          |                                - Keyword only
           -- Positional only
  ```
- The `=` specifier in f-strings, which is mainly for logging and print-statement debugging. Example:
  ```python
  >>> print(f'{theta=}  {cos(radians(theta))=:.3f}')
  theta=30  cos(radians(theta))=0.866
  ```
- The addition of `Protocol`, `runtime_checkable`, `final`, `TypedDict`, and `Literal` to the `typing` standard library (i.e. we won't need to use `typing_extensions` for these anymore).
- The addition of `importlib.metadata` to the standard library, so we won't have to use the `importlib_metadata` package anymore.
- The addition of `cached_property` to the `functools` standard library, so we won't have to use the `cached_property` package anymore.
- Update `pre-commit` to a version greater than 2.
- Misc performance improvements.

Related:
- https://github.com/meltano/meltano/issues/6223
- https://github.com/meltano/meltano/issues/6544

**Comment by WillDaSilva** [comment]
Once Python 3.7 support has been dropped, we'll be able to consider https://pypi.org/project/datafiles/ as an option for the foundation of Meltano's config management, and for the configuration of the Cloud CLI. I think this library is worth exploring as an alternative to Meltano's `Canonical` class. It's a dataclass-based ORM backed by JSON/YAML/TOML files. Like Meltano, it uses Ruamel to preserve comments/style when writing back to YAML. I'll open an issue for it after I've looked more into it, and we're closer to being able to use it (after Python 3.7 support has been dropped).

**Comment by edgarrmondragon** [comment]
@kgpayne, I know you'll love seeing `datafiles` being considered here 😁
