### ISSUE TITLE
Cloud CLI: Add `--lookback` option to cloud history command

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#7420]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

```sh
meltano cloud history --limit 10 --lookback 10d
```

Related:

* Follow-on to https://github.com/meltano/meltano/pull/7415
* Depends on https://github.com/meltano/infra/issues/525

**Comment by tayloramurphy** [comment]
@edgarrmondragon what are the accepted formats for --lookback? And I should read this as "get me the logs starting from 10 days ago and limit results to 10"?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon what are the accepted formats for --lookback?

@tayloramurphy That's up for discussion but the proposal in https://github.com/meltano/infra/issues/321 seems to suggest a number plus unit, e.g. 3 days = `3d`, 12 hours = `12h`. We could support hours, days and weeks.

cc @aaronsteers 

> And I should read this as "get me the logs starting from 10 days ago and limit results to 10"?

Yup, that's the intent of the command above.

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/meltano/pull/7438
