### ISSUE TITLE
Cloud CLI: `meltano cloud status`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7424]
Would require calling multiple API backend endpoints.

Would print basic metadata about the active project:

1. Project name and ID.
1. Organization name / ID.
1. Internal keys like tenant resource key. (Perhaps only if `--verbose` or `--debug` is provided.)

Would list the following:

1. Which schedules exist. (Perhaps literally the output of `meltano cloud schedules list`.)
4. Which deployments exist for the active project. (Perhaps literally the output of `meltano cloud deployments list`.)
5. Any jobs currently running.

**Comment by tayloramurphy** [comment]
Duplicate of https://github.com/meltano/meltano/issues/6958
