### ISSUE TITLE
CLI: "Did you mean?" prompt if command doesn't exist

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7425]
```
% meltano cloud invoke evidence:dev
Error. `meltano cloud invoke` is not a valid command. Did you mean `meltano invoke`?
```

```
% meltano status
Error. `meltano status` is not a valid command. Did you mean `meltano cloud status`?
```

```
% meltano login
Error. `meltano login` is not a valid command. Did you mean `meltano cloud login`?
```

**Comment by tayloramurphy** [comment]
This would still be great. How hard is something like this to implement @WillDaSilva ?

**Comment by WillDaSilva** [comment]
@tayloramurphy Pretty easy - so much so that responding with what would be required to implement this feature is hardly faster than just implementing it:
- https://github.com/meltano/meltano/pull/7932

**Comment by tayloramurphy** [comment]
@WillDaSilva Love those kind of issues 🤣
