### ISSUE TITLE
bug: `flask` not found when running `meltano-cloud` via `pipx`

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7426]
### Meltano Version

N/A

### Python Version

3.11

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Python 3.11 Docker container

### Description

```sh
pip install pipx
pipx install 'git+https://github.com/meltano/meltano.git@cloud#subdirectory=src/cloud-cli'`
pipx ensurepath
bash
meltano-cloud login
```

Results in:
```
FileNotFoundError: [Errno 2] No such file or directory: 'flask'
```

This is because `pipx` only exposes the CLI entrypoints of our package, and not those of its dependencies like `flask`. We can resolve this by using the precise path to the `flask` binary in the active environment rather than searching for it on `$PATH`.

**Comment by edgarrmondragon** [comment]
Not sure why this wasn't closed automatically 🤷
