### ISSUE TITLE
Publish `meltano-cloud-cli` package to PyPI

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7456]
Currently we instruct users to use `pipx` to install the `meltano-cloud` CLI application. Instructions from internal Slack channel: https://meltano.slack.com/archives/C04V2560TPE/p1679529094984779

```sh
pipx install 'git+https://github.com/meltano/meltano.git@cloud#subdirectory=src/cloud-cli'
```

The Meltano Cloud CLI can be invoked standalone via `meltano-cloud`, or from the full version of Meltano using `meltano cloud`. Note that you can still invoke the Cloud CLI as `meltano-cloud` if you have the full version of Meltano installed.

As we do in the infra repository, we should use a [Poetry path dependency](https://python-poetry.org/docs/dependency-specification/#path-dependencies) to have the full Meltano Python project depend on the Cloud CLI. This would keep their dependencies compatible thanks to Poetry's dependency resolution - all of the dependencies for the Cloud CLI would be installed with the full Meltano installation too. This would also make for a better development experience, since `poetry install` would install the project properly.

Instead we currently use a hacky `pre-commit` script that checks that the dependencies listed in `src/cloud-cli/pyproject.toml` are also listed in `pyproject.toml`, and a symlink to fix the `poetry install` issue. The symlink results in every file from the Cloud CLI appearing twice in e.g. code searches in our editors.

The current hacky approach also does not scale to multiple packages well, if at all. This was an issue that significantly impeded the addition of telemetry to the Cloud CLI:
- #7266 

The reason we do not currently use a Poetry path dependency is because it is essentially impossible to publish a Python package with a path dependency, since that path won't be valid on the computer it is installed on. Fortunately we can use https://github.com/artisanofcode/poetry-stickywheel-plugin to work around this. It can be run immediately prior to publishing (e.g. in CI), and it replaces path dependencies with regular version dependencies. Because the path dependencies are replaced by version dependencies, the packages being depended on (currently just `meltano-cloud-cli`, but this could include as-of-yet non-existent subpackages such as `meltano-core`, `meltano-telemetry`, `meltano-cli`, etc. in the future) must be published to PyPI (or whatever Python package index is being used).

To resolve the issues explained above, and to make the installation process for the Cloud CLI easier by simply having to instruct users to install `meltano-cloud-cli` rather than run `pipx` targeting a branch and subdirectory on our GitHub, I propose we publish `meltano-cloud-cli` to PyPI.

Does this seem like a desirable approach @meltano/engineering @tayloramurphy?

**Comment by aaronsteers** [comment]
@WillDaSilva - I think this needs a deep dive on pros/cons. Can you put something on the calendar with me, you, Taylor, plus anyone else interested to join the discussion?

**Comment by kgpayne** [comment]
@WillDaSilva just for clarification:

- Are we expecting `meltano-cloud` to be installed and used in a standalone way? I currently use `meltano cloud` via a full install of the `cloud` branch. My assumption is that will be the primary way to access the cloud cli?
- Would packaging `meltano-cloud` separately allow us to install the cloud cli as an optional dependency, via `pipx install meltano[cloud]`? I think that has really great optics, vs. having cloud automatically bundled with OSS Meltano 🙂

> The symlink results in every file from the Cloud CLI appearing twice in e.g. code searches in our editors.

Agree this is annoying, and potentially breaks some IDE features around renaming/refactoring. Would be a great QOL fix 👍

**Comment by WillDaSilva** [comment]
> Are we expecting `meltano-cloud` to be installed and used in a standalone way? I currently use `meltano cloud` via a full install of the cloud branch. My assumption is that will be the primary way to access the cloud cli?

@kgpayne I think for regular users of Meltano the full CLI would be how they typically access the Cloud CLI, but currently the Cloud CLI also functions standalone, and I'd like to keep it that way since it seems fairly low-effort, and comes with a few advantages. Notably:
- The standalone Cloud CLI has far fewer dependencies, which:
  - Makes it require less downloading (which could matter a lot for CI environments or other places in which it'll be re-installed frequently).
  - Makes it easier for security teams to vet before allowing their company's devs to install it.
- It establishes a lightweight reusable pattern for how we can modularize components within Meltano. This could be extended to `meltano.core`, `meltano.api`, `meltano.telemetry`, etc. in the future. Particularly as our engineering team grows, this modularization would pay dividends.

> Would packaging `meltano-cloud` separately allow us to install the cloud cli as an optional dependency, via `pipx install meltano[cloud]`? I think that has really great optics, vs. having cloud automatically bundled with OSS Meltano

Yes, we could make the Cloud CLI installable as an extra, rather than be included by default. I'm not sure this would be desirable, since it adds a (small) barrier to using and discovering Meltano Cloud, but it would be possible.

**Comment by WillDaSilva** [comment]
- https://github.com/meltano/meltano/issues/7959
