### ISSUE TITLE
Replace use of `Path(__file__)` with `importlib_resources` to support Meltano zipapp

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7474]
https://docs.python.org/3/library/importlib.resources.html

> This module leverages Python’s import system to provide access to resources within packages. If you can import a package, you can access resources within that package. Resources can be opened or read, in either binary or text mode.
> 
> Resources are roughly akin to files inside directories, though it’s important to keep in mind that this is just a metaphor. Resources and packages do not have to exist as physical files and directories on the file system: for example, a package and its resources can be imported from a zip file using [zipimport](https://docs.python.org/3/library/zipimport.html#module-zipimport).

Currently Meltano makes use of `pathlib.Path(__file__)` in 3 locations under `src/meltano`. These paths are incorrect when Meltano is running as a zipapp. To access the contents the paths would normally refer to in all cases, `importlib.resources` must be used. To support older versions of Python, the official backport `importlib_resources` should be used instead: https://github.com/python/importlib_resources

This backport is already a dependency of Meltano, so all that remains is to make us of it.

CC @aaronsteers because of your interest in zipapps. From what I've heard this is a moderately widespread issue with them, but at least we can do our part to make sure Meltano runs properly as one.

**Comment by WillDaSilva** [comment]
Example of how we can use `importlib_resources` instead of `Path(__file__)`:
- https://github.com/meltano/meltano/blob/62446ae8830a49aeafe04696fecff7a76f8046b2/src/cloud-cli/meltano/cloud/api/auth/auth.py#L86-L98

A caveat of this approach is that the directory containing the resource files must be a Python module, so we may have to add some otherwise useless `__init__.py` files. In this example we use `__package__` to access the directory the calling Python file is in, but more generally we can import the Python module containing the resource files, and then use the imported module instead of `__package__`.

**Comment by edgarrmondragon** [comment]
Still relevant
