### ISSUE TITLE
docs: extras formatting is hard to read

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7478]
On https://docs.meltano.com/concepts/plugins#metadata-extra the formatting is hard to read because the code snippet from the previous sections blends with the section header. I think we should either add some space between the two or make the header background color different than the code background color.

![Screen Shot 2023-04-03 at 5 02 31 PM](https://user-images.githubusercontent.com/27376735/229627102-70dbeb87-03ec-4f93-a3cd-039f0c1a2e38.png)

**Comment by tayloramurphy** [comment]
@DouweM you did the CSS changes on the docs - what's a quick fix for this?

**Comment by edgarrmondragon** [comment]
Looks much better now with Docusaurus: https://docs.meltano.com/concepts/plugins/#metadata-extra
<img width="1026" alt="Screenshot 2023-08-01 at 20 24 31" src="https://github.com/meltano/meltano/assets/16805946/64a47d2b-e83f-4d9a-83d1-fe5963f8a0e6">
