### ISSUE TITLE
feat: Cloud CLI - enable filtering of schedule history by `deployment` and `result`

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#7486]
* ~~`meltano cloud history --name=<>`~~ Covered by https://github.com/meltano/meltano/pull/7467

* `meltano cloud history --deployment=<>`

* `meltano cloud history --result=[Success|Failed|Running]`

**Comment by edgarrmondragon** [comment]
@tayloramurphy does `name` refer to the schedule name?

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/meltano/pull/7626
