### ISSUE TITLE
bug: tcgetpgrp failed: Not a tty

### ISSUE THREAD

**Issue by visch** [meltano/meltano#7494]
### Meltano Version

2023-04-05 - 'git+https://github.com/meltano/meltano.git@cloud#subdirectory=src/cloud-cli' 

### Python Version

3.8

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

20.04.5 LTS on WSL2

### Description

1. Using WSL2 on my desktop I run `meltano-cloud login` from https://docs.meltano.com/cloud/onboarding#step-2-install-or-update-the-cloud-cli
2. My browser opens, I auth
3. Terminal is still open waiting for something, so I hit enter a couple times and I get

I bet this is something specific to wsl2 / Windows. My chrome browser opened in Windows so there's some magic behind the scenes going on here. 

### Code

```python
visch@DESKTOP-9BDPA9T:~/git/prodder$ meltano-cloud login
Logging in to Meltano Cloud.
You will be directed to a web browser to complete login.
If a web browser does not open, open the following link:
https://auth.meltano.cloud/oauth2/authorize?client_id=client_id_was_here&response_type=token&scope=email+openid+profile&redirect_uri=http%3A%2F%2Flocalhost%3A9999
tcgetpgrp failed: Not a tty
Logged in as visch
```

### Workaround on Windows

Don't run on WSL, run in Powershell

**Comment by WillDaSilva** [comment]
Probably still relevant
