### ISSUE TITLE
Feature (Cloud CLI): Adding a `--follow` option for `meltano cloud run` to immediately run and then stream logs to console

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7559]
This feature would stack together two other features:

- #7558 
- #7557 

So that internally, the Cloud CLI could (1) know the Execution ID for a `meltano cloud run` command which has just been invoked, and then (2) automatically tail the logs while the job is running, and until the user presses Ctrl+C to exit.

The goal with this feature would be to give something that resembles the ease-of-use of local execution (user runs a job and see its logs while its running) even though the job execution is not local.

**Comment by tayloramurphy** [comment]
Still relevant but low-pri
