### ISSUE TITLE
bug: Homepage "Try Live Demo" link appears to be broken

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#7613]
### Meltano Version

n/a

### Python Version

3.6 (deprecated)

### Bug scope

API

### Operating System

n/a

### Description

Hi folks! Ran into this issue just now. It looks like GitHub may have changed their launch screen deep link rules for Codespaces. 

Clicking "Try Live Demo" today on https://meltano.com took me to `https://meltano.com/demo` - which redirected to...

`https://github.com/codespaces/new?template_repository=meltano/meltano-codespace-ready`

...and the UI is missing the repo selection:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/18150651/234418653-d69cabd5-15c1-4232-825a-83af347a8e78.png">

This URL seems to work for me (copy-pasted after entering the missing fields):

[`https://github.com/codespaces/new?template_repository=meltano%2Fmeltano-codespace-ready&machine=basicLinux32gb&repo=566374145&ref=main&location=WestUs2&devcontainer_path=.devcontainer%2Fdevcontainer.json`](https://github.com/codespaces/new?template_repository=meltano%2Fmeltano-codespace-ready&machine=basicLinux32gb&repo=566374145&ref=main&location=WestUs2&devcontainer_path=.devcontainer%2Fdevcontainer.json)

cc @sbalnojan, @tayloramurphy

**Comment by aaronsteers** [comment]
If I go to the repo, click the "+" icon, and select "Share Deep Link", then this URL is suggested: 

[`https://codespaces.new/meltano/meltano-codespace-ready`](https://codespaces.new/meltano/meltano-codespace-ready)

**Comment by tayloramurphy** [comment]
Thanks for the issue @aaronsteers ! I think we've got this sorted out. We haven't updated to the new URL but it seems to be working. If you notice a problem still can you reopen? cc @sbalnojan
