### ISSUE TITLE
Emit deprecation warning when `elt` command is used instead of `el`

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7617]
Also emit a deprecation warning when the transform option is used.

The `el` command would have to exist before this could be completed.

Relates to:
- https://github.com/meltano/meltano/discussions/6273

**Comment by edgarrmondragon** [comment]
Since https://github.com/meltano/meltano/issues/7576 is in the v3 Milestone and the `elt` might behave unexpectedly for users of `--transform` (see https://github.com/meltano/meltano/issues/7548#issuecomment-1513382766), do we want to add this to the v3 Milestone too?

@WillDaSilva @tayloramurphy

**Comment by WillDaSilva** [comment]
Sounds good to me @edgarrmondragon. We'd want to target `main` with the addition of the new `el` command, and likely with the addition of the deprecation warning too.

**Comment by tayloramurphy** [comment]
@edgarrmondragon so the plan would be:

* to add `el`, which is basically an alias for `elt` minus the `--transform` flag
* keep `elt` but emit deprecation warning if used with the `--transform` option
* target v4 for full removal of `elt`

That about right? If so, makes sense to me.
