### ISSUE TITLE
bug: When meltano.yml is empty, no error message is printed. Rather, it just mentions to reach out to community

### ISSUE THREAD

**Issue by rawwar** [meltano/meltano#7635]
### Meltano Version

2.19.0

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Windows - WSL(Ubuntu)

### Description

when `meltano.yml` is empty, `cli`(`meltano.cli.__init__.py: 105`) raises `EmptyMeltanoFileException` exception whenever we try to run any command such as `meltano add` or `meltano ui`. But, since there's no exception message, it just prints the troubleshooting message and blank lines as follows

```
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

```

**Comment by tayloramurphy** [comment]
@rawwar thanks for the bug report. Seems like an easy fix to throw some text on the command line there. I'll add the Accepting PRs label, but perhaps @meltano/engineering will pick it up too!

Out of curiosity, how are you winding up with an empty `meltano.yml`?

**Comment by tayloramurphy** [comment]
🤦 I didn't see the PR you opened as well! Thanks!

**Comment by rawwar** [comment]
> @rawwar thanks for the bug report. Seems like an easy fix to throw some text on the command line there. I'll add the Accepting PRs label, but perhaps @meltano/engineering will pick it up too!
> 
> Out of curiosity, how are you winding up with an empty `meltano.yml`?

I was actually working on some other thing. It kept complaining no meltano.yml.. so, I just created an empty file and forgot about it. I kept seeing empty error messages after a while.. when I tried to debug.. found the issue
