### ISSUE TITLE
bug: Configuration values for `hidden`-type settings from environment variables are always `string` implicitly 

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/meltano#7663]
### Meltano Version

2.16.1

### Python Version

3.7

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Linux - Ubuntu 22.04

### Overview
When providing configuration for a plugin from environment variables (shell or `.env`), if the corresponding setting is of `kind` `hidden`, (in `meltano.yml` or plugin `.lock` file), the value is always handled as a string (as if the setting were of `kind` `string`). 

In the case of [`tap-auth0`](https://hub.meltano.com/extractors/tap-auth0/), trying to supply an override for the default value of `job_poll_interval_ms` as an environment variable (`TAP_AUTH0_JOB_POLL_INTERVAL_MS`) causes configuration schema validation to fail (see traceback).

### Fix
Since the Meltano UI is no longer supported, I don't know how much value updating the setting definition to replace `hidden` as a `kind` with `hidden` as a separate boolean flag holds for Meltano (not sure if it is used anywhere else other than for the UI).

If `hidden` is to be deprecated or removed eventually, a nice interim solution would be to infer the type from the setting default value (if present). 

Happy to open a PR for either of these.

### Code

`meltano.yml`
```
version: 1
send_anonymous_usage_stats: true
project_id: tap-auth0
default_environment: test
environments:
- name: test
plugins:
  extractors:
  - name: tap-auth0
    namespace: tap_auth0
    pip_url: -e .
    capabilities:
    - state
    - catalog
    - discover
    settings:
    - name: client_id
      kind: password
    - name: client_secret
      kind: password
    - name: domain
    - name: job_poll_interval_ms
      kind: hidden
    - name: job_poll_max_count
      kind: hidden
```

`.env`
```
# required settings
TAP_AUTH0_CLIENT_ID=<client id>
TAP_AUTH0_CLIENT_SECRET=<client secret>
TAP_AUTH0_DOMAIN=<domain>

# optional integer setting
TAP_AUTH0_JOB_POLL_INTERVAL_MS=5000
```

```
$ meltano invoke tap-auth0
Traceback (most recent call last):
  File "/home/reuben/Documents/taps/tap-auth0/.meltano/extractors/tap-auth0/venv/bin/tap-auth0", line 8, in <module>
    sys.exit(TapAuth0.cli())
  File "/home/reuben/Documents/taps/tap-auth0/.meltano/extractors/tap-auth0/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/reuben/Documents/taps/tap-auth0/.meltano/extractors/tap-auth0/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/reuben/Documents/taps/tap-auth0/.meltano/extractors/tap-auth0/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/reuben/Documents/taps/tap-auth0/.meltano/extractors/tap-auth0/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/reuben/Documents/taps/tap-auth0/.meltano/extractors/tap-auth0/venv/lib/python3.7/site-packages/singer_sdk/tap_base.py", line 497, in cli
    validate_config=validate_config,
  File "/home/reuben/Documents/taps/tap-auth0/.meltano/extractors/tap-auth0/venv/lib/python3.7/site-packages/singer_sdk/tap_base.py", line 73, in __init__
    validate_config=validate_config,
  File "/home/reuben/Documents/taps/tap-auth0/.meltano/extractors/tap-auth0/venv/lib/python3.7/site-packages/singer_sdk/plugin_base.py", line 121, in __init__
    self._validate_config(raise_errors=validate_config)
  File "/home/reuben/Documents/taps/tap-auth0/.meltano/extractors/tap-auth0/venv/lib/python3.7/site-packages/singer_sdk/plugin_base.py", line 257, in _validate_config
    raise ConfigValidationError(summary)
singer_sdk.exceptions.ConfigValidationError: Config validation failed: '5000' is not of type 'integer', 'null'
JSONSchema was: {'type': 'object', 'properties': {'client_id': {'type': ['string'], 'description': 'App client ID'}, 'client_secret': {'type': ['string'], 'description': 'App client secret'}, 'domain': {'type': ['string'], 'description': 'Tenant domain'}, 'job_poll_interval_ms': {'type': ['integer', 'null'], 'default': 2000, 'description': 'Job poll interval (ms)'}, 'job_poll_max_count': {'type': ['integer', 'null'], 'default': 10, 'description': 'Maximum job poll count'}, 'stream_maps': {'type': ['object', 'null'], 'properties': {}, 'description': 'Config object for stream maps capability. For more information check out [Stream Maps](https://sdk.meltano.com/en/latest/stream_maps.html).'}, 'stream_map_config': {'type': ['object', 'null'], 'properties': {}, 'description': 'User-defined config values to be used within map expressions.'}, 'flattening_enabled': {'type': ['boolean', 'null'], 'description': "'True' to enable schema flattening and automatically expand nested properties."}, 'flattening_max_depth': {'type': ['integer', 'null'], 'description': 'The max depth to flatten schemas.'}}, 'required': ['client_id', 'client_secret', 'domain']}
```
```

**Comment by ReubenFrankel** [comment]
@tayloramurphy Ah yes, I knew that `sensitive` issue was lying around somewhere. Do you think that makes sense for the above use-case though? The setting isn't really "sensitive" - we just want to hide the field in our UI (hence `kind: hidden`).

From https://github.com/meltano/sdk/issues/347:

> ## Example
> ### `oauth_credentials.access_token` Setting
>  Configuration for an `oauth_credentials.access_token` setting should be both hidden from the user, and stored encrypted.
>
>  In this case we need
>
>  kind: password
>  hidden: true
>  ### `oauth_credentials.scope` Setting
>  Configuration for an `oauth_credentials.scope` setting is not sensitive, but does not need to be shown to the user for configuration.
>  
>  In this case we need
>  
>  kind: string
>  hidden: true

**Comment by ReubenFrankel** [comment]
@tayloramurphy So `sensitive` is more-or-less a proposal to replace `kind: password`? I guess we haven't run into a problem with that in particular since most passwords resolve to a string anyway. I can definitely see a potential use-case for a non-string sensitive credential like a PIN or code, which currently is not possible due to conflict between `kind: integer` and `kind: password`.

Would you accept a PR to add new `sensitive` and `hidden` fields as drop-in replacements for the corresponding kinds (which could then be deprecated)?

`sensitive` I feel would be quite an involved change if it ties into a enhancement relating to how setting values are stored (i.e. requiring encryption/decryption) and displayed to the user from the CLI (e.g. `meltano config <plugin> list` or `meltano config set --interactive`). If this is the case, perhaps it's better to split the two changes up for now.

**Comment by tayloramurphy** [comment]
@ReubenFrankel let's keep the PR's small since changes like this may have larger effects than we intend. Pulling out `hidden` as a separate field would be a good first iteration and would inform us about what we're likely to run into for `password` vs `sensitive`. 

Also, we should do this in a backwards compatible way until we release 3.0 (which we're planning for same time as Python 3.7 EOL). cc @WillDaSilva
