### ISSUE TITLE
feature: Require user to run `meltano cloud project use` to set a default project 

### ISSUE THREAD

**Issue by magreenbaum** [meltano/meltano#7673]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Soon we will be creating organizations for new customers without creating a default project. Projects can/will be created by users soon. 
Once a user logs in, we will want them to use the projects API to set a default project rather than [parsing it](https://github.com/meltano/meltano/blob/739d0a75fb5420b715cee7256feed88b145adfbe/src/cloud-cli/meltano/cloud/api/config.py#L177-L206) from the `trk_and_pid` attribute since we won't be creating and setting a default.

We'll want to prompt the user to perform this action on login if a default project is not configured.

**Comment by tayloramurphy** [comment]
@magreenbaum from a user perspective, if they only have a single project couldn't we just use that as a default? Or as part of adding a project can we assume the first one they add is the default?

**Comment by WillDaSilva** [comment]
@tayloramurphy The key thing here is that we can no longer rely on the available projects being provided within the auth token. The user experience could involve manually calling `meltano cloud project use`, or we could automatically call `meltano cloud project list` and `use` the project if there's only one, but either way it'll go through the project API.

**Comment by WillDaSilva** [comment]
@tayloramurphy Understood, and no apologies necessary. I just want to make the motivation for this issue clear. Perhaps we should hit the project API on every login to see which projects are available, and select one automatically if there's only one.
