### ISSUE TITLE
docs: Rewrite cloud docs for Public Beta release

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/meltano#7709]
There are a lot of minor updates and improvements for the cloud docs that we need to make ahead of the public beta release.
We also need to fully rewrite the onboarding section to reflect the new onboarding workflow for public beta.

- [ ] Cloud landing page
  - [ ] Overview
  - [ ] Marketing copy
  - [ ] Link to waitlist
- [ ] CLI
  - [ ] history
    - [ ] Add full options list
  - [ ] run
    - [ ] Update help text
      - [ ] JOB_OR_SCHEDULE -> SCHEDULE_NAME
      - [ ] "Run a Meltano project" -> "Run a Meltano schedule"
  - [ ] schedule
    - [ ] list
      - [ ] Add full options list
- [ ] Concepts
- [ ] Connectors
- [ ] Encrypting secrets
- [ ] Meltano Cloud
  - [ ] Remove self-referential link
- [ ] Onboarding
  - [ ] Total rewrite
- [ ] Platform information
  - [ ] Clarify webhook setup workflow
- [ ] Security
  - [ ] Remove "Security Whitepaper" section
  - [ ] Double-check accuracy of GitHub app permissions section

**Comment by pnadolny13** [comment]
@cjohnhanson @tayloramurphy where did we land on this? I saw the PR for the onboarding docs update and deployment cli  but theres a still more in this [issue description](https://github.com/meltano/meltano/issues/7709#issue-1727989387) that are unfinished. Did those get moved to a different issue?

**Comment by tayloramurphy** [comment]
Only the onboarding piece was covered, but another pass across the docs is definitely warranted.
