### ISSUE TITLE
Interactively select Meltano Cloud log to print

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7756]
Currently the `--execution-id` needs to be specified for `meltano cloud log print`. When it is not provided, we should provide an interactive prompt that lists recent executions IDs with some extra info (similar to the `history` command), and allows one to be selected.

**Comment by tayloramurphy** [comment]
@WillDaSilva love this. That would be so much nicer. 

We could also have a "view in app" command / link too 👀
