### ISSUE TITLE
Cloud CLI command to open the UI

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7757]
@tayloramurphy requested this feature during office hours on 2023-06-07

**Comment by tayloramurphy** [comment]
@WillDaSilva thoughts on the command? `meltano-cloud ui` doesn't feel quite right. maybe `meltano-cloud app`?

**Comment by WillDaSilva** [comment]
@tayloramurphy I'm not sure. Maybe `meltano cloud web`?

**Comment by tayloramurphy** [comment]
@WillDaSilva I like web! @pnadolny13 any objections?

**Comment by pnadolny13** [comment]
I'd throw a few more in the mix - `dashboard` or `control panel`. I think we've been internally referring to it as the UI or app but that sort of makes it seem like its part of Meltano. Also `meltano-cloud app` on the CLI would make me think that its spinning up a web app locally.

**Comment by tayloramurphy** [comment]
@pnadolny13 `dashboard` is tempting but I like `web` since it's shorter.

**Comment by XshubhamX** [comment]
@WillDaSilva can I work on this?

**Comment by WillDaSilva** [comment]
@XshubhamX I wouldn't recommend doing so, since the Cloud CLI has not been merged in `main`, and we have no plans to do so in the foreseeable future.
