### ISSUE TITLE
bug: Error messages for 400 Bad Request in Cloud CLI do not show error message

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7762]
### Meltano Version

cloud branch

### Python Version

NA

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

N/A

### Description

We currently use the default exception handler for HTTP status code 400 Bad Request. Instead we should print the included error message.

**Comment by tayloramurphy** [comment]
@WillDaSilva I almost opened a new issue but I think this is covered here. With the error that we saw with Garrett (no schedules) what would the output be and the overall UX? Would it be obvious that it failed to deploy b/c schedules were missing?
