### ISSUE TITLE
Auto-use newly created deployments

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7771]
After creating a deployment, the default behaviour should be to set it as the default deployment to use for future commands. A message should be printed when the deployment is created stating that it will be used by default, and to run `meltano cloud deployment use` to change this.

**Comment by tayloramurphy** [comment]
@WillDaSilva is it possible to only do this if there already isn't a deployment? If a user is creating their 2nd deployment I don't know that it would make sense to automatically switch the default. 

We could print the recommended command to switch. `prod deployment created. To use as default run "meltano cloud deployment use --name prod"`

**Comment by WillDaSilva** [comment]
@tayloramurphy that behaviour sounds better, and would be just as easy to implement. Thanks for the suggestion.

**Comment by leoroese** [comment]
@WillDaSilva @tayloramurphy 

Should we also do some type of auto-use logic for when users delete deployments?

The 3 scenarios I am imagining for delete are
- Delete a deployment that isn't the default and > 1 left -- don't do anything.
- Delete the default and there are > 1 deployment -- Auto use the latest deployment? Provide option for them to choose new default from a list of deployments?
- Delete default and there is 1 deployment left -- auto use that final deployment
- Delete deployment and none left -- Don't do anything

If so, should I track this in a new issue or just add the work to part of this one.

**Comment by WillDaSilva** [comment]
@leoroese Those are good scenarios to consider, but I don't think we will want to auto-use another deployment when the one selected is deleted.

We will want to update the config file to set the default deployment to `null`, but auto-using a new one may not be what the user wishes to do, whereas auto-using the one that has just been created if it's the only one deployment is what the user will want to do 99% of the time.

**Comment by leoroese** [comment]
@WillDaSilva That makes sense.

Not sure how valuable it would be, but I wonder if there was any way to monitor the combination of 
1. Delete default deployment
2. raised UsageError from run from missing a default deployment

to track the amount of users that are possibly expecting a default deployment to still work?

But raising this error and displaying the message for them to choose a new default (as we do now), seems like a better alternative to the user running a deployment that they didn't intend on, and therefore wasting credits.

**Comment by WillDaSilva** [comment]
Relates to:
- https://github.com/meltano/meltano/issues/7839
