### ISSUE TITLE
feature: Add copy button to code blocks in Getting Started

### ISSUE THREAD

**Issue by BraedonLeonard** [meltano/meltano#7778]
### Feature scope

Other

### Description

While running through the [Getting Started guide](https://docs.meltano.com/getting-started/), I noticed the lack of copy-to-clipboard buttons in the code blocks that you would see in most rendered Markdown. This makes the process of going through the guide a little slower and clunkier than it could otherwise be. 

By adding a copy button to all code blocks, it would be a lot quicker for users to run commands, copy file contents, etc., and would generally mean a smoother experience for new users.

**Comment by tayloramurphy** [comment]
Thanks for the issue @BraedonLeonard  - we're migrating to docusaurus this month and it will have the copy button for code blocks. I'm super excited about it 😄
