### ISSUE TITLE
bug: Valid options for `--interval` flag are unclear

### ISSUE THREAD

**Issue by BraedonLeonard** [meltano/meltano#7791]
### Meltano Version

2.19.1

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Mac OS - Ventura 13.4

### Description

When running `meltano schedule add --help`, the following is printed:
```
Usage: meltano schedule add [OPTIONS] NAME

      Add a new schedule. Schedules can be used to run Meltano jobs or ELT
      tasks at a specific interval.

      Example usage:

              # Schedule a job name "my_job" to run everyday
              meltano schedule add <schedule_name> --job my_job --interval "@daily"
              # Schedule an ELT task to run hourly
              meltano schedule add <schedule_name> --extractor <tap> --loader <target> --transform run --interval "@hourly"

      Note that the --job option and --extractor/--loader options are mutually exclusive.

      Read more at https://docs.meltano.com/reference/command-line-interface#schedule
          

Options:
  --interval TEXT                 Interval of the schedule.  [required]
  --job TEXT                      The name of the job to run.
  --extractor TEXT                ELT Only
  --loader TEXT                   ELT Only
  --transform [skip|only|run]     ELT Only
  --start-date [%Y-%m-%d|%Y-%m-%dT%H:%M:%S|%Y-%m-%d %H:%M:%S]
                                  ELT Only
  --help                          Show this message and exit.
  ```
  
For the `--interval` option, it does mention anywhere what format it accepts in the help message. You have to open the link to the CLI documentation to find out that it accepts cron expressions. 

The help message should be improved to state that interval accepts cron expressions and a set of presets, and then either list the presets or direct them to the link to view the presets.

**Comment by tayloramurphy** [comment]
@BraedonLeonard makes sense to me. There aren't that many options (mostly the same as https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dag-run.html#cron-presets) plus cron. Would be a quick win 🙌
