### ISSUE TITLE
bug: Discover command should not show hidden variants

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7796]
Similar to https://github.com/meltano/hub/pull/1377, sometimes users find hidden variants and get confused why they aren't working. We use the hidden property to allow backwards compatibility so they still exist but aren't advertised in searches. I still see the hidden `meltano` variant of target-snowflake when I run discover:

`target-snowflake, variants: transferwise (default), meltano, datamill-co, meltanolabs`

**Comment by tayloramurphy** [comment]
May not be relevant if we deprecate the command, but good to log for now.Related to:

* https://github.com/meltano/meltano/issues/7656

**Comment by edgarrmondragon** [comment]
The command was removed :)
