### ISSUE TITLE
docs: Tabs for code blocks with OS-specific instructions in Getting Started

### ISSUE THREAD

**Issue by BraedonLeonard** [meltano/meltano#7802]
### Feature scope

Other

### Description

In the Getting Started guide, there are code blocks like the following which contain commented commands for use by different OSes.

```bash
#For Windows (PowerShell): New-Alias Python3 Python
python3 -m pip install --user pipx
python3 -m pipx ensurepath
#For Windows (PowerShell): Open up a new powershell instance to load your new path variables
source ~/.bashrc
```

In these cases, it would be much nicer to have code blocks with separate tabs for each OS, like this:
<img width="772" alt="Screenshot 2023-06-14 at 12 08 49 PM" src="https://github.com/meltano/meltano/assets/10601513/77b341d3-eb70-4556-99ee-6ca14351879f">

This would be a much nicer user experience.

**Comment by tayloramurphy** [comment]
Love this!
