### ISSUE TITLE
bug: Getting Started uses airflow orchestrator instead of airflow utility

### ISSUE THREAD

**Issue by BraedonLeonard** [meltano/meltano#7804]
In the Getting Started guide, users are told to [add the airflow orchestrator](https://docs.meltano.com/getting-started/#schedule-pipelines-to-run-regularly) to their project:
```bash
meltano add orchestrator airflow
```

While doing some digging, I came across the [Airflow utility](https://hub.meltano.com/utilities/airflow), which states:
```
This utility plugin is meant to be used in favor of the [Airflow orchestrator plugin type](https://hub.meltano.com/orchestrators/airflow).
```

Given that the Airflow utility is something we manage, we should update the Getting Started guide to use the airflow utlity.

**Comment by tayloramurphy** [comment]
@BraedonLeonard I think it also still recommends the `transformer` for dbt instead of the utility too.
