### ISSUE TITLE
bug: Commands and tests fail with `ValueError` due to bug in Python 3.11.4

### ISSUE THREAD

**Issue by BraedonLeonard** [meltano/meltano#7813]
### Meltano Version

2.19.1

### Python Version

3.11

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

N/A

### Description

Python 3.11.4 introduced a [bug with inverting Flag enums](https://github.com/python/cpython/issues/105497). This breaks a lot of plugin-related functionality, like adding extractors, on Python 3.11, as well as causing tests in CI to fail on PRs. There's an MR backporting a fix for this to 3.11, but it hasn't been merged yet: https://github.com/python/cpython/pull/105571

If we wait for the fix to be merged and a new version cut, this issue will just go away, so I'm not sure if we want to do something about this in the meantime or just wait.

**Comment by WillDaSilva** [comment]
This has been fixed in Python 3.11.5. Once it has been released, we can revert https://github.com/meltano/meltano/pull/7821, and close this issue.

**Comment by edgarrmondragon** [comment]
3.11.5 is behind schedule: https://peps.python.org/pep-0664/#bugfix-releases

**Comment by edgarrmondragon** [comment]
Python 3.11.5 has been released. It's not yet [available to setup-python](https://github.com/actions/python-versions/blob/main/versions-manifest.json), though.

**Comment by edgarrmondragon** [comment]
We're testing on 3.11.5 now and even 3.11.4 seems to work: https://github.com/meltano/meltano/pull/8075
