### ISSUE TITLE
bug: `meltano schedule set` does not validate interval

### ISSUE THREAD

**Issue by BraedonLeonard** [meltano/meltano#7814]
### Meltano Version

2.19.1

### Python Version

3.10

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

N/A

### Description

If you pass an invalid interval to `meltano schedule add`, it will error:
```bash
(meltano-dev-3.10) braedon ~/meltano/projects/test-project $ meltano schedule add csv-to-jsonl --interval fakeinterval --extractor tap-csv --loader target-jsonl
Invalid Cron expression or alias: 'fakeinterval'. Please use a valid cron expression.
```

The same is not true for `meltano schedule set`:
```bash
(meltano-dev-3.10) braedon ~/meltano/projects/test-project $ meltano schedule set csv-to-jsonl --interval fakeinterval
Updated schedule 'csv-to-jsonl'
(meltano-dev-3.10) braedon ~/meltano/projects/test-project $ meltano schedule list
[fakeinterval] elt csv-to-jsonl: tap-csv → target-jsonl x transforms
```

The same validation should be done when setting the interval with `set` and `add`.

**Comment by tayloramurphy** [comment]
Good find! This would be a great quick fix and we came across this with a cloud customer.

**Comment by XshubhamX** [comment]
@BraedonLeonard Can I work on this?

**Comment by BraedonLeonard** [comment]
@XshubhamX Absolutely!
