### ISSUE TITLE
feat: Cloud - support secrets at the deployment level

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#7896]
As of July 2023 only supported at the project level

**Comment by WillDaSilva** [comment]
@tayloramurphy we currently _only_ support secrets at the project level. We do not support org-level secrets.

Unless you're referring to user permissions, in which case there is only the binary choice between no access, and full access to everything within an org.

**Comment by tayloramurphy** [comment]
@WillDaSilva thanks for the call out. I confused myself when quickly creating the issue. I updated to be deployment.
