### ISSUE TITLE
feat: Cloud option to download file-based artifacts

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#7905]
### Feature scope

Other

### Description

There's a few ideas here, so maybe warrants another issue. If a user runs `target-csv`, `target-jsonl`, or basically any file-based target, that data currently just disappears. We could store that for them and enable them to download it via the CLI and UI.

Similarly, as we work on #https://github.com/meltano/meltano/issues/7081 we should enable users the ability to download these artifacts from Cloud. 

We'd need to set some sort of deletion policy, but this could be a useful feature. 

Discussed with @visch :smile

**Comment by visch** [comment]
Thought about this more after the call (and happened to see this), this makes a lot of sense for me when I"m running with a job runner (Gitlab runner in my case) but if I was running on pure meltano cloud setting up a push to S3 or something wouldn't be that big of a deal as we'd be in Meltano's infra which would presumably allow outbound connections. This just avoids me having to ask folks to open up external output ports (if they lock them down) or any other web filters / etc that get in the way.

**Comment by dresslife-shbh** [comment]
@tayloramurphy can I pick this up?

**Comment by XshubhamX** [comment]
@tayloramurphy @edgarrmondragon can I pick this ?

**Comment by WillDaSilva** [comment]
@XshubhamX Generally I wouldn't recommend picking up any features for Meltano Cloud. Also, with this feature in particular, it would not be possible to support without changes to the backend for Meltano Cloud, which is not open source.
