### ISSUE TITLE
bug: Exception thrown due to missing environment variable for `database_uri` could be much clearer

### ISSUE THREAD

**Issue by anden-akkio** [meltano/meltano#8014]
### Meltano Version

2.20.0

### Python Version

3.11

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

MacOS

### Description

I'm getting this output:

```shell
$ meltano install
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

'NoneType' object has no attribute '_instantiate_plugins'
```

I've narrowed the root cause of this to be setting the `database_uri` value to `$MELTANO_DATABASE_URI` in a situation where that environment variable isn't actually set, then running `meltano install`.

While erroring out here is correct behavior, I feel this error could be much more descriptive. Googling it brings you here: https://stackoverflow.com/questions/61238025/attributeerror-nonetype-object-has-no-attribute-instantiate-plugins-canno

While this helped me get in the right ballpark of me figuring out what's going on, I feel the exception thrown here could be more descriptive.

**Comment by edgarrmondragon** [comment]
Thanks @anden-akkio! We could certainly improve that error message.

In the meantime you could use [`ff.strict_env_var_mode`](https://docs.meltano.com/reference/settings/#ffstrict_env_var_mode):

```console
$ export MELTANO_FF_STRICT_ENV_VAR_MODE=1
$ meltano config meltano list
2023-08-11T23:33:04.815294Z [info     ] The default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.
Environment variable 'MELTANO_DATABASE_URI' referenced but not set. Make sure the environment variable is set.
```
