### ISSUE TITLE
feature(cloud): Add way to unset a default project

### ISSUE THREAD

**Issue by leoroese** [meltano/meltano#8032]
### Feature scope

API

### Description

Currently once you set a default project there is no way to unset it. You must switch over to another project, would be nice if there was some command like `meltano cloud project unset` to unset default project.

This would be useful for when trying to set organization level notifications from the cli

**Comment by tayloramurphy** [comment]
Thanks for this issue @leoroese!

* https://github.com/meltano/meltano/issues/7790

☝️ is a somewhat related issue where you could achieve the same goal with `--all` on specific commands. It's not clear to me what allowing `unset` would do aside from doing things like fetching history from all projects (which would be covered by the all flag). 

I'm not sure which is more desirable. My intuition is that once you have a project in your org then it should be the default. The only way to not have a default project set would be to not have a project at all. Thoughts?

**Comment by leoroese** [comment]
The main reason for this ticket was in case we wanted to support organization level notifications without the need of an extra flag. Currently if you have a default project set, then all the notification CLI commands are narrowed to that trk_pid combination. I could just add the extra flag called `--scope` or something which defaults to project. The user could then provide --scope organization or --scope user to specify what type of notification they want to create.

**Comment by tayloramurphy** [comment]
@leoroese ah ok, that makes sense. Thanks for the clarification.
