### ISSUE TITLE
feature: Support authenticating to Azure state backend without a connection string

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8045]
### Feature scope

State backend

### Description

https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python?tabs=managed-identity%2Croles-azure-portal%2Csign-in-azure-cli#sign-in-and-connect-your-app-code-to-azure-using-defaultazurecredential

See request in

* Slack: https://meltano.slack.com/archives/CMN8HELB0/p1692386533863739?thread_ts=1692366917.319929&cid=CMN8HELB0
* Linen: https://www.linen.dev/s/meltano/t/15516560/hey-i-m-a-bit-confused-how-to-set-the-state-id-when-using-me#d65c3bd0-9e62-48dd-a616-90d4d7246d33

**Comment by XshubhamX** [comment]
@edgarrmondragon can I pick this up?

**Comment by edgarrmondragon** [comment]
@XshubhamX go for it 😄

**Comment by edgarrmondragon** [comment]
from @XshubhamX:

> 1. So right now when the client function https://github.com/meltano/meltano/blob/main/src/meltano/core/state_store/azure.py#L97 is called we just return a new BlobServiceClient if user has configured the connection string.
> 2. Now if we want to use the default credentials we can use the DefaultAzureCredential() funtion offered by the azure library.
> 3. And after getting these credentials we can initiate a new isntance BlobServiceClient using the credentials that we just fetched in above step and the account_url.
> 4. account_url = “https://<storageaccountname>.[blob.core.windows.net](http://blob.core.windows.net/)”
> 5. But he issue is that here also we’d require the user to configure the account_url which would basically mean that we need to have another state variable like `state_backend.azure.account_name`  and we’d allow user to configure this.

And some additional requirements:

1. document that leaving `state_backend.azure.account_name` unset will cause Meltano to try to use `state_backend.azure.connection_string`
2. give precedence to `DefaultAzureCredential()` and `state_backend.azure.account_name`,
3. and link to the official docs for instructions on where to find the account name
