### ISSUE TITLE
Validate input is a ULID for `meltano cloud project use --id`

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#8052]
If anything other than a ULID is provided, the command will succeed, and then future commands will error with an unclear error message.

We can avoid this problem by validating that the provided value for the `--id` option is a ULID.

Context in the internal Slack: https://internalmeltano.slack.com/archives/C05N4BJEQJE/p1692561545277719

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/meltano/pull/8055
