### ISSUE TITLE
bug: identical project names (unique ids) causes interactive project selection to fail

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#8056]
```
❯ meltano-cloud project use
2023-08-21 16:33:31 [debug    ] Making Cloud CLI HTTP request  method=GET url=https://internal.api.meltano.cloud/projects/v1/01GV0Z1VW5TSRF8BYX1J2V3WNT
Error: Multiple Meltano Cloud projects have the same name. Please specify the project using the `--id` option with its internal ID, shown below. Note that these IDs may change at any time. To avoid this issue, please use unique project names.
01GGWBJ538JBBW4TV91E4ST1PF: Meltano Squared ('https://github.com/meltano/squared.git')
01GVR8N319XJPPG9C8184GCKQB: private-meltano-demo-in-a-box ('https://github.com/meltano/meltano-demo-in-a-box.git')
01H7GHXGAZAXGHZR3WPJ1RS2QE: cody-test-9 ('https://github.com/meltano/test-project-9 --root-path /some/path\n\n.git')
01H7GHY1EH9EMMBRF98N5YJF99: cody-test-9 ('https://github.com/meltano/test-project-9.git')
01H8D07597KR2Y474SSJG3CTT2: taylor-test2 ('https://github.com/meltano/squared.git')
```

**Comment by WillDaSilva** [comment]
> bug: identical project names (unique ids) causes interactive project selection to fail

@tayloramurphy Project names are not unique, and we don't use them as an identifier in any context. They are arbitrary unicode labels. Same with org names. We use the ULIDs as the unique IDs for both of these.

**Comment by tayloramurphy** [comment]
* https://github.com/meltano/meltano/issues/8057

☝️ is related. @WillDaSilva my parenthetical about unique ids was to show that the project names were the same but the ids are unique which is expected but I wanted to cover my bases. 

How does a user fix this situation though? We'd need to be able to rename the offending project or reach out to support to remove it currently. It does feel weird that we say "Project names are not unique, and we don't use them as an identifier in any context" but then interactive fails b/c the arbitrary labels are the same.

**Comment by WillDaSilva** [comment]
@tayloramurphy The plan was to let users edit some metadata for projects such as their name themselves, following:
- https://github.com/meltano/meltano/pull/7620

@cjohnhanson and I discuss that a bit here:
- https://github.com/meltano/infra/pull/1539#discussion_r1276803598

Given the recent reprioritization, this feature likely won't be implemented for a long time. Users will have to make requests to Meltano Cloud support for these sorts of changes. Fortunately they're very easy for us to make. You need only rename the project name field in the appropriate DynamoDB item.
