### ISSUE TITLE
bug: State cleared when answering 'no' to confirmation prompt

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/meltano#8114]
### Meltano Version

2.20.0

### Python Version

3.7 (deprecated)

### Bug scope

API

### Operating System

Linux - Ubuntu 22.04

### Description

Running `meltano state clear <state id>` and answering `n` (or other variation signifying 'no') for the confirmation prompt results in the state being cleared anyway.

![image](https://github.com/meltano/meltano/assets/60552974/f26a3666-c6ff-4f92-b8eb-e4a621ea0fdc)

**Comment by edgarrmondragon** [comment]
Seems like a quick fix
