### ISSUE TITLE
feature:  Set the meltano.yml path in a directory different from the project 

### ISSUE THREAD

**Issue by leandroimail** [meltano/meltano#8130]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

I really tried to make a docker container with meltano to run in AWS Lambda, but I had a lot of problems because in my case I needed to change meltano.yml in run time, but only possible to change files in AWS Lambda if this file is in /tmp.

I believe could be a great feature if it is possible to set meltano.yml path by a environment variable. I tried to change this meltano source code but I had problems with the plugins installations. These changes are beyond my skills. 

So I propose this new feature like other projects have (DBT as an example), where it is possible set a new configuration file or set a path for the configuration file.

**Comment by edgarrmondragon** [comment]
Hi @leandroimail, thanks for logging an issue!

There's `--cwd`:

```console
$ meltano --cwd /path/to/project/root ...
```

Which lets you point to a _project directory_ that contains a `meltano.yml` file.

It's a global CLI option, but it's not documented in https://docs.meltano.com/reference/command-line-interface#global-configuration. It probably should, if you're still interested in contributing 😉.

**Comment by XshubhamX** [comment]
@edgarrmondragon can I work on this?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon can I work on this?

Sure! This merely needs documentation so you may want to make changes in https://github.com/meltano/meltano/tree/b26b9bfffa37e89a168dabffb4ef625a1c91fcf7/docs.

**Comment by XshubhamX** [comment]
@edgarrmondragon Below mention PR closes this.
https://github.com/meltano/meltano/pull/8156

**Comment by edgarrmondragon** [comment]
Closed by #8156

**Comment by edgarrmondragon** [comment]
Thanks @XshubhamX!
