### ISSUE TITLE
bug: Top-level ordered lists are not rendered correctly in docs

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8174]
### Meltano Version

3.0.0

### Python Version

NA

### Bug scope

Other

### Operating System

NA

### Description

See https://docs.meltano.com/reference/command-line-interface/#add

<img width="1785" alt="Screenshot 2023-09-21 at 9 12 11" src="https://github.com/meltano/meltano/assets/16805946/9c61a674-cf6b-440c-a2ee-e1014808129f">

cc @tayloramurphy

**Comment by tayloramurphy** [comment]
@edgarrmondragon seems like there's a lot of examples of this in the docs 👀 I'll ping brightscout.
