### ISSUE TITLE
bug: Can't install meltano-map-transformer on Meltano v3

### ISSUE THREAD

**Issue by peterspiro** [meltano/meltano#8224]
### Meltano Version

3.1.0

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

OSX

### Description

I'm getting the error:
```
Mapper 'meltano-map-transformer' is not known to Meltano. Try running `meltano lock --update --all` to ensure your plugins are up to date.
```
when I try to either install `meltano-map-transformer` or run a job containing a mapping.  The error isn't resolved by running `meltano lock --update --all`.

The error doesn't occur with Meltano v2.  It looks like it may have been introduced by https://github.com/meltano/meltano/pull/7992.

### Code

```python
mappers:
    - name: meltano-map-transformer
      pip_url: "git+https://github.com/MeltanoLabs/meltano-map-transform.git"
      executable: meltano-map-transform
      mappings:
        - name: rename_column
          config:
            stream_maps:
              demographics:
                foo_text: foo
                foo: null
```

**Comment by edgarrmondragon** [comment]
Here's a potential workaround:

1. Remove `meltano-map-transformer` from the project
1. Use [`--from-ref`](https://docs.meltano.com/reference/command-line-interface/#how-to-use) to add the plugin

   ```shell
   meltano add mapper meltano-map-transformer --from-ref https://raw.githubusercontent.com/meltano/hub/main/_data/meltano/mappers/meltano-map-transformer/meltano.yml
   ```

1. Add your `mappings`

**Comment by peterspiro** [comment]
Thanks @edgarrmondragon, that worked.  It seems that the `namespace` config element is now required.

**Comment by edgarrmondragon** [comment]
I'd rathe keep this open since the workaround makes the mapper a [custom plugin](https://docs.meltano.com/tutorials/custom-extractor/#interacting-with-your-new-plugin). We probably want the plugin work when added with `meltano add mapper meltano-map-transformer`.

**Comment by edgarrmondragon** [comment]
Related:

* https://github.com/meltano/meltano/issues/8563

**Comment by edgarrmondragon** [comment]
This is no longer an issue 🎉
