### ISSUE TITLE
bug: Select doesn't show % characters

### ISSUE THREAD

**Issue by visch** [meltano/meltano#8244]
### Meltano Version

3.1.0

### Python Version

3.10

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Ubuntu 20.04 (WSL)

### Description

I have a tap with properties that have a "%" in the name 

Example

```
visch@DESKTOP-9BDPA9T:~/git/meltano-projects/ait-mssql-snowflake$ meltano select tap-mssql --list
2023-10-27T15:03:27.475043Z [info     ] The default environment 'dev' will be ignored for `meltano select`. To configure a specific environment, please use the option `--environment=<environment name>`.
Legend:
        selected
        excluded
        automatic

Enabled patterns:
        *test*.*

Selected attributes:
        [selected ] dbo-test.APN
        [selected ] dbo-test.test
        [selected ] dbo-test.testcolum
 ```
 
 
 Meltano works properly with the tap and I get output like
 
 ```
 {"type": "RECORD", "stream": "dbo-test", "record": {"testcolum": "col1", "APN % Issue": "col3", "test%column": "col2"}, "version": 1698418991197, "time_extracted": "2023-10-27T15:03:11.205010Z"}
 ```
 
 So it looks to just be a UI thing

**Comment by visch** [comment]
https://github.com/meltano/meltano/blob/main/src/meltano/core/plugin/singer/catalog.py#L250 looks to be the culprit as if you swap this function to just return `path` things work as expected. More to this than just that so it seems so I'll leave it there!

**Comment by tayloramurphy** [comment]
@edgarrmondragon may be worth taking a look at this one.

**Comment by edgarrmondragon** [comment]
PR's up: https://github.com/meltano/meltano/pull/8249
