### ISSUE TITLE
bug: Invisible email address - `Subscribe`

### ISSUE THREAD

**Issue by mbiesiad** [meltano/meltano#8277]
### Meltano Version

NA

### Python Version

NA

### Bug scope

Other

### Operating System

NA

### Description

Hi,
 
**Repro steps**: 
Visit https://meltano.com/ and scroll down to see `Subscribe` button - click, type your email address.

**Result:**
![image](https://github.com/meltano/meltano/assets/18367606/cddccb8e-b766-400a-b568-f93306d300f8)
Invisible email address - used CTRL+A there:
![image](https://github.com/meltano/meltano/assets/18367606/2dff90bd-f42b-434c-abea-abe2b8a5bf52)

**Additional information:**
Checked using Firefox and different Chromium based browsers.

Best wishes,

**Comment by sbalnojan** [comment]
should be fixed
