### ISSUE TITLE
bug: Interactive config prompt should indicate when you're typing a redacted value

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8299]
### Meltano Version

3.1.0

### Python Version

NA

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

NA

### Description

`New value` should probably be `New value (redacted)`:

https://github.com/meltano/meltano/blob/eee71ac0209071bc7174feff1ea26329808abe2a/src/meltano/cli/interactive/config.py#L242-L248

**Comment by abastola0** [comment]
@edgarrmondragon  can you assign me this issue?

**Comment by edgarrmondragon** [comment]
Done @abastola0!

**Comment by abastola0** [comment]
@edgarrmondragon Lmk if there's anything else to change.
