### ISSUE TITLE
Meltano Community Slack currently unavailable - Use https://discuss.meltano.com as an alternative

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/meltano#8308]
@tayloramurphy here - Hijacking Reuben's comment to provide an update. As of 2023-12-08 12:00 PM CST we're working with Slack to restore access. Something went wrong on the Slack side as part of a migration for Arch. 

### Update as of 2023-12-15 - join us on https://discuss.meltano.com which is an alternative frontend to Slack, which has the full history of the slack workspace. From there you can sign in with GitHub or email and we can continue the conversation. Thanks for your patience

----

(sorry for the unrelated issue, wasn't sure where else to contact)

![image](https://github.com/meltano/meltano/assets/60552974/a50f3503-f5f3-44e8-95bf-d36d9f242dfb)
![image](https://github.com/meltano/meltano/assets/60552974/1a9973c0-c6f3-41c0-96ef-b5f1ca17eea1)

**Comment by WillDaSilva** [comment]
@ReubenFrankel Thanks for opening this issue. I was also having trouble accessing Slack a couple hours ago. I can't say for certain when it'll be available again, but please rest assured that we're aware of it, and working to bring it back.

**Comment by pnadolny13** [comment]
The team is aware of this and is still working with Slack to get it resolved. Thanks for the patience!

**Comment by ReubenFrankel** [comment]
An update for anyone coming across this just now: https://www.linkedin.com/posts/meltano_slack-activity-7140467510855843840-qX5h

**Comment by sbalnojan** [comment]
@ReubenFrankel (& everyone else listening in): Thanks for the pointer! 

**There's more:** We fixed the linen workspace - that means everyone can still participate in the Slack community via the linen integration: https://discuss.meltano.com/c/best-practices.

(But we will get the Slack version up and running again!)

**Comment by ReubenFrankel** [comment]
Should this be closed now?

**Comment by tayloramurphy** [comment]
We're back! Come join us at meltano.com/slack !
