### ISSUE TITLE
perf: Project's `.env` contents are evaluated too many times

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8342]
### Meltano Version

3.2.0

### Python Version

NA

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

NA

### Description

The `Project.dotenv_env` is evaluated many times per run, so a potential performance improvement would be to cache it:

https://github.com/meltano/meltano/blob/19197396dee4145b039f70210a172ef72c1f464e/src/meltano/core/project.py#L375-L382

#### Justification

See this flamegraph provided by @TyShkan: https://static.main.linendev.com/attachments/876cebd1-f3ad-485c-81a0-4b1cc971bc6a/profile.svg

#### Measuring performance

It would be nice to have https://github.com/meltano/meltano/issues/8341 in place before implementing this so we get a measure of the improvement but it's probably not a hard requirement.

**Comment by TyShkan** [comment]
Hey, @edgarrmondragon, nicely done! Small steps in code, but huge impact on performance (:

Do you have estimates when the changes could reach a release version?
