### ISSUE TITLE
bug: `UnicodeDecodeError` when processing plugin's output for logging

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8377]
### Meltano Version

3.3.0

### Python Version

NA

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Windows, probably

### Description

This line https://github.com/meltano/meltano/blob/42f0fc6895da3265d0fede67fae09cd37b7843f1/src/meltano/core/logging/utils.py#L208

could probably be made safer by passing `errors="replace"`[^1] to the `.decode()` method.

[^1]: https://docs.python.org/3.12/library/stdtypes.html#bytes.decode

**Comment by nkclemson** [comment]
Hi. I am a Django developer with six years of experience. I would like to start contributing to `meltano` starting with this issue if there is no problem then. Would it be possible to assign this to me?

**Comment by edgarrmondragon** [comment]
Go for it @nkclemson!

**Comment by nkclemson** [comment]
Does anyone know the error log text to test this bug? I can add normal Unicode text and use `.decode('utf-8', errors='ignore')` in the code, but I want to make sure this is the reason the bug was raised.

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/meltano/meltano/pull/8399
