### ISSUE TITLE
Directory creation with MELTANO_PROJECT_READONLY

### ISSUE THREAD

**Issue by gictor** [meltano/meltano#8401]
### Meltano Version

3.3.1 && 2.20.0

### Python Version

3.9

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

Official docker image / Ubuntu 22.04 / Kubernetes

### Description

When using the env. variable 
`MELTANO_PROJECT_READONLY=true` 
meltano still writes to project structure during `meltano run`
In the case below i have we use both `meltano install --clean` and `meltano invoke dbt-bigquery:deps` during docker build, then during runtime meltano tries to write to the extractors folder.

As a sidenote, it was fixable with creating `.meltano/extractors/venv`-folder manually, but it does not seem like the right thing to do since there is a "project_readonly"-variable.

### Code

```python
Output 1:
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

[Errno 30] Read-only file system: '/project/.meltano/extractors/<extractor name>'

Output 2: 
root@7e978fadb393:/project# inotifywait .meltano/extractors/
Setting up watches.
Watches established.
.meltano/extractors/ CREATE,ISDIR <extractor name>
```

**Comment by edgarrmondragon** [comment]
@gictor Thanks for logging

> then during runtime meltano tries to write to the extractors folder.
> 
> As a sidenote, it was fixable with creating `.meltano/extractors/venv`-folder manually, but it does not seem like the right thing to do since there is a "project_readonly"-variable.

Does this mean the `.meltano/extractors/venv` folder didn't exist at runtime? Meltano still needs to be able to write to the filesystem to dump the temporary plugin config files.

**Comment by gictor** [comment]
thanks for your reply @edgarrmondragon 

Exactly, the venv-folders are not created during `meltano install` but during `meltano run`

I'm cool with giving meltano space for writing, it would just be nice to have a clear view of where and why it needs to be writable.

/project/.meltano/run/
/project/.meltano/logs/
/project/transform/logs
/project/transform/target

This is a good start, but, I'm unsure if I'm alone with running meltano inside a docker container. Then if we mount `.meltano/extractors` during runtime, then we lose the binaries that were installed during `meltano install` (this we do during docker build).

**Comment by edgarrmondragon** [comment]
> I'm unsure if I'm alone with running meltano inside a docker container

You're certainly not alone!

> Then if we mount .meltano/extractors during runtime

I'm curious what's the use case for mounting that directory at runtime.

**Comment by gictor** [comment]
Thanks for your reply @edgarrmondragon 

So one of the best practices in Kubernetes is that your container is immutable.

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

If my whole container is immutable, the issue I'm getting in runtime is

`[Errno 30] Read-only file system: '/project/.meltano/extractors/<extractor name>'`

Because meltano run tries to create first
`/project/.meltano/extractors/<extractor name>` and
`/proect/.meltano/extractors/<extractors name>/venv`

What's i expect is that `meltano install` does create all directories needed to run and that the run command does _not_ go out and create new directories in runtime. Does that make any sense?

**Comment by edgarrmondragon** [comment]
> What's i expect is that `meltano install` does create all directories needed to run and that the run command does _not_ go out and create new directories in runtime. Does that make any sense?

@gictor That's my expectation too and `meltano install` does create those directories. I think the problem in your environment is that for some reason they don't exist by the time you run `meltano run`. I'm not sure why that's the case though, if you're running `meltano install` at image build-time.

Are you by chance using stages to build your docker image, or something similar that may cause the directories created by `meltano install` to be lost by the time `meltano run` is called?

**Comment by gictor** [comment]
Thanks for your reply @edgarrmondragon 

Could it be that directories for taps that "inherit_from" are not created until runtime?

To be a bit more specific, this is what my `.meltano/extractors` looks during my `docker build` straight after `meltano install --clean`

```
#23 [19/19] RUN ls -al .meltano/extractors/
#23 1.995 total 40
#23 1.995 drwxr-xr-x 9 meltano meltano 4096 Mar  8 14:24 .
#23 1.995 drwxr-xr-x 1 meltano meltano 4096 Mar  8 14:24 ..
#23 1.995 drwxr-xr-x 3 meltano meltano 4096 Mar  8 14:24 tap-braintree
#23 1.995 drwxr-xr-x 3 meltano meltano 4096 Mar  8 14:24 tap-csv-fmcsa-census
#23 1.995 drwxr-xr-x 3 meltano meltano 4096 Mar  8 14:24 tap-currencyfreaks
#23 1.995 drwxr-xr-x 3 meltano meltano 4096 Mar  8 14:24 tap-facebook
#23 1.995 drwxr-xr-x 3 meltano meltano 4096 Mar  8 14:24 tap-hubspot
#23 1.995 drwxr-xr-x 3 meltano meltano 4096 Mar  8 14:24 tap-postgres
#23 1.995 drwxr-xr-x 3 meltano meltano 4096 Mar  8 14:24 tap-rawpostgresql-yobify
#23 DONE 2.0s
```

Great, it does create some directories!

But then we have this extractor
```
    - name: tap-postgres-meltano
      inherit_from: tap-postgres
 ```

That writes to this directories during runtime
```
 .meltano/extractors/tap-postgres-meltano/venv
```

**Comment by edgarrmondragon** [comment]
Ah, that's very helpful @gictor!

Inherited plugins indeed don't create those directories at install time, but they're created by their respective invokers.

Using `sys.audit`[^1] within the main entry point:

```python
def main():
    """Entry point for the meltano CLI."""
    def audit(event, args):
        if event == 'os.mkdir':
            print(f'audit: {event} with args={args}')
            if args[0].endswith('venv'):
                raise OSError('audit hook test')
    sys.addaudithook(audit)
```

I was able to track where the offending `os.mkdir` call is made to:

https://github.com/meltano/meltano/blob/74d826f3ccbe03ccc986fafa229dec7cdcaab782/src/meltano/core/plugin_invoker.py#L393

Now, I first assumed based on `Project.venvs_dir` being decorated with `@makedirs`

https://github.com/meltano/meltano/blob/74d826f3ccbe03ccc986fafa229dec7cdcaab782/src/meltano/core/utils/__init__.py#L388-L403

would mean that passing `make_dirs` to `venvs_dir` would be enough to not create the directory. Unfortunately it seems the decorator is not recursive, and because `venvs_dir` calls `meltano_dir`

https://github.com/meltano/meltano/blob/74d826f3ccbe03ccc986fafa229dec7cdcaab782/src/meltano/core/project.py#L419

Then the directory is created regardless.

---

So, the solution probably involves finding a way of making the decorated recursive or explicitly passing a `make_dirs=...` kwarg to those calls.

[^1]: https://docs.python.org/3/library/sys.html#sys.audit
