### ISSUE TITLE
Replace use of flakeheaven with Ruff for pep8-naming

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8402]
* Disable the flakeheaven plugin in `pyproject.toml`
* Migrate to Ruff's `Nxxx` rules
* Remove additional dependency from `pre-commit-config.yaml`

**Comment by nkclemson** [comment]
Hi @edgarrmondragon, Can I work on this?

**Comment by edgarrmondragon** [comment]
Go for it @nkclemson!
