### ISSUE TITLE
feature: Use `uv` for managing plugin virtual envs?

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8410]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

`uv`[^1] is a tool created by the Astral team (of Ruff fame). It's a drop-in replacement for _most_ of the functionality of both `pip` and `virtualenv`, but  faster (10x-100x).

It's probably not a good idea to think of replacing `pip` and `virtualenv` with it this early, but it could initially be added behind a feature flag.

### Blockers

The following bugs and missing features are probable blockers for this integration:

- https://github.com/astral-sh/uv/issues/313
- https://github.com/astral-sh/uv/issues/1396

[^1]: https://github.com/astral-sh/uv

**Comment by edgarrmondragon** [comment]
cc @BTheunissen

**Comment by edgarrmondragon** [comment]
In particular `uv pip install --link-mode=hard-link` seems like an interesting option for boosting performance of (Python) plugin installation:

```
      --link-mode <LINK_MODE>
          The method to use when installing packages from the global cache
          
          [default: clone]

          Possible values:
          - clone:    Clone (i.e., copy-on-write) packages from the wheel into the site packages
          - copy:     Copy packages from the wheel into the site packages
          - hardlink: Hard link packages from the wheel into the site packages
```

**Comment by WillDaSilva** [comment]
@edgarrmondragon is the `clone` option only supported on particularly file systems? If so, which ones? What does it fall back to if copy-on-write is not possible, or does it just error instead? Is there a practical risk that the hardlinks break, e.g. if the cache is cleared?

**Comment by edgarrmondragon** [comment]
> is the `clone` option only supported on particularly file systems? If so, which ones?

Here's a good summary[^1] of OS/FS support:

<table>
            <thead>
              <tr>
                <th scope="col"><abbr title="Operating system">OS</abbr></th>
                <th scope="col"><abbr title="File system">FS</abbr></th>
                <th scope="col">Copy command</th>
                <th scope="col">System call</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th rowspan="6" scope="row">Linux</th>
                <td>Bcachefs</td>
                <td class="table-good" rowspan="4"><code class="notranslate" translate="no">cp --reflink=always</code></td>
                <td class="table-good" rowspan="4"><code class="notranslate" translate="no">ficlone</code></td>
              </tr>
              <tr>
                <td>Btrfs</td>
              </tr>
              <tr>
                <td>XFS</td>
              </tr>
              <tr>
                <td>OCFS2</td>
              </tr>
              <tr>
                <td>Ext4</td>
                <td class="table-bad" colspan="2" rowspan="4">Unsupported.</td>
              </tr>
              <tr class="webcompatfix-table-rowspan-broken">
                <td rowspan="2">OpenZFS</td>
              </tr>
              <tr>
                <th rowspan="2" scope="row">FreeBSD</th>
              </tr>
              <tr>
                <td>ZFS</td>
              </tr>
              <tr>
                <th scope="row">Solaris</th>
                <td>Oracle ZFS</td>
                <td class="table-good"><code class="notranslate" translate="no">cp -z</code></td>
                <td class="table-good"><code class="notranslate" translate="no">reflink</code></td>
              </tr>
              <tr>
                <th rowspan="2" scope="row">MacOS</th>
                <td><abbr title="Apple File System">APFS</abbr></td>
                <td class="table-good"><code class="notranslate" translate="no">cp -c</code></td>
                <td class="table-good"><code class="notranslate" translate="no">clonefile</code></td>
              </tr>
              <tr>
                <td>HFS+</td>
                <td class="table-bad" colspan="2" rowspan="2">Unsupported; non-<abbr title="copy-on-write">CoW</abbr> <abbr title="File system">FS</abbr>.</td>
              </tr>
              <tr>
                <th rowspan="2" scope="row">Windows</th>
                <td>NTFS</td>
              </tr>
              <tr>
                <td>ReFSv2</td>
                <td class="table-bad">Not included.</td>
                <td class="table-good"><code class="notranslate" translate="no"><span>DUPLICATE_</span><span>EXTENTS_</span><span>TO_</span>FILE</code></td>
              </tr>
            </tbody>
          </table>

And they seem to be using `reflink-copy`[^2], which has the following to say:

<blockquote>

At the moment Linux, Android, OSX, iOS, and Windows are supported.

Note: On Windows, the integrity information features are only available on Windows Server editions starting from Windows Server 2012. Client versions of Windows do not support these features. [More Information](https://learn.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_set_integrity_information)

</blockquote>

---

> What does it fall back to if copy-on-write is not possible, or does it just error instead?

Currently it errors. `reflink-copy` does have a simple copy fallback[^3] available and its being reviewed[^4] in `uv`.

---

> Is there a practical risk that the hardlinks break, e.g. if the cache is cleared?

I've only done simple testing so AFAICT they should be pretty safe, i.e. each hardlink is a reference so the same file on disk, and deleting a copy only deletes a reference so deleting uv's cache doesn't affect installed wheels.

[^1]: https://www.ctrl.blog/entry/file-cloning.html
[^2]: https://docs.rs/reflink-copy/latest/reflink_copy
[^3]: https://docs.rs/reflink-copy/latest/reflink_copy/fn.reflink_or_copy.html
[^4]: https://github.com/astral-sh/uv/pull/1773

**Comment by edgarrmondragon** [comment]
https://github.com/astral-sh/uv/pull/1773

**Comment by edgarrmondragon** [comment]
https://github.com/astral-sh/uv/issues/313 might not be a deal-breaker if we keep uv optional and instruct users to update their `pip_url`s
