### ISSUE TITLE
feature: System database support for AWS S3

### ISSUE THREAD

**Issue by menzenski** [meltano/meltano#8435]
### Feature scope

Configuration (settings parsing, validation, etc.)

### Description

It would be great to have Meltano able to write `runs` data to AWS S3. S3 is a supported "state backend" (so Meltano can write state there) but it's not a supported "system database" (so Meltano cannot write runs data there).

We currently run Meltano using a Postgres system database and have become accustomed to having the `runs` table data available. However we'd like to retire this Postgres database and have been standing up a Meltano project using the S3 state backend. I am now realizing that this means we will no longer have runs data available to us.

**Comment by edgarrmondragon** [comment]
Hey Matt, thanks for filing!

Can you say more about how you're using the `runs` table? Is it something that you glance at occasionally, or are some of your workflows dependent on it?

---

I'm trying to think what this would look like. State backends are essentially key-value stores so it's easy to use object storage for that, but the runs table is more transactional.

See for example how the job/run model is used within a transaction to keep a heartbeat

https://github.com/meltano/meltano/blob/bcbe3eb465e258efa818a97a43f8fe637a24220e/src/meltano/core/job/job.py#L249-L280

and to control concurrency

https://github.com/meltano/meltano/blob/bcbe3eb465e258efa818a97a43f8fe637a24220e/src/meltano/core/block/extract_load.py#L477-L499

I'm happy to discuss spec and implementation proposals, and even review PRs, but this is something that we probably won't prioritize ourselves.

---

That said, one option that may be available today is to rely on the default SQLite system db and use something like Litestream[^1] to sync the database with S3.

[^1]: https://litestream.io Litestream - Streaming SQLite Replication

**Comment by edgarrmondragon** [comment]
Another idea that just came to mind is to search for or implement a sqlalchemy dialect that's sqlite + s3, so it could be used like the example in https://github.com/meltano/meltano/issues/7143#issuecomment-1690040370.

The individual components seem to be out there:

* https://github.com/uktrade/sqlite-s3vfs

  Although this is concerning

  > No locking is performed, so client code must ensure that writes do not overlap with other writes or reads. If multiple writes happen at the same time, the database will probably become corrupt and data be lost.

* https://rogerbinns.github.io/apsw/vfs.html

* https://github.com/edgarrmondragon/sqlalchemy-sqlean/blob/206f86df0a325a9d853d5afb066d26cbcddd41d7/src/sqlean_driver/__init__.py (Example of a SQLite driver implementation)

**Comment by menzenski** [comment]
> Can you say more about how you're using the runs table? Is it something that you glance at occasionally, or are some of your workflows dependent on it?

We don't have anything today that depends on it specifically. We query it manually, occasionally, for debugging purposes.

As we build out our "second-generation" Meltano platform, though, we would like to better implement "reporting and analytics on our ELT workflows" - ideally we'd be able to e.g. surface in a dashboard which ELT jobs have run recently, succeeded, failed, etc.

We run Meltano in Kubernetes via Argo Workflows and we have [the Argo Workflows workflow archive](https://argo-workflows.readthedocs.io/en/latest/workflow-archive/) set up, so all Argo Workflows executions are recorded in a database today. A Meltano run corresponds to exactly one Argo Workflows run, so we still have good information available on what Meltano jobs ran when, succeeded, failed, etc.

The part I'm thinking about specifically as a potential limitation is not having the "payload" field from the meltano runs table available. It seems like it'd be useful to have that explicitly persisted - it seems to provide the value of the replication key for each stream in the run, at the start of the run.

**Comment by menzenski** [comment]
The other thought I had is that we're moving from Postgres into Snowflake for our warehouse. System database support for Snowflake would accomplish the same goal for us (continue to leverage a persistent state backend without running a Postgres database).

**Comment by edgarrmondragon** [comment]
> We don't have anything today that depends on it specifically. We query it manually, occasionally, for debugging purposes.
> 
> As we build out our "second-generation" Meltano platform, though, we would like to better implement "reporting and analytics on our ELT workflows" - ideally we'd be able to e.g. surface in a dashboard which ELT jobs have run recently, succeeded, failed, etc.
> 
> We run Meltano in Kubernetes via Argo Workflows and we have [the Argo Workflows workflow archive](https://argo-workflows.readthedocs.io/en/latest/workflow-archive/) set up, so all Argo Workflows executions are recorded in a database today. A Meltano run corresponds to exactly one Argo Workflows run, so we still have good information available on what Meltano jobs ran when, succeeded, failed, etc.
> 
> The part I'm thinking about specifically as a potential limitation is not having the "payload" field from the meltano runs table available. It seems like it'd be useful to have that explicitly persisted - it seems to provide the value of the replication key for each stream in the run, at the start of the run.

Thanks for adding context! That makes sense. The `payload` field can indeed give some insight into "state evolution" of a tap and its streams, which can be valuable.

> The other thought I had is that we're moving from Postgres into Snowflake for our warehouse. System database support for Snowflake would accomplish the same goal for us (continue to leverage a persistent state backend without running a Postgres database).

Yeah, that's been asked in Slack before. The `database_uri` is a SQLAlchemy URL, so in theory you could point it to a snowflake instance by setting it to `'snowflake://<user_login_name>:<password>@<account_name>/<database_name>/<schema_name>?warehouse=<warehouse_name>&role=<role_name>'`[^1].

Now, I recall that doesn't work because at least one of the migration scripts is not compatible with snowflake's sql so changes would be required there (see https://github.com/meltano/meltano/issues/6529 and https://github.com/meltano/meltano/pull/6167). Do log an issue for it if a Snowflake support for systemdb would make this transition easier for you, and of course PRs would be welcome 😄.

[^1]: https://github.com/snowflakedb/snowflake-sqlalchemy/?tab=readme-ov-file#connection-parameters

**Comment by menzenski** [comment]
After some further considerations we've decided that it's actually not feasible to retire our Postgres database. We plan to continue to use it for the Meltano system database (and for some other metadata capturing, Argo Workflows archive etc).

So, from my perspective this issue could be closed.
