### ISSUE TITLE
feature: Capture run ID

### ISSUE THREAD

**Issue by menzenski** [meltano/meltano#8458]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

We run meltano in Kubernetes using Argo Workflows.

We use the Argo Workflows [workflow archive](https://argo-workflows.readthedocs.io/en/latest/workflow-archive/), so we have workflow execution data saved in Postgres there.

We use the Meltano [Postgres system database](https://docs.meltano.com/concepts/project/#system-database), so we have Meltano job run data saved in Postgres also.

But we don't have a way to join these two "job execution" data sets together. That is, we don't have a way to link "this specific argo workflow executed this specific Meltano run". We would like to be able to do that.

I am not sure exactly what would make the most sense here, or what would be easiest relative to existing behavior/functionality. But some things I can think of:

* If `meltano run` could accept a `--run-id=abc123` CLI argument or similar, that could be persisted as part of the `runs` table record for that run.
* If `meltano run` would expose the run ID of the current job as an environment variable (`MELTANO_RUN_ID` or similar), we could capture that upon completion of the job and persist it in the argo workflows archive.

Being able to join these two sets of "job run data" would be really valuable to us and I'd be happy to try to contribute to this effort.

**Comment by edgarrmondragon** [comment]
Thanks for filing @menzenski!

> If meltano run could accept a --run-id=abc123 CLI argument or similar, that could be persisted as part of the runs table record for that run.

I can imagine this, though we'd prefer to keep the run ID as a UUID to avoid having to create an Alembic migration script, since in Postgres it uses the builtin `UUID` type.

Uniqueness of `run_id` is not enforced, but I wonder what problems could come from running two pipelines with the same run ID. Maybe they'd just use the same log file?

Let me know if those restrictions work for you and your workflow, or if you'd need support for arbitrary strings.

> If meltano run would expose the run ID of the current job as an environment variable (MELTANO_RUN_ID or similar), we could capture that upon completion of the job and persist it in the argo workflows archive.

I'm certain we could pass down a `MELTANO_RUN_ID` env var to the plugin's subprocess, but I don't think that would be exposed outside of it, so I'm not sure it could be retrieved.

**Comment by menzenski** [comment]
> > If meltano run could accept a --run-id=abc123 CLI argument or similar, that could be persisted as part of the runs table record for that run.
> 
> I can imagine this, though we'd prefer to keep the run ID as a UUID to avoid having to create an Alembic migration script, since in Postgres it uses the builtin `UUID` type.
> 
> Uniqueness of `run_id` is not enforced, but I wonder what problems could come from running two pipelines with the same run ID. Maybe they'd just use the same log file?
> 
> Let me know if those restrictions work for you and your workflow, or if you'd need support for arbitrary strings.

Sorry - I wasn't clear in my original message. I wasn't trying to propose that an orchestrator external to meltano should be able to set the meltano run ID. Rather, I was thinking about something like this:

* Invoke meltano with `meltano run tap-my-source target-my-destination --run-id=abc123`
* In the `runs` table, the record for this run has that persisted on the `payload` as a new `"metadata": {"run-id":"abc123"}` field. 

Or similar - it seems that the `payload` column is "just a JSON-encoded dict" (per https://github.com/meltano/meltano/blob/2988899b0f62ee7ede720da40664cc89861737c8/src/meltano/core/job/job.py#L112) so in theory it could support an additional field (alongside the existing `singer_state` property).


> > If meltano run would expose the run ID of the current job as an environment variable (MELTANO_RUN_ID or similar), we could capture that upon completion of the job and persist it in the argo workflows archive.

> I'm certain we could pass down a MELTANO_RUN_ID env var to the plugin's subprocess, but I don't think that would be exposed outside of it, so I'm not sure it could be retrieved.

For our use case, as long as it was available as an environment variable here, when the `block run completed` message is logged (on success or error) https://github.com/meltano/meltano/blob/2988899b0f62ee7ede720da40664cc89861737c8/src/meltano/cli/run.py#L153-L209 , I think we'd be able to pull it from the environment in our workflow exit handler.

**Comment by edgarrmondragon** [comment]
> * Invoke meltano with `meltano run tap-my-source target-my-destination --run-id=abc123`
> * In the `runs` table, the record for this run has that persisted on the `payload` as a new `"metadata": {"run-id":"abc123"}` field.

@menzenski Would this have a different value to the `run_id` column in the `runs` table? If so, I can imagine it could lead to some confusion.

FWIW if you wanna check out the approach, I was able to experiment with a `--run-id=...` option in #8459 and I'm able to see the value correctly set in the `runs` table:

<img width="1420" alt="Screenshot 2024-03-22 at 11 12 49 a m" src="https://github.com/meltano/meltano/assets/16805946/9c1ca6b9-5da4-419f-8aa8-9e171dde66da">

**Comment by menzenski** [comment]
@edgarrmondragon sorry for my delayed response here, I was out of office and missed your update - the draft PR https://github.com/meltano/meltano/pull/8459/files looks awesome, that'd totally work for our use case. (I confirmed that Argo Workflows is using v4 UUID strings).

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon sorry for my delayed response here, I was out of office and missed your update - the draft PR https://github.com/meltano/meltano/pull/8459/files looks awesome, that'd totally work for our use case. (I confirmed that Argo Workflows is using v4 UUID strings).

@menzenski Thanks for confirming @menzenski. I'm already in the process beta testing Meltano 3.4.0 but I could probably slip #8459 in if the team accepts it.

**Comment by menzenski** [comment]
@edgarrmondragon I put Meltano 3.4.0 into production today - we're using this new `--run-id` flag to set the Meltano run ID to the workflow ID of the Argo Workflows workflow that runs Meltano.

It works great! Huge quality-of-life improvement for us. Thanks so much for implementing this!

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon I put Meltano 3.4.0 into production today - we're using this new `--run-id` flag to set the Meltano run ID to the workflow ID of the Argo Workflows workflow that runs Meltano.
> 
> It works great! Huge quality-of-life improvement for us. Thanks so much for implementing this!

I'm glad that it's helpful!
