### ISSUE TITLE
feature: Make installation progress messages use logging instead of `click.echo`

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8503]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

We'd like to start reducing the amount of non-formatted and non-configurable output in Meltano's CLI. The installation result messages are good start:

```
Installing 1 plugin           
Installing extractor 'tap-getpocket'...
Installed extractor 'tap-getpocket'
```

### Related

* https://github.com/meltano/meltano/pull/8482#issuecomment-2042923721
* https://github.com/meltano/meltano/issues/6394

**Comment by WillDaSilva** [comment]
@edgarrmondragon Do you think it would make sense to eventually make `click.echo` a banned API using Ruff?

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon Do you think it would make sense to eventually make `click.echo` a banned API using Ruff?

Yeah, I would hope so. I want everything we output to go through our logging infra and probably make the default output format easier on the eyes.
