### ISSUE TITLE
bug: mysql-tap test returns Plugin configuration is invalid

### ISSUE THREAD

**Issue by iamfrisbee** [meltano/meltano#8521]
### Meltano Version

3.4.0

### Python Version

3.9

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Debian GNU/Linux 12 (bookworm)

### Description

I create tap-mysql extractor configuration and then run the `meltano config tap-mysql test` and receive the error `Plugin configuration is invalid` but `meltano invoke tap-mysql` is working as expected. My configuration includes an ssh tunnel and a private key; not that I think that is important but just in case. If I set the log level to debug, `meltano config tap-mysql test` prints a long stack trace of errors. Also, using discover to generate the catalog.json works fine too. Only test fails.

### Code

```python
version: 1
default_environment: dev
project_id: 736d2f60-743c-45d8-b67e-207b1211daf4
environments:
  - name: dev
  - name: staging
  - name: prod
plugins:
  extractors:
    - name: tap-mysql
      variant: transferwise
      pip_url: pipelinewise-tap-mysql
      config:
        database: dummy
        user: dummy
        host: rds.dummy.com
        port: 3306
        ssh_tunnel:
          enable: true
          host: dummy.amazonaws.com
          port: 22
          username: dummy
          private_key: dummy-pem
      select:
        - dummy-summary.*
```

**Comment by edgarrmondragon** [comment]
@iamfrisbee Can you try using the `filter_dbs` setting:

```yaml
      config:
        database: dummy
        user: dummy
        host: rds.dummy.com
        port: 3306
        filter_dbs: dummy
```

**Comment by iamfrisbee** [comment]
That fixes the issue and I get `Plugin configuration is valid`

**Comment by edgarrmondragon** [comment]
> That fixes the issue and I get `Plugin configuration is valid`

Nice, thanks for confirming!
