### ISSUE TITLE
bug: documentation for configuring plug-in python version

### ISSUE THREAD

**Issue by ilsaloving** [meltano/meltano#8543]
### Meltano Version

3.4.1

### Python Version

NA

### Bug scope

Configuration (settings parsing, validation, etc.)

### Operating System

MacOS 14.4

### Description

https://docs.meltano.com/reference/settings/#python says that you can specify a specific version of python for a particular plugin.  However, there is no explanation as to how to do that.  

It says that this has to be set when installing the plugin, but the documentation for `meltano install` makes no mention of specifying the python version to use.

**Comment by edgarrmondragon** [comment]
This would be addressed by https://github.com/meltano/meltano/issues/8374 so I'm closing this and I'll quickly tackle it
