### ISSUE TITLE
bug: Docs search broken

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/meltano#8548]
### Meltano Version

NA

### Python Version

NA

### Bug scope

Other

### Operating System

Ubuntu 22.04 LTS

### Description

Trying to search docs but results never load:

![image](https://github.com/meltano/meltano/assets/60552974/2233c6a8-0e25-4eed-8b82-9d9b89a0106a)

Looks like search requests fail due to `Invalid Application-ID or API key`.

Maybe related - search results count shows as `{count}`:

![image](https://github.com/meltano/meltano/assets/60552974/7d8ca0d8-d686-421e-a352-f87d9385cfc3)

**Comment by edgarrmondragon** [comment]
Thanks @ReubenFrankel, we're looking into it :+1:

**Comment by edgarrmondragon** [comment]
This should be fixed now :)
