### ISSUE TITLE
feature: Python 3.13 support

### ISSUE THREAD

**Issue by Nirmalendu** [meltano/meltano#8587]
### Feature scope

Other

### Description

python:3.13.0b1-slim has the least number of known security vulnerabilities. We have upgraded accordingly, unfortunately the latest python support is 3.12.
Is there an expected date for 3.13 support?
Thank you.

**Comment by edgarrmondragon** [comment]
For reference:

* [PEP 719](https://peps.python.org/pep-0719/): Python 3.13 release schedule
* Blocker: https://github.com/python-greenlet/greenlet/issues/392 OR https://github.com/sqlalchemy/sqlalchemy/milestone/92 (SQLAlchemy 2.1)
* https://github.com/python-cffi/cffi/issues/23 is only in pre-release now

There may be other dependencies that currently fail to build on Python 3.13, but these are probably the major ones.

**Comment by fcovatti** [comment]
since python 3.13 was recently released any idea if there is still plans to add the psycopg2 support?
