### ISSUE TITLE
docs: Some table-of-contents links not displaying for settings reference

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/meltano#8611]
https://docs.meltano.com/reference/settings

Seems to happen on initial page visit/reload. Internal link from navbar is fine.

[Screencast from 05-07-24 09:51:15.webm](https://github.com/meltano/meltano/assets/60552974/4aa817f5-618f-4ea0-b9ed-b4ff70b3bd10)

**Comment by edgarrmondragon** [comment]
Thanks for reporting. I think I saw this once and never again, but it does seem to be somewhat persistent 😬.

Can't find anything related in the docusaurus issue tracker: https://github.com/facebook/docusaurus/issues.

I wonder if this has been fixed and would be gone with #8417.

**Comment by edgarrmondragon** [comment]
Closing, let's hope it's gone for good
