### ISSUE TITLE
feature: hide sensitive values in `meltano config <plugin>`

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/meltano#8619]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

This is a follow-on from https://github.com/meltano/meltano/pull/7878#issuecomment-1624013519

Currently both `meltano invoke --dump=config <plugin>` and `meltano config <plugin>` will show sensitive values with no `--safe` option. 

Options we have:
* `meltano config <plugin>` work the same as ``meltano config <plugin> list`
* Have `meltano config <plugin>` default to a `--safe` option where sensitive values are replaced with ******
* Drop `meltano config <plugin>` as an option and recommend either the list subcommand or the invoke with dump feature

I'm not sure what's easiest @edgarrmondragon or feels best. I have a slight preference for adding `--safe` and recommending `invoke` to really see what the config is. @ReubenFrankel do you have any thoughts on this?

**Comment by ReubenFrankel** [comment]
I don't personally use it, but I see the primary use-case of `meltano config <plugin>` as a means to pass a plugin's config off to another application as JSON, via a file or stdout pipe.

```sh
meltano config tap-spotify > config.json
meltano config tap-spotify | jq .refresh_token
```

In those cases, I feel like you would want values not be redacted, which means if `--safe` was the default you would be passing `--unsafe` all the time. If that's the same as `meltano invoke <plugin> --dump`, then I'm in favour of removing it _eventually_.

> Have `meltano config <plugin>` default to a `--safe` option where sensitive values are replaced with ******

This is the least breaking change. I don't know how many people are using the command, but it feels better than removing it before the next major version release.

**Comment by edgarrmondragon** [comment]
> ```shell
> ```shell
> 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> In those cases, I feel like you would want values not be redacted, which means if --safe was the default you would be passing --unsafe all the time. If that's the same as meltano invoke <plugin> --dump, then I'm in favour of removing it eventually.
> 
> Have meltano config <plugin> default to a --safe option where sensitive values are replaced with ******
> 
> This is the least breaking change. I don't know how many people are using the command, but it feels better than removing it before the next major version release.
> ```

100% agree 👍. So we can do the following:

1. Make `meltano config <plugin` behave like other sub-commands and have it actually support `--safe/--unsafe`
2. Log a warning when the command is used and recommend `meltano invoke --dump=config <plugin>` as an alternative

It's probably too early to think of a v4 milestone, but this is something we can certainly remove at some point in the future.

**Comment by tayloramurphy** [comment]
The only update I'd add @edgarrmondragon is to default to `--safe`. Technically a breaking change but it's the right move for security. 

Looking at the data we have I don't believe we track subcommands on `config` so it's unclear how many people use it. We'll just track it as a change when it's done 👍
