### ISSUE TITLE
bug: Error message when `meltano run` is missing a loader is not very user friendly

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8709]
### Meltano Version

3.5.0

### Python Version

3.12

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

All

### Description

For example, when users call

```
meltano run tap-rest-api-msdk
```

they get this message:

```
block violates set requirements: Found no end in block set!
```

which doesn't tell them explicitly how they can fix the error.

### Link to Slack/Linen

https://www.linen.dev/s/meltano/t/22920536/hi-everyone-has-anyone-worked-on-a-tap-for-splunk-or-do-you-#c6677d5e-cbd1-4785-b53a-f40510d4b5e3

**Comment by NishitSingh2023** [comment]
@edgarrmondragon is this still open can I pick this up?

**Comment by edgarrmondragon** [comment]
> [@edgarrmondragon](https://github.com/edgarrmondragon) is this still open? can I pick this up?

@NishitSingh2023 Yes, it's still open! It's a couple of lines change at most, but it probably does require a bit of familiarity with Meltano concepts, so feel free to open a pull request and ask any questions you have 🙂
