### ISSUE TITLE
bug:  Multiple Variants and Lock files

### ISSUE THREAD

**Issue by visch** [meltano/meltano#8746]
### Meltano Version

3.5.1

### Python Version

3.10

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

Ubuntu 20.04

### Description

Try to take the meltano.yml from https://docs.meltano.com/guide/plugin-management/#multiple-variants and run `meltano install` and then run the required lock commands. You'll find this doesn't work.

I personally don't have the issue but dean in slack does https://meltano.slack.com/archives/C068YB1BMD5/p1725410727155789

**To Reproduce**
1. Take the yaml from https://docs.meltano.com/guide/plugin-management/#multiple-variants
2. Run meltano install
3. Run `meltano lock --update --all` as requested
4. Run `meltano install`, it won't work

To get things working.
1. Start from an empty meltano project
2. Run ` meltano add extractor tap-postgres`
3. Run `meltano add extractor tap-postgres--transferwise --inherit-from tap-postgres --variant transferwise`

Now everything works for you as your lock files are setup properly

### Link to Slack/Linen

https://meltano.slack.com/archives/C068YB1BMD5/p1725410727155789

**Comment by visch** [comment]
Related to https://github.com/meltano/meltano/issues/6731 , might want to close for that one. I'm not sure

**Comment by edgarrmondragon** [comment]
> Related to #6731 , might want to close for that one. I'm not sure

Let's do that
