### ISSUE TITLE
docs: Broken anchor links

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8805]
For example, in https://docs.meltano.com/reference/settings/#auto_install had the following links:

- [meltano add](https://docs.meltano.com/reference/settings/command-line-interface#add)
- [meltano config <plugin> test](https://docs.meltano.com/reference/settings/command-line-interface#config)
- [meltano select --list](https://docs.meltano.com/reference/settings/command-line-interface#select)
- [meltano test](https://docs.meltano.com/reference/settings/command-line-interface#test)
- [meltano invoke](https://docs.meltano.com/reference/settings/command-line-interface#invoke)
- [meltano el](https://docs.meltano.com/reference/settings/command-line-interface#el) / [meltano elt](https://docs.meltano.com/reference/settings/command-line-interface#elt)
- [meltano run](https://docs.meltano.com/reference/settings/command-line-interface#run)

but as you'll notice, they're all broken. It's probably something to do with bumping to Docusaurus 3.

**Comment by ReubenFrankel** [comment]
I think it's to do with relative links breaking when there is a trailing slash and interpreting them as child pages. When you visit https://docs.meltano.com/reference/settings#auto_install it redirects to https://docs.meltano.com/reference/settings/#auto_install.

**Comment by edgarrmondragon** [comment]
What's weird is that on a local build, the links work fine 🤔
