### ISSUE TITLE
feature: Support an environment variable for the `--full-refresh` option of `meltano run` and `meltano el|elt`

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8816]
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Many users' deployments generate or hard-code a Meltano command to run on their own infra, and modifying this command for a one-off full refresh of the data is inconvenient.

An environment variable would make triggering a full refresh in such environments considerably easier.

https://github.com/meltano/meltano/blob/b8d68748075ec8e5e464da79a694164d0c62eeca/src/meltano/cli/run.py#L59-L66

https://github.com/meltano/meltano/blob/b8d68748075ec8e5e464da79a694164d0c62eeca/src/meltano/cli/elt.py#L58-L62

- https://click.palletsprojects.com/en/8.1.x/api/#click.Parameter

### Slack

https://meltano.slack.com/archives/C069CQNHDNF/p1727713013315249?thread_ts=1727710811.205209&cid=C069CQNHDNF

**Comment by SBurwash** [comment]
👍

**Comment by edgarrmondragon** [comment]
> Hi [@edgarrmondragon](https://github.com/edgarrmondragon).. I noticed this issue and would like to contribute. Is anyone currently working on it? If not, could you please assign it to me?

@MutuT2 Go for it!
